'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {resolveLanguage,translate,catalog}=require('../src/i18n.js');
const {Service}=require('../src/core/service.cjs');
test('system language resolution and unsupported-language fallback',()=>{
  assert.equal(resolveLanguage('system','zh-TW'),'zh-CN');assert.equal(resolveLanguage('system','nl-BE'),'nl-NL');assert.equal(resolveLanguage('system','de-DE'),'en-US');assert.equal(resolveLanguage('en-US','nl-NL'),'en-US');
});
test('catalog has complete English and Dutch translations',()=>{for(const [key,values] of Object.entries(catalog)){assert.equal(values.length,2,key);for(const v of values){assert.ok(v.trim(),key);assert.doesNotMatch(v,/[\u3400-\u9fff]/,key);}assert.equal(translate(key,'zh-CN'),key);assert.equal(translate(key,'en-US'),values[0]);assert.equal(translate(key,'nl-NL'),values[1]);}});
test('unknown data is never translated',()=>{assert.equal(translate('我的项目 <script>','nl-NL'),'我的项目 <script>');});
test('count messages use singular, plural and local number formatting',()=>{assert.equal(translate('{n} 个会话','nl-NL',{n:1}),'1 sessie');assert.equal(translate('{n} 个会话','nl-NL',{n:2000}),'2.000 sessies');assert.equal(translate('已导出 {n} 条记录','en-US',{n:1}),'Exported 1 record');assert.equal(translate('{n} 条记录','zh-CN',{n:2}),'2 条记录');});
test('all literal translation calls have catalog entries',()=>{for(const filename of ['src/ui/app.js','src/ui/experience.js','src/main.cjs','src/core/report.cjs']){const code=fs.readFileSync(path.resolve(__dirname,'..',filename),'utf8');for(const match of code.matchAll(/\bt\((['"])(.*?)\1/g))assert.ok(Object.hasOwn(catalog,match[2]),filename+': '+match[2]);}});
test('language survives restart and invalid preferences are rejected',()=>{const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'language-'));const a=new Service(dir);assert.equal(a.settings.language,'system');assert.throws(()=>a.saveSettings({language:'de-DE'}));a.saveSettings({language:'nl-NL'});a.store.close();const b=new Service(dir);assert.equal(b.settings.language,'nl-NL');b.store.close();});
test('legacy settings without language migrate without changing billing data',()=>{const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'legacy-'));const a=new Service(dir);a.store.set('settings',{paid:20,theme:'dark'});a.store.close();const b=new Service(dir);assert.equal(b.settings.language,'system');assert.equal(b.settings.paid,20);assert.equal(b.settings.theme,'dark');b.store.close();});
test('renderer catalog matches canonical source',()=>{const vm=require('node:vm');const context={window:{}};vm.runInNewContext(fs.readFileSync(path.resolve(__dirname,'../src/ui/locales.js'),'utf8'),context);assert.equal(JSON.stringify(context.window.LensLocales),JSON.stringify(catalog));});
