'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
test('installer retains the 1.2 application identity and data-preserving upgrade path',()=>{const p=require('../package.json'),{UUID}=require('builder-util-runtime');assert.equal(p.build.appId,'net.subscriptionlens.desktop');assert.equal(p.build.nsis.guid,UUID.v5(p.build.appId,UUID.parse('50e065bc-3134-11e6-9bab-38c9862bdaf3')));assert.equal(p.productName,undefined);assert.equal(p.build.productName,'Subscription Lens');assert.equal(p.build.nsis.deleteAppDataOnUninstall,false);const hook=fs.readFileSync(path.resolve(__dirname,'../',p.build.nsis.include),'utf8');assert.match(hook,/hasPerUserInstallation/);assert.match(hook,/hasPerMachineInstallation/);const upstream=fs.readFileSync(path.resolve(__dirname,'../node_modules/app-builder-lib/templates/nsis/include/installUtil.nsh'),'utf8');assert.match(upstream,/\/KEEP_APP_DATA/);assert.match(upstream,/--updated/);});

test('Windows taskbar identity and shortcut metadata stay on the product',()=>{const p=require('../package.json');assert.equal(p.build.appId,'net.subscriptionlens.desktop');assert.equal(p.build.productName,'Subscription Lens');assert.equal(p.build.win.icon,'assets/icon.ico');assert.equal(p.build.nsis.createDesktopShortcut,true);const main=fs.readFileSync(path.resolve(__dirname,'../src/main.cjs'),'utf8');assert.match(main,/app\.setName\('Subscription Lens'\);\s*if\(process\.platform==='win32'\)app\.setAppUserModelId\(APP_USER_MODEL_ID\)/);assert.match(main,/const icon=process\.platform==='win32'\?path\.join\(__dirname,'\.\.\/assets\/icon\.ico'\):iconPng/);assert.match(main,/win\.setIcon\(nativeImage\.createFromPath\(icon\)\)/);assert.match(main,/win\.setAppDetails\(\{appId:APP_USER_MODEL_ID,appIconPath:icon/);});

test('macOS packaging is Apple Silicon only and includes the native router',()=>{const p=require('../package.json');assert.equal(p.build.mac.icon,'assets/icon.icns');assert.equal(p.build.mac.identity,'-');assert.equal(p.build.mac.hardenedRuntime,false);assert.equal(p.build.afterPack,'scripts/after-pack.cjs');assert.deepEqual(p.build.mac.target.map(target=>target.arch),[['arm64'],['arm64']]);assert.ok(p.build.asarUnpack.includes('assets/router/**'));assert.ok(fs.existsSync(path.resolve(__dirname,'../assets/icon.icns')));const sidecar=fs.readFileSync(path.resolve(__dirname,'../src/core/cc-switch-sidecar.cjs'),'utf8');assert.match(sidecar,/process\.platform === 'win32' \? '\.exe' : ''/);});

test('release packaging writes version-scoped SHA256 checksums',()=>{const p=require('../package.json');assert.equal(p.scripts.postdist,'node scripts/write-sha256.cjs');const script=fs.readFileSync(path.resolve(__dirname,'../scripts/write-sha256.cjs'),'utf8');assert.match(script,/createHash\('sha256'\)/);assert.match(script,/name\.includes\(`-\$\{version\}-`\)/);assert.match(script,/SHA256SUMS\.txt/);});
