'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {Store}=require('../src/core/store.cjs');const {Monitor,ccRecord,jsonRecord,providerIdentity,qwenRecord,kimiRecord,codebuddyRecord,qoderRecord,overlapMatches}=require('../src/core/monitor.cjs');
const {DatabaseSync}=require('node:sqlite');
test('Gemini thinking tokens are included once and missing prices stay unknown',()=>{const {geminiRecords}=require('../src/core/monitor.cjs');const rows=geminiRecords({sessionId:'s',messages:[{id:'r',type:'gemini',timestamp:'2026-09-16',model:'gemini-model',tokens:{input:100,cached:30,output:20,thoughts:5}}]},'p');assert.equal(rows[0].total,125);assert.equal(rows[0].reasoning,5);assert.equal(rows[0].output,25);assert.equal(rows[0].amount,null);assert.equal(rows[0].status,null);});
test('CC Switch database stays unchanged while usage corrections are imported',async()=>{const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'cc-readonly-')),source=path.join(dir,'cc.db'),db=new DatabaseSync(source);db.exec(`CREATE TABLE providers(id TEXT,name TEXT,app_type TEXT,settings_config TEXT);INSERT INTO providers VALUES('p','Provider','codex','private-configuration');CREATE TABLE proxy_request_logs(request_id TEXT PRIMARY KEY,provider_id TEXT,app_type TEXT,model TEXT,input_tokens INTEGER,output_tokens INTEGER,created_at INTEGER,total_cost_usd TEXT);INSERT INTO proxy_request_logs VALUES('r','p','codex','m',100,10,1789552800,'1.2');`);db.close();const original=fs.readFileSync(source),store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{await monitor.add('cc-switch',source);assert.deepEqual(fs.readFileSync(source),original);let q=monitor.query({},{from:'2000',to:'2100'});assert.equal(q.summary.estimated,1.2);assert.equal(q.rows[0].provider,'Provider');assert.doesNotMatch(JSON.stringify(q),/private-configuration/);const update=new DatabaseSync(source);update.exec("UPDATE proxy_request_logs SET total_cost_usd='2.3'");update.close();await monitor.scan();q=monitor.query({},{from:'2000',to:'2100'});assert.equal(q.summary.requests,1);assert.equal(q.summary.estimated,2.3);}finally{store.close();}});
test('Claude duplicate chunks and partial lines resume without double counting',async()=>{const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'claude-')),root=path.join(dir,'projects');fs.mkdirSync(root);const file=path.join(root,'session.jsonl'),record={type:'assistant',sessionId:'s',timestamp:'2026-09-16',message:{id:'m',model:'claude-model',content:'private-body',usage:{input_tokens:10,output_tokens:5,cache_read_input_tokens:20,cache_creation_input_tokens:30}}};const text=JSON.stringify(record);fs.writeFileSync(file,text+'\n'+text.slice(0,20));const store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{await monitor.add('claude',root);fs.appendFileSync(file,text.slice(20)+'\n');await monitor.scan();const q=monitor.query({},{from:'2000',to:'2100'});assert.equal(q.summary.requests,1);assert.equal(q.summary.tokens,65);assert.equal(q.summary.unpriced,1);assert.doesNotMatch(JSON.stringify(q),/private-body/);}finally{store.close();}});
test('CC Switch input semantics preserve disjoint token categories',()=>{const base={request_id:'r',created_at:1750000000,provider_id:'p',app_type:'claude',model:'m',input_tokens:100,output_tokens:20,cache_read_tokens:30,cache_creation_tokens:10};assert.equal(ccRecord(base).input,140);assert.equal(ccRecord({...base,input_token_semantics:1}).input,100);assert.equal(ccRecord({...base,app_type:'codex'}).input,110);assert.equal(ccRecord({...base,app_type:'codex',input_token_semantics:2}).input,140);});
test('JSON usage cannot override identity and rejects non-USD costs',()=>{const r={schema:'subscription-lens.usage.v1',id:'a',at:'2026-09-16',provider:'A',model:'m',usage:{input:10,output:2,provider:'B'}};assert.equal(jsonRecord(r).provider,'A');assert.equal(jsonRecord({...r,currency:'EUR'}),null);});
test('domestic provider attribution uses explicit model families and provider names',()=>{
 assert.equal(providerIdentity('Anthropic gateway','glm-4.7'),'Zhipu AI');assert.equal(providerIdentity('My proxy','qwen3-coder'),'Alibaba Cloud');assert.equal(providerIdentity('Moonshot 北京','custom-model'),'Moonshot AI');assert.equal(providerIdentity('DeepSeek API','custom-model'),'DeepSeek');assert.equal(providerIdentity('My proxy','custom-model'),'My proxy');
});
test('Qwen and Kimi records preserve disjoint token categories',()=>{
 const q=qwenRecord({schemaVersion:1,id:'q1',timestamp:'2026-09-16T10:00:00Z',sessionId:'qs',model:'qwen3-coder',source:'main',inputTokens:100,outputTokens:20,cachedTokens:60,thoughtsTokens:5,totalTokens:125,apiDurationMs:900});assert.equal(q.provider,'Alibaba Cloud');assert.equal(q.input,100);assert.equal(q.output,25);assert.equal(q.reasoning,5);assert.equal(q.total,125);
 const k=kimiRecord({type:'usage.record',model:'kimi-code/kimi-for-coding',usage:{inputOther:40,output:10,inputCacheRead:50,inputCacheCreation:5},usageScope:'turn',time:1789552800000},{relative:'sessions/work/session/agents/main/wire.jsonl',session:'session',project:'work'});assert.equal(k.provider,'Moonshot AI');assert.equal(k.input,95);assert.equal(k.cached,50);assert.equal(k.write,5);assert.equal(k.total,105);assert.equal(kimiRecord({...{},type:'usage.record',usageScope:'session',usage:{}},{}),null);
});
test('CodeBuddy prefers raw cache decomposition and supports its inclusive fallback',()=>{
 const raw=codebuddyRecord({id:'cb1',type:'message',role:'assistant',timestamp:'2026-09-16T10:00:00Z',providerData:{model:'glm-5.1',rawUsage:{prompt_tokens:27537,completion_tokens:552,prompt_cache_hit_tokens:27264,prompt_cache_miss_tokens:273,prompt_cache_write_tokens:0,completion_thinking_tokens:100}},message:{usage:{input_tokens:27537,output_tokens:552,cache_read_input_tokens:27264}}});assert.equal(raw.provider,'Zhipu AI');assert.equal(raw.input,27537);assert.equal(raw.cached,27264);assert.equal(raw.output,552);assert.equal(raw.reasoning,100);
 const fallback=codebuddyRecord({id:'cb2',type:'function_call',timestamp:1789552800000,providerData:{model:'deepseek-v4.1'},message:{usage:{input_tokens:28923,output_tokens:106,cache_read_input_tokens:28672}}});assert.equal(fallback.provider,'DeepSeek');assert.equal(fallback.input-fallback.cached,251);assert.equal(fallback.total,29029);
 assert.equal(codebuddyRecord({type:'message',role:'user',message:{usage:{input_tokens:1,output_tokens:1}}}),null);
});
test('Qoder assistant usage keeps Credits separate and skips cumulative results',()=>{
 const e=qoderRecord({type:'assistant',timestamp:'2026-09-16T10:00:00Z',session_id:'qs',message:{id:'m1',model:'qoder-model',usage:{input_tokens:100,cache_read_input_tokens:20,output_tokens:30,credits:1.25}}});
 assert.equal(e.provider,'Qoder');assert.equal(e.input,100);assert.equal(e.output,30);assert.equal(e.sourceUnit,'Credits');assert.equal(Number(e.sourceAmount)/1e15,1.25);assert.equal(e.amount,null);
 assert.equal(qoderRecord({type:'result',timestamp:'2026-09-16T10:00:01Z',total_credits:2}),null);
});
test('Qoder connector reads captured stream JSON and does not double count result totals',async()=>{
 const base=path.resolve(__dirname,'../test-results'),dir=fs.mkdtempSync(path.join(base,'qoder-')),root=path.join(dir,'.qoder'),usage=path.join(root,'usage');fs.mkdirSync(usage,{recursive:true});
 const lines=[{type:'assistant',timestamp:'2026-09-16T10:00:00Z',session_id:'s',message:{id:'m',model:'qoder-model',usage:{input_tokens:12,output_tokens:3,credits:0.5}}},{type:'result',timestamp:'2026-09-16T10:00:01Z',total_credits:0.5}];fs.writeFileSync(path.join(usage,'subscription-lens.jsonl'),lines.map(JSON.stringify).join('\n')+'\n');
 const store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{await monitor.add('qoder',root);const q=monitor.query({}, {from:'2026-09-01',to:'2026-10-01'});assert.equal(q.summary.requests,1);assert.equal(q.summary.tokens,15);assert.equal(Number(q.summary.sourceCredits),0.5);assert.equal(q.summary.sourceCreditRecords,1);}finally{store.close();}
});
test('Qoder Quest agent logs import context snapshots without duplicate counting',async()=>{
 const base=path.resolve(__dirname,'../test-results'),dir=fs.mkdtempSync(path.join(base,'qoder-quest-')),root=path.join(dir,'.qoder'),logs=path.join(root,'logs','run','questWindow');fs.mkdirSync(logs,{recursive:true});
 const line=(time,used)=>`${time} [info] [ChatSessionService] Context usage update: ${JSON.stringify({sessionId:'quest-session',requestId:'request-1',usedTokens:used,limitTokens:200000})}`;
 fs.writeFileSync(path.join(logs,'agent.log'),[line('2026-09-16 10:00:00.000',100),line('2026-09-16 10:00:05.000',250)].join('\n')+'\n');
 const store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{const source=await monitor.add('qoder',root),q=monitor.query({connection:source.id},{from:'2026-09-01',to:'2026-10-01'});assert.equal(q.summary.requests,1);assert.equal(q.summary.tokens,250);assert.equal(q.models[0],'Qoder Quest');assert.equal(q.rows[0].tokenBasis,'estimated');}finally{store.close();}
});
test('CodeBuddy connector ignores configuration and tool result files',async()=>{
 const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'codebuddy-')),root=path.join(dir,'.codebuddy'),project=path.join(root,'projects','demo'),results=path.join(project,'tool-results');fs.mkdirSync(results,{recursive:true});fs.writeFileSync(path.join(root,'settings.json'),JSON.stringify({apiKey:'private-key'}));fs.writeFileSync(path.join(results,'leak.jsonl'),JSON.stringify({type:'message',role:'assistant',timestamp:'2026-09-16',providerData:{model:'glm-5.1',rawUsage:{prompt_cache_miss_tokens:999,completion_tokens:1}}})+'\n');fs.writeFileSync(path.join(project,'session.jsonl'),[JSON.stringify({type:'message',role:'user',message:'private prompt'}),JSON.stringify({id:'cb',type:'message',role:'assistant',timestamp:'2026-09-16T10:00:00Z',providerData:{model:'glm-5.1',rawUsage:{prompt_cache_miss_tokens:273,prompt_cache_hit_tokens:27264,prompt_cache_write_tokens:0,completion_tokens:552,completion_thinking_tokens:100}}})].join('\n')+'\n');
 const store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{await monitor.add('codebuddy',root);const q=monitor.query({},{from:'2026-09-01',to:'2026-10-01'});assert.equal(q.summary.requests,1);assert.equal(q.summary.tokens,28089);assert.equal(q.rows[0].provider,'Zhipu AI');assert.doesNotMatch(JSON.stringify(q),/private prompt|private-key/);}finally{store.close();}
});
test('Qwen and Kimi connectors read only documented usage files and deduplicate rescans',async()=>{
 const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'domestic-')),qroot=path.join(dir,'qwen'),kroot=path.join(dir,'kimi'),usageDir=path.join(qroot,'usage'),wireDir=path.join(kroot,'sessions','wd_demo','session_1','agents','main');fs.mkdirSync(usageDir,{recursive:true});fs.mkdirSync(wireDir,{recursive:true});
 fs.writeFileSync(path.join(qroot,'settings.json'),JSON.stringify({apiKey:'must-not-be-read'}));fs.writeFileSync(path.join(usageDir,'token-usage-2026-09.jsonl'),JSON.stringify({schemaVersion:1,id:'q1',timestamp:'2026-09-16T10:00:00Z',localDate:'2026-09-16',localMonth:'2026-09',sessionId:'qs',model:'qwen3-coder',authType:'qwen-oauth',source:'main',inputTokens:100,outputTokens:20,cachedTokens:60,thoughtsTokens:5,totalTokens:125,apiDurationMs:900})+'\n');
 fs.writeFileSync(path.join(wireDir,'wire.jsonl'),[JSON.stringify({type:'turn.prompt',input:[{type:'text',text:'private prompt'}],time:1789552799000}),JSON.stringify({type:'usage.record',model:'kimi-code/kimi-for-coding',usage:{inputOther:40,output:10,inputCacheRead:50,inputCacheCreation:5},usageScope:'turn',time:1789552800000}),JSON.stringify({type:'usage.record',model:'kimi-code/kimi-for-coding',usage:{inputOther:40,output:10,inputCacheRead:50,inputCacheCreation:5},usageScope:'session',time:1789552800001})].join('\n')+'\n');
 const store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{await monitor.add('qwen',qroot);await monitor.add('kimi',kroot);let q=monitor.query({connection:monitor.sources[0].id},{from:'2026-09-01',to:'2026-10-01'});assert.equal(q.summary.requests,1);assert.equal(q.summary.tokens,125);q=monitor.query({connection:monitor.sources[1].id},{from:'2026-09-01',to:'2026-10-01'});assert.equal(q.summary.requests,1);assert.equal(q.summary.tokens,105);assert.doesNotMatch(JSON.stringify(q),/private prompt|must-not-be-read/);await monitor.scan();assert.equal(monitor.query({connection:monitor.sources[1].id},{from:'2026-09-01',to:'2026-10-01'}).summary.requests,1);}finally{store.close();}
});
test('provider and model distributions reconcile across costs, filters and repeated scans',async()=>{const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'monitor-')),store=new Store(path.join(dir,'data')),monitor=new Monitor(store);const file=path.join(dir,'usage.jsonl');const row=(id,provider,model,input,cost)=>({schema:'subscription-lens.usage.v1',id,at:'2026-09-16T10:00:00Z',provider,model,usage:{input,output:0},cost,status:200,latencyMs:100});
 fs.writeFileSync(file,[row('a','OpenAI','gpt-6-astra',100,{usd:'2',basis:'reported'}),row('b','OpenAI','gpt-5.6-luna',200,{usd:'1'}),row('c','Other','future',300)].map(JSON.stringify).join('\n')+'\n');
 try{await monitor.add('usage-jsonl',file);await monitor.scan();const range={from:'2026-09-01',to:'2026-10-01'},m=monitor.query({},range);assert.equal(m.summary.requests,3);assert.equal(m.summary.tokens,600);assert.equal(m.summary.estimated,1);assert.equal(m.summary.reported,2);assert.equal(m.summary.unpriced,1);assert.equal(m.summary.pricedTokens,300);assert.equal(m.summary.costPerMillion,10000);assert.equal(m.modelGroups.length,3);assert.equal(m.modelGroups.reduce((n,g)=>n+g.tokens,0),m.summary.tokens);assert.equal(m.groups.reduce((n,g)=>n+g.estimated+g.reported,0),3);assert.equal(m.groups.find(g=>g.key==='OpenAI').costPerMillion,10000);const scoped=monitor.query({provider:'OpenAI'},range);assert.equal(scoped.modelGroups.length,2);assert.equal(scoped.summary.tokens,300);assert.equal(monitor.query({provider:'OpenAI',model:'gpt-5.6-luna'},range).rows[0].total,200);monitor.setRate('Other','future',{input:'10',cached:'0',write:'0',output:'0'});assert.equal(monitor.query({},range).summary.unpriced,0);monitor.configure(monitor.sources[0].id,{enabled:false});await monitor.scan();assert.equal(monitor.query({},range).summary.requests,3);}finally{store.close();}
});
test('separate sources never merge the same request into one bill',async()=>{
 const base=path.resolve(__dirname,'../test-results'),dir=fs.mkdtempSync(path.join(base,'source-boundary-')),a=path.join(dir,'a.jsonl'),b=path.join(dir,'b.jsonl'),record={schema:'subscription-lens.usage.v1',id:'same-request',at:'2026-09-16T10:00:00Z',provider:'DeepSeek',model:'deepseek-chat',usage:{input:100,output:20},cost:{usd:'0.01',basis:'reported'},currency:'USD'};
 fs.writeFileSync(a,JSON.stringify(record)+'\n');fs.writeFileSync(b,JSON.stringify(record)+'\n');const store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{const first=await monitor.add('usage-jsonl',a),second=await monitor.add('usage-jsonl',b),range={from:'2026-09-01',to:'2026-10-01'},q=monitor.query({connection:first.id},range);assert.equal(monitor.query({connection:first.id},range).summary.requests,1);assert.equal(monitor.query({connection:second.id},range).summary.requests,1);assert.equal(monitor.query({},range).summary.requests,1);assert.equal(q.summary.overlapExact,1);assert.equal(q.rows[0].overlap.kind,'exact');}finally{store.close();}
});
test('overlap detector marks near-identical records with different IDs as possible duplicates',()=>{const event={id:'a',at:'2026-09-16T10:00:00.000Z',provider:'DeepSeek',model:'deepseek-chat',input:100,cached:0,write:0,output:20,reasoning:0,total:120},peer={...event,id:'b',at:'2026-09-16T10:00:20.000Z',sourceId:'other'};const match=overlapMatches(event,[peer]);assert.equal(match.kind,'possible');assert.deepEqual(match.sources,['other']);});
test('compatibility status distinguishes supported, partial and candidate platforms',async()=>{const dir=fs.mkdtempSync(path.join(path.resolve(__dirname,'../test-results'),'compatibility-')),file=path.join(dir,'usage.jsonl');fs.writeFileSync(file,'');const store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{await monitor.add('usage-jsonl',file);const statuses=monitor.query({}, {from:'2026-09-01',to:'2026-10-01'}).compatibility;assert.equal(statuses.find(s=>s.id==='qoder').level,'supported');assert.equal(statuses.find(s=>s.id==='qoder').connected,false);assert.equal(statuses.find(s=>s.id==='deepseek').level,'partial');assert.equal(statuses.find(s=>s.id==='trae').level,'candidate');}finally{store.close();}});
