'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {Store}=require('../src/core/store.cjs');const {Monitor,ccRecord,jsonRecord}=require('../src/core/monitor.cjs');
const {DatabaseSync}=require('node:sqlite');
test('Gemini thinking tokens are included once and missing prices stay unknown',()=>{const {geminiRecords}=require('../src/core/monitor.cjs');const rows=geminiRecords({sessionId:'s',messages:[{id:'r',type:'gemini',timestamp:'2026-09-16',model:'gemini-model',tokens:{input:100,cached:30,output:20,thoughts:5}}]},'p');assert.equal(rows[0].total,125);assert.equal(rows[0].reasoning,5);assert.equal(rows[0].output,25);assert.equal(rows[0].amount,null);assert.equal(rows[0].status,null);});
test('CC Switch database stays unchanged while usage corrections are imported',async()=>{const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'cc-readonly-')),source=path.join(dir,'cc.db'),db=new DatabaseSync(source);db.exec(`CREATE TABLE providers(id TEXT,name TEXT,app_type TEXT,settings_config TEXT);INSERT INTO providers VALUES('p','Provider','codex','private-configuration');CREATE TABLE proxy_request_logs(request_id TEXT PRIMARY KEY,provider_id TEXT,app_type TEXT,model TEXT,input_tokens INTEGER,output_tokens INTEGER,created_at INTEGER,total_cost_usd TEXT);INSERT INTO proxy_request_logs VALUES('r','p','codex','m',100,10,1789552800,'1.2');`);db.close();const original=fs.readFileSync(source),store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{await monitor.add('cc-switch',source);assert.deepEqual(fs.readFileSync(source),original);let q=monitor.query({},{from:'2000',to:'2100'});assert.equal(q.summary.estimated,1.2);assert.equal(q.rows[0].provider,'Provider');assert.doesNotMatch(JSON.stringify(q),/private-configuration/);const update=new DatabaseSync(source);update.exec("UPDATE proxy_request_logs SET total_cost_usd='2.3'");update.close();await monitor.scan();q=monitor.query({},{from:'2000',to:'2100'});assert.equal(q.summary.requests,1);assert.equal(q.summary.estimated,2.3);}finally{store.close();}});
test('Claude duplicate chunks and partial lines resume without double counting',async()=>{const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'claude-')),root=path.join(dir,'projects');fs.mkdirSync(root);const file=path.join(root,'session.jsonl'),record={type:'assistant',sessionId:'s',timestamp:'2026-09-16',message:{id:'m',model:'claude-model',content:'private-body',usage:{input_tokens:10,output_tokens:5,cache_read_input_tokens:20,cache_creation_input_tokens:30}}};const text=JSON.stringify(record);fs.writeFileSync(file,text+'\n'+text.slice(0,20));const store=new Store(path.join(dir,'data')),monitor=new Monitor(store);try{await monitor.add('claude',root);fs.appendFileSync(file,text.slice(20)+'\n');await monitor.scan();const q=monitor.query({},{from:'2000',to:'2100'});assert.equal(q.summary.requests,1);assert.equal(q.summary.tokens,65);assert.equal(q.summary.unpriced,1);assert.doesNotMatch(JSON.stringify(q),/private-body/);}finally{store.close();}});
test('CC Switch input semantics preserve disjoint token categories',()=>{const base={request_id:'r',created_at:1750000000,provider_id:'p',app_type:'claude',model:'m',input_tokens:100,output_tokens:20,cache_read_tokens:30,cache_creation_tokens:10};assert.equal(ccRecord(base).input,140);assert.equal(ccRecord({...base,input_token_semantics:1}).input,100);assert.equal(ccRecord({...base,app_type:'codex'}).input,110);assert.equal(ccRecord({...base,app_type:'codex',input_token_semantics:2}).input,140);});
test('JSON usage cannot override identity and rejects non-USD costs',()=>{const r={schema:'subscription-lens.usage.v1',id:'a',at:'2026-09-16',provider:'A',model:'m',usage:{input:10,output:2,provider:'B'}};assert.equal(jsonRecord(r).provider,'A');assert.equal(jsonRecord({...r,currency:'EUR'}),null);});
test('provider and model distributions reconcile across costs, filters and repeated scans',async()=>{const base=path.resolve(__dirname,'../test-results');fs.mkdirSync(base,{recursive:true});const dir=fs.mkdtempSync(path.join(base,'monitor-')),store=new Store(path.join(dir,'data')),monitor=new Monitor(store);const file=path.join(dir,'usage.jsonl');const row=(id,provider,model,input,cost)=>({schema:'subscription-lens.usage.v1',id,at:'2026-09-16T10:00:00Z',provider,model,usage:{input,output:0},cost,status:200,latencyMs:100});
 fs.writeFileSync(file,[row('a','OpenAI','gpt-6-astra',100,{usd:'2',basis:'reported'}),row('b','OpenAI','gpt-5.6-luna',200,{usd:'1'}),row('c','Other','future',300)].map(JSON.stringify).join('\n')+'\n');
 try{await monitor.add('usage-jsonl',file);await monitor.scan();const range={from:'2026-09-01',to:'2026-10-01'},m=monitor.query({},range);assert.equal(m.summary.requests,3);assert.equal(m.summary.tokens,600);assert.equal(m.summary.estimated,1);assert.equal(m.summary.reported,2);assert.equal(m.summary.unpriced,1);assert.equal(m.modelGroups.length,3);assert.equal(m.modelGroups.reduce((n,g)=>n+g.tokens,0),m.summary.tokens);assert.equal(m.groups.reduce((n,g)=>n+g.estimated+g.reported,0),3);const scoped=monitor.query({provider:'OpenAI'},range);assert.equal(scoped.modelGroups.length,2);assert.equal(scoped.summary.tokens,300);assert.equal(monitor.query({provider:'OpenAI',model:'gpt-5.6-luna'},range).rows[0].total,200);monitor.setRate('Other','future',{input:'10',cached:'0',write:'0',output:'0'});assert.equal(monitor.query({},range).summary.unpriced,0);monitor.configure(monitor.sources[0].id,{enabled:false});await monitor.scan();assert.equal(monitor.query({},range).summary.requests,3);}finally{store.close();}
});
