'use strict';
const icons={overview:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',list:'<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/>',models:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"/>',connect:'<path d="m8 16 8-8M7 14l-2 2a3 3 0 0 0 4 4l3-3M12 7l3-3a3 3 0 0 1 4 4l-2 2"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="var(--sidebar)"/><circle cx="15" cy="17" r="3" fill="var(--sidebar)"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',refresh:'<path d="M20 7v5h-5M4 17v-5h5M6 6a8 8 0 0 1 13 2M5 16a8 8 0 0 0 13 2"/>',export:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>',folder:'<path d="M3 6h7l2 2h9v12H3V6Z"/>'};
const svg=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.info}</svg>`;
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={page:'overview',period:'month',model:'',query:'',offset:0,metric:'cost',data:null,busy:false,dirty:false,seq:0};
const labels={overview:'总览',activity:'用量',models:'价格',sources:'连接',settings:'设置'};
const plans={pro:'Pro',prolite:'Pro Lite',plus:'Plus',free:'Free',team:'Team',business:'Business',edu:'Edu',enterprise:'Enterprise'};
const errors={missing_codex:'未找到 Codex',timeout:'连接超时',unsupported:'当前版本不支持',upstream:'账户查询失败',unavailable:'无法连接',closed:'连接已关闭',process:'无法启动 Codex',no_quota:'未返回额度',login_failed:'登录未完成'};
const locale=()=>LensI18n.resolveLanguage(state.data?.settings.language,navigator.language);
const t=(key,params)=>LensI18n.translate(key,locale(),params);
const decimal=(n,d)=>new Intl.NumberFormat(locale(),{minimumFractionDigits:d,maximumFractionDigits:d}).format(n);
const fmt={format:n=>new Intl.NumberFormat(locale()).format(n)};const compact=n=>n===null||n===undefined?'—':n>=1e9?decimal(n/1e9,2)+'B':n>=1e6?decimal(n/1e6,2)+'M':n>=1e3?decimal(n/1e3,1)+'K':fmt.format(n);
const money=n=>n===null||n===undefined?'—':new Intl.NumberFormat(locale(),{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const datetime=s=>s?new Date(s).toLocaleString(locale(),{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'—';
const clock=s=>s?new Date(s).toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit',hour12:false}):'—';
const percentage=(n,d)=>d>0?decimal(n/d*100,1)+'%':'—';
function toast(text){text=t(text);$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
async function api(name,...args){const r=await window.lens[name](...args);if(!r.ok)throw new Error(r.error);return r.value;}
function filters(){return {period:state.period,model:state.model,query:state.query,offset:state.offset,limit:50};}
async function load(){const seq=++state.seq;try{const data=await api('query',filters());if(seq!==state.seq)return;state.data=data;if(!(state.page==='settings'&&state.dirty))render();else updateHeader();}catch(e){toast(e.message);if(!state.data)$('#main').innerHTML=`<div class="empty">${t("无法读取数据，请重新打开应用。")}</div>`;}}
async function action(fn,success,button){if(button)button.disabled=true;try{const result=await fn();if(result!==null&&success)toast(typeof success==='function'?success(result):success);await load();}catch(e){toast(e.message);}finally{if(button?.isConnected)button.disabled=false;}}
function modal(title,html){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;$('#dialog').showModal();}
function applyTheme(){const theme=state.data?.settings.theme||'system';document.body.classList.toggle('dark',theme==='dark'||theme==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);}
function updateHeader(){const d=state.data;$('#update-state').textContent=d?.scanner.running?`${t("读取中 ")}${d.scanner.processed}/${d.scanner.files}`:d?.scanner.lastScan?t("更新于 ")+clock(d.scanner.lastScan):t("未开始监测");}
function periodSelect(){return `<select id="period" aria-label="${t("时间范围")}">${[['today',t("今天")],['week',t("最近 7 天")],['month',t("本月")],['cycle',t("本账期")],['all',t("全部")]].map(([v,n])=>`<option value="${v}" ${state.period===v?'selected':''}>${n}</option>`).join('')}</select>`;}
function head(title,actions='',sub=''){return `<div class="page-head"><div><h1>${title}</h1>${sub?`<div class="page-sub">${sub}</div>`:''}</div><div class="page-actions">${actions}</div></div>`;}
function exportButton(){return `<button class="button" data-action="export">${svg('export')}${t("导出")}</button>`;}
function empty(){return `${head(t("总览"))}<div class="panel onboarding empty"><div class="empty-icon">${svg('folder')}</div><h2>${t("添加 Codex 使用记录")}</h2><p>${t("选择本机的 Codex 目录，开始统计。")}</p><div class="path">${esc(state.data.detectedRoot)}</div><div class="row center"><button class="button primary" data-action="defaultRoot">${t("开始监测")}</button><button class="button" data-action="chooseRoot">${t("选择目录")}</button></div></div>`;}
function chart(){const days=state.data.days;if(!days.length)return `<div class="empty">${t("暂无记录")}</div>`;const cost=state.metric==='cost';const values=days.map(d=>cost?d.usd:d.tokens);const max=Math.max(...values,1)*1.15;const W=680,H=235,L=52,R=12,T=14,B=30,step=(W-L-R)/days.length,bw=Math.min(36,step*.55);let s=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${cost?t("每日 API 等价成本"):t("每日 Token 用量")}">`;for(let i=0;i<4;i++){const y=T+(H-T-B)*i/3,n=max*(3-i)/3;s+=`<line class="grid" x1="${L}" x2="${W-R}" y1="${y}" y2="${y}"/><text x="${L-10}" y="${y+4}" text-anchor="end">${cost?'$'+decimal(n,max>10?0:2):compact(n)}</text>`;}values.forEach((v,i)=>{const h=v/max*(H-T-B),x=L+i*step+(step-bw)/2;s+=`<rect class="bar" x="${x}" y="${H-B-h}" width="${bw}" height="${Math.max(0,h)}" rx="3"><title>${days[i].date} · ${cost?money(v):fmt.format(v)+' tokens'}</title></rect>`;if(i===0||i===values.length-1||i%Math.max(1,Math.ceil(values.length/7))===0)s+=`<text x="${x+bw/2}" y="${H-6}" text-anchor="middle">${new Date(days[i].date+'T12:00:00').toLocaleDateString(locale(),{month:'2-digit',day:'2-digit'})}</text>`;});return s+'</svg>';}
function windowLabel(q){if(q.minutes===null)return t(q.window==='primary'?'短期额度':'长期额度');const days=q.minutes>=1440;return new Intl.NumberFormat(locale(),{style:'unit',unit:days?'day':'hour',unitDisplay:'long',maximumFractionDigits:1}).format(days?Math.round(q.minutes/1440):q.minutes/60);}
function quota(){const d=state.data,q=d.quota;const connected=d.account.state==='connected';const stale=!q||Date.now()-Date.parse(q.observedAt)>300000;return `<section class="panel"><div class="panel-head"><h2>${t("套餐额度")}</h2><span class="pill ${connected&&!stale?'green':''}">${connected&&!stale?t("已连接"):q?t("历史快照"):t("未连接")}</span></div>${q?`<div class="quota-body">${q.windows.map(w=>{const expired=w.resetsAt&&w.resetsAt*1000<Date.now(),remain=Math.max(0,100-w.used);return `<div class="quota"><div class="quota-top"><span>${esc(w.label||w.limit)} · ${windowLabel(w)}</span><strong>${expired?'—':decimal(remain,0)}<small>${expired?'':t("% 剩余")}</small></strong></div><div class="track"><span style="width:${expired?0:remain}%"></span></div><div class="quota-bottom"><span class="${expired?'warning':''}">${expired?t("待刷新"):t("已用 ")+decimal(w.used,0)+'%'}</span><span>${w.resetsAt?t("重置于 {time}").replace("{time}",datetime(w.resetsAt*1000)):t("未提供重置时间")}</span></div></div>`;}).join('')}</div><div class="chart-foot"><span>${q.source==='account'?t("账户接口"):t("本机记录")} · ${datetime(q.observedAt)}</span><button class="text-button" data-page="sources">${t("管理")}</button></div>`:`<div class="empty"><p>${t("连接套餐账户，查看额度。")}</p><button class="button small" data-action="connect">${t("连接账户")}</button></div>`}</section>`;}
function rowsTable(rows){return `<div class="table-wrap"><table><thead><tr><th>${t("时间")}</th><th>${t("项目 / 模型")}</th><th>Tokens</th><th>${t("缓存读取")}</th><th>${t("API 等价成本")}</th><th></th></tr></thead><tbody>${rows.length?rows.map(e=>`<tr><td>${datetime(e.at)}</td><td>${esc(e.project)}<div class="sub">${esc(e.model)}</div></td><td>${compact(e.total)}</td><td>${compact(e.cached)}</td><td>${e.price.amount===null?`<span class="pill amber">${t("未计价")}</span>`:money(e.price.usd)}</td><td><button class="text-button" data-detail="${e.id}">${t("详情")}</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">${t("暂无记录")}</div></td></tr>`}</tbody></table></div>`;}
function overview(){const d=state.data;if(!d.settings.roots.length)return empty();const s=d.summary,has=s.events>0;return head(t("总览"),periodSelect()+exportButton(),t("本机 · Codex"))+
  `<div class="metrics"><div class="metric"><div class="metric-label">Tokens</div><div class="metric-value">${has?compact(s.tokens):'—'}</div><div class="metric-note">${t("{n} 条记录",{n:s.events})} · ${t("{n} 个会话",{n:s.sessions})}</div></div><div class="metric"><div class="metric-label">${t("API 等价成本")}</div><div class="metric-value">${has?money(s.usd):'—'}</div><div class="metric-note">Standard · USD</div></div><div class="metric"><div class="metric-label">${t("缓存读取占比")}</div><div class="metric-value">${has?percentage(s.cached,s.tokens-s.output):'—'}</div><div class="metric-note">${compact(s.cached)}${t(" 缓存 Tokens")}</div></div><div class="metric"><div class="metric-label">${t("计价覆盖率")}</div><div class="metric-value">${has?percentage(s.pricedTokens,s.tokens):'—'}</div><div class="metric-note">${t("{n} 条未计价",{n:s.unpriced})}</div></div></div>
  <div class="two-col"><section class="panel"><div class="panel-head"><div><h2>${t("用量趋势")}</h2><p>${d.days.length?d.days[0].date+' — '+d.days.at(-1).date:t("暂无记录")}</p></div><div class="segments"><button data-metric="cost" class="${state.metric==='cost'?'active':''}">${t("成本")}</button><button data-metric="tokens" class="${state.metric==='tokens'?'active':''}">Tokens</button></div></div><div class="chart-area">${chart()}</div><div class="chart-foot"><span>${state.metric==='cost'?t("已计价记录"):t("已采集记录")}</span><span>${esc(d.timezone)}</span></div></section>${quota()}</div>
  <div class="bottom-col"><section class="panel"><div class="panel-head"><h2>${t("模型用量")}</h2><button class="text-button" data-page="models">${t("价格")}</button></div><div class="model-bars">${d.models.length?d.models.slice(0,6).map(m=>`<div class="model-row"><div class="model-name"><span>${esc(m.model)}</span><strong>${money(m.usd)} <span class="muted">· ${compact(m.tokens)}</span></strong></div><div class="model-track"><span style="width:${s.tokens?m.tokens/s.tokens*100:0}%"></span></div></div>`).join(''):`<div class="empty">${t("暂无记录")}</div>`}</div></section><section class="panel value-panel"><div class="row" style="justify-content:space-between"><h2>${t("账期对比")}</h2><button class="text-button" data-page="settings">${t("设置")}</button></div><div class="large-number">${s.diff===null?'—':(s.diff>=0?'+':'−')+money(Math.abs(s.diff))}</div><div class="info-row"><span>${t("套餐实付")}</span><strong>${money(d.settings.paid)}</strong></div><div class="info-row"><span>${t("额外额度")}</span><span>${money(d.settings.extra)}</span></div><div class="info-row"><span>${t("费用覆盖倍数")}</span><span>${s.ratio===null?'—':decimal(s.ratio,2)+'×'}</span></div><div class="caption" style="margin-top:15px">${d.settings.paid===null?t("填写账期实付后计算。"):state.period!=='cycle'?t("选择“本账期”查看对比。"):t("API 等价成本减去套餐与额外额度实付。")}</div></section></div>
  <section class="panel"><div class="table-title"><h2>${t("最近记录")}</h2><button class="text-button" data-page="activity">${t("查看全部")}</button></div>${rowsTable(d.rows.slice(0,5))}</section><div class="footnote"><span>${t("价格 ")}${esc(d.catalog.asOf)}${t(" · 按此价格快照估算，不含工具费用")}</span><span>${s.unpriced?t("存在未计价记录"):t("已记录数据")}${t(" · API 等价成本非实际账单")}</span></div>`;}
function activity(){const d=state.data;return head(t("用量"),periodSelect()+exportButton())+`<div class="filters"><input class="input" id="search" aria-label="${t("搜索项目或会话")}" placeholder="${t("搜索项目、模型或会话")}" value="${esc(state.query)}"><select id="model" aria-label="${t("筛选模型")}"><option value="">${t("全部模型")}</option>${d.allModels.map(m=>`<option value="${esc(m)}" ${state.model===m?'selected':''}>${esc(m)}</option>`).join('')}</select><span class="pill">${t("{n} 条记录",{n:d.summary.events})}</span></div><section class="panel">${rowsTable(d.rows)}<div class="pagination"><span>${d.summary.events?d.offset+1:0}–${Math.min(d.offset+d.limit,d.summary.events)} / ${fmt.format(d.summary.events)}</span><div class="row"><button class="button small" data-action="prev" ${!d.offset?'disabled':''}>${t("上一页")}</button><button class="button small" data-action="next" ${d.offset+d.limit>=d.summary.events?'disabled':''}>${t("下一页")}</button></div></div></section>`;}
function models(){const d=state.data;return head(t("价格"),`<button class="button" data-action="exportPrices">${t("导出")}</button><button class="button" data-action="importPrices">${t("导入")}</button>`,t("USD / 百万 Tokens"))+`<div class="notice">${t("Standard 基准 · ")}${esc(d.catalog.asOf)}${t(" · 按当前目录重估历史用量。")}<button class="text-button" data-action="openPricing" style="margin-left:14px">${t("官方价格 ↗")}</button></div><section class="panel"><div class="table-wrap"><table><thead><tr><th>${t("模型")}</th><th>${t("普通输入")}</th><th>${t("缓存读取")}</th><th>${t("缓存写入")}</th><th>${t("输出")}</th><th>${t("长上下文阈值")}</th></tr></thead><tbody>${Object.entries(d.catalog.models).map(([m,r])=>`<tr><td>${esc(m)}</td>${['input','cached','write','output'].map(k=>`<td>${r.standard[k]===null?'—':'$'+esc(r.standard[k])}</td>`).join('')}<td>${r.threshold?compact(r.threshold):'—'}</td></tr>`).join('')}</tbody></table></div></section><div class="section-gap row"><button class="button small" data-action="resetPrices">${t("恢复内置价格")}</button><span class="caption">${esc(d.catalog.version)}</span></div><div class="notice section-gap">${t("长上下文自动使用对应档位。缺少模型或分类价格的记录保留为未计价。价格导入会重新计算已有记录。")}</div>`;}
function sources(){const d=state.data,a=d.account;const connected=a.state==='connected',waiting=a.state==='awaiting_login';const label=connected?t("已连接"):waiting?t("等待登录"):a.state==='connecting'?t("连接中"):a.state==='signed_out'?t("未登录"):a.state==='error'||a.state==='degraded'?t("连接异常"):t("未连接");return head(t("连接"))+`<div class="grid-2"><section class="panel padded"><div class="connection-head"><h2>${t("Codex 使用记录")}</h2><span class="pill ${d.settings.roots.length?'green':''}">${d.settings.roots.length?t("已添加"):t("未添加")}</span></div>${d.settings.roots.map(r=>`<div class="path-item">${esc(r)}</div>`).join('')}<div class="source-count"><div><strong>${d.stats.sessions}</strong><small>${t("会话")}</small></div><div><strong>${fmt.format(d.stats.records)}</strong><small>${t("用量记录")}</small></div><div><strong>${d.fileStats.files}</strong><small>${t("文件")}</small></div></div><div class="row"><button class="button" data-action="chooseRoot">${t("添加目录")}</button><button class="button" data-action="rescan" ${!d.settings.roots.length?'disabled':''}>${t("重新扫描")}</button></div>${d.scanner.errors||d.fileStats.errors?`<p class="connection-copy">${t("{n} 个文件读取失败",{n:d.scanner.errors})} · ${t("{n} 条记录未解析",{n:d.fileStats.errors})}</p>`:''}</section><section class="panel padded"><div class="connection-head"><h2>${t("套餐账户")}</h2><span class="pill ${connected?'green':a.lastError?'amber':''}">${label}</span></div><div class="info-row"><span>${t("套餐")}</span><span>${esc(plans[a.plan]||a.plan||'—')}</span></div><div class="info-row"><span>${t("最近查询")}</span><span>${datetime(a.updatedAt)}</span></div><div class="info-row"><span>${t("账户累计 Tokens")}</span><span>${compact(a.usage?.lifetimeTokens)}</span></div>${a.lastError?`<p class="connection-copy">${esc(t(errors[a.lastError]||t("查询失败")))}</p>`:`<p class="connection-copy">${t("使用 Codex 已登录的套餐账户。")}</p>`}<div class="row"><button class="button primary" data-action="${waiting?'cancelLogin':a.state==='signed_out'?'login':'connect'}">${waiting?t("取消登录"):a.state==='signed_out'?t("登录 ChatGPT"):connected?t("刷新连接"):t("连接账户")}</button>${d.settings.accountEnabled?`<button class="button" data-action="disconnect">${t("断开")}</button>`:''}<button class="text-button" data-action="chooseCodex">${t("选择 Codex 程序")}</button></div></section><section class="panel padded full"><h2>${t("数据范围")}</h2><div class="info-row"><span>${t("本机明细")}</span><span>${d.stats.earliest?datetime(d.stats.earliest)+' — '+datetime(d.stats.latest):'—'}</span></div><div class="info-row"><span>${t("账户汇总")}</span><span>${a.usage?t("官方接口返回范围"):t("未获取")}</span></div><div class="info-row"><span>${t("其他设备 / 云端任务明细")}</span><span>${t("未接入")}</span></div><div class="info-row"><span>${t("普通 ChatGPT 聊天")}</span><span>${t("不支持")}</span></div></section></div>`;}
function settings(){const s=state.data.settings;return head(t("设置"))+`<form id="settings-form"><div class="grid-2"><section class="panel form-section"><h2>${t("账期")}</h2><div class="field-pair"><div class="field"><label for="cycleStart">${t("开始日期")}</label><input class="input" id="cycleStart" name="cycleStart" type="date" required value="${esc(s.cycleStart)}"></div><div class="field"><label for="cycleEnd">${t("结束日期（不含当天）")}</label><input class="input" id="cycleEnd" name="cycleEnd" type="date" required value="${esc(s.cycleEnd)}"></div></div><div class="field-pair"><div class="field"><label for="paid">${t("套餐实付 · USD")}</label><input class="input" id="paid" name="paid" type="number" min="0" max="1000000" step="0.01" placeholder="${t("未填写")}" value="${s.paid===null?'':s.paid}"></div><div class="field"><label for="extra">${t("额外额度 · USD")}</label><input class="input" id="extra" name="extra" type="number" min="0" max="1000000" step="0.01" required value="${s.extra}"></div></div><div class="caption">${t("时区：")}${esc(state.data.timezone)}${t("。非美元账单请先换算为 USD。")}</div></section><section class="panel form-section"><h2>${t("应用")}</h2><div class="field"><label for="language">${t("语言")}</label><select id="language" name="language">${[['system',t('跟随系统')],['zh-CN','简体中文'],['en-US','English'],['nl-NL','Nederlands']].map(([v,label])=>`<option value="${v}" ${s.language===v?'selected':''}>${label}</option>`).join('')}</select></div><div class="field"><label for="theme">${t("外观")}</label><select id="theme" name="theme">${[['system',t("跟随系统")],['light',t("浅色")],['dark',t("深色")]].map(([v,t])=>`<option value="${v}" ${s.theme===v?'selected':''}>${t}</option>`).join('')}</select></div><label class="check-line"><input name="tray" type="checkbox" ${s.tray?'checked':''}>${t("关闭窗口后继续在托盘运行")}</label><label class="check-line"><input name="startup" type="checkbox" ${s.startup?'checked':''}>${t("登录 Windows 时启动")}</label><div class="section-gap"><button type="button" class="button small" data-action="diagnostics">${t("导出诊断")}</button></div></section></div><div class="section-gap"><button class="button primary" type="submit">${t("保存")}</button></div></form>`;}
function render(){if(!state.data)return;localizeShell();const focus=document.activeElement;const remembered=focus?.id==='search'?{id:'search',start:focus.selectionStart,end:focus.selectionEnd}:null;applyTheme();updateHeader();$('#breadcrumb').textContent=t(labels[state.page]);document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===state.page));$('#main').innerHTML=({overview,activity,models,sources,settings}[state.page])();if(remembered&&$('#search')){$('#search').focus();$('#search').setSelectionRange(remembered.start,remembered.end);}}
function navigate(page){if(!labels[page])return;state.page=page;state.dirty=false;state.offset=0;if(page!=='activity'){state.query='';state.model='';}load();window.scrollTo(0,0);}
function detail(id){const e=state.data.rows.find(r=>r.id===id);if(!e)return;const reasons={model:t("没有匹配的模型价格"),counter:t("累计计数不一致"),tokens:t("缺少 Token 分类"),invalid:t("Token 分类不一致"),context:t("缺少上下文档位价格"),category:t("缺少分类价格")};modal(t("用量详情"),`<p>${esc(e.model)} · ${datetime(e.at)}<br>${esc(e.project)}</p>${[[t("普通输入"),e.input===null||e.cached===null||e.write===null?null:e.input-e.cached-e.write,'input'],[t("缓存读取"),e.cached,'cached'],[t("缓存写入"),e.write,'write'],[t("输出"),e.output,'output']].map(([name,n,k])=>`<div class="info-row"><span>${name} · ${n===null?'—':fmt.format(n)}</span><span>${e.price.parts?money(Number(BigInt(e.price.parts[k]))/1e15):'—'}</span></div>`).join('')}<div class="info-row"><span>${t("其中推理（已含在输出）")}</span><span>${fmt.format(e.reasoning)}</span></div><div class="detail-price">${money(e.price.usd)}</div><p>${e.price.reason?esc(reasons[e.price.reason]||t("未计价")):esc(e.price.version)+' · '+(e.price.context==='long'?t("长上下文"):t("标准上下文"))}<br>${t("会话 ")}${esc(e.session)}${e.quality!=='complete'?`<br>${t("记录状态：")}`+esc(t(({reset:t("计数已重置"),partial_history:t("历史记录不完整"),ambiguous:t("计数存在歧义")})[e.quality]||e.quality)):''}</p>`);}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.page){navigate(b.dataset.page);return;}if(b.dataset.metric){state.metric=b.dataset.metric;render();return;}if(b.dataset.detail){detail(b.dataset.detail);return;}const a=b.dataset.action;if(!a)return;
  const handlers={defaultRoot:()=>api('useDetectedRoot'),chooseRoot:()=>api('chooseRoot'),chooseCodex:()=>api('chooseCodex'),connect:()=>api('connect'),login:()=>api('login'),cancelLogin:()=>api('cancelLogin'),disconnect:()=>api('disconnect'),rescan:()=>api('rescan'),export:()=>api('exportCsv',filters()),exportPrices:()=>api('exportPrices'),importPrices:()=>api('importPrices'),resetPrices:()=>api('resetPrices'),openPricing:()=>api('openPricing'),diagnostics:()=>api('diagnostics')};
  if(a==='prev'||a==='next'){state.offset=Math.max(0,state.offset+(a==='next'?50:-50));load();return;}
  if(handlers[a])action(handlers[a],a==='export'?n=>t("已导出 {n} 条记录",{n}):['importPrices','resetPrices'].includes(a)?t("价格已更新"):a==='rescan'?t("扫描完成"):undefined,b);
});
document.addEventListener('change',e=>{if(e.target.id==='period'){state.period=e.target.value;state.offset=0;load();}if(e.target.id==='model'){state.model=e.target.value;state.offset=0;load();}if(e.target.closest('#settings-form'))state.dirty=true;});
let searchTimer;document.addEventListener('input',e=>{if(e.target.id==='search'){state.query=e.target.value;state.offset=0;clearTimeout(searchTimer);searchTimer=setTimeout(load,180);}if(e.target.closest('#settings-form'))state.dirty=true;});
document.addEventListener('submit',e=>{if(e.target.id!=='settings-form')return;e.preventDefault();const f=new FormData(e.target);action(async()=>{const r=await api('saveSettings',{cycleStart:f.get('cycleStart'),cycleEnd:f.get('cycleEnd'),paid:f.get('paid')===''?null:Number(f.get('paid')),extra:Number(f.get('extra')),language:f.get('language'),theme:f.get('theme'),tray:f.has('tray'),startup:f.has('startup')});state.dirty=false;state.data.settings=r;return r;},()=>t('已保存'));});
$('#refresh').addEventListener('click',()=>action(()=>api('refresh')));$('#close-dialog').addEventListener('click',()=>$('#dialog').close());
$('#about').addEventListener('click',()=>modal(t("余量"),`<p>Subscription Lens 1.3.0-beta.1</p><p>${t("Codex 套餐用量监测。数据保存在本机，应用不保存聊天正文。")}</p><p>${t("API 等价成本按价格快照计算，不含工具费用。普通 ChatGPT 聊天和未接入设备不计入明细。")}</p><p>${t("独立工具，与 OpenAI 无隶属关系。")}</p><button class="button" data-action="openPricing">${t("价格来源")}</button>`));
document.querySelectorAll('[data-icon]').forEach(i=>i.innerHTML=svg(i.dataset.icon));
localizeShell();window.lens.changed(()=>load());matchMedia('(prefers-color-scheme:dark)').addEventListener('change',applyTheme);load();

function localizeShell(){document.documentElement.lang=locale();document.title=t('余量');document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-title]').forEach(el=>el.title=t(el.dataset.i18nTitle));document.querySelectorAll('[data-i18n-label]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nLabel)));}
