'use strict';
// Product-level views reuse the same ledger, account connection and window.
Object.assign(state,{view:'sessions',sort:'cost',project:'',session:'',day:'',unpriced:false,quotaKey:''});
const baseFilters=filters,baseRender=render,baseSettings=settings,baseSources=sources,baseNavigate=navigate;
const baseChart=chart;
chart=function(){let index=0;return baseChart().replace(/<rect class="bar"[\s\S]*?<\/rect>/g,bar=>{const d=state.data.days[index++];return `<g class="chart-hit" data-chart-day="${d.date}" role="button" tabindex="0" aria-label="${d.date}">${bar}</g>`;});};
filters=()=>({...baseFilters(),project:state.project,session:state.session,day:state.day,unpriced:state.unpriced,sort:state.sort});
const pricedValue=s=>s.unpriced>0&&s.unpriced===s.events?null:s.usd;
const dateOnly=value=>new Date(value+'T12:00:00').toLocaleDateString(locale(),{year:'numeric',month:'short',day:'numeric'});
function duration(seconds){if(seconds===null||!Number.isFinite(seconds))return '—';const minutes=Math.max(1,Math.ceil(seconds/60));const f=(n,unit)=>new Intl.NumberFormat(locale(),{style:'unit',unit,unitDisplay:'short',maximumFractionDigits:0}).format(n);if(minutes<60)return f(minutes,'minute');if(minutes<1440)return f(Math.floor(minutes/60),'hour')+' '+f(minutes%60,'minute');return f(Math.floor(minutes/1440),'day')+' '+f(Math.floor(minutes%1440/60),'hour');}
function selectedQuota(){const rows=state.data.outlooks||[];const codex=rows.filter(w=>w.limit==='codex');return rows.find(w=>w.limit+':'+w.window===state.quotaKey)||[...(codex.length?codex:rows)].sort((a,b)=>b.used-a.used)[0];}
function quotaStatus(w){return t(({stale:'额度需要刷新',expired:'等待重置确认',exhausted:'额度已用尽',learning:'正在积累额度观测',risk:'按近期速度可能提前用尽',on_track:'按近期速度可用至重置',uncertain:'暂不能确定是否够用'})[w?.state]||'未连接');}
function quotaCard(compact=false){const d=state.data,w=selectedQuota();if(!w)return `<section class="panel quota-card"><div class="panel-head"><h2>${help('套餐额度')}</h2></div><div class="empty"><p>${t('连接套餐账户，查看额度。')}</p><button class="button primary" data-action="connect">${t('连接账户')}</button><button class="text-button" data-page="sources">${t('管理')}</button></div></section>`;
  const live=!['stale','expired'].includes(w.state),tone=['risk','exhausted'].includes(w.state)?'warning':'';
  const choice=`<select id="quota-window" aria-label="${t('选择额度窗口')}">${d.outlooks.map(q=>`<option value="${esc(q.limit+':'+q.window)}" ${q===w?'selected':''}>${esc(q.label||q.limit)} · ${windowLabel(q)}</option>`).join('')}</select>`;
  return `<section class="panel quota-card"><div class="panel-head"><h2>${help('套餐额度')}</h2>${choice}</div><div class="quota-main"><div><span class="quota-number">${live?decimal(w.remaining,0):'—'}<small>${live?'%':''}</small></span><span class="muted">${t('剩余额度')}</span></div><div class="reset-time"><strong>${duration(w.secondsToReset)}</strong><span>${t('距重置')}</span></div></div><div class="quota-meter"><span style="width:${live?w.remaining:0}%"></span></div><div class="pace-line ${tone}"><span class="status-dot"></span><strong>${quotaStatus(w)}</strong>${!live?`<button class="text-button" data-action="connect">${t('刷新连接')}</button>`:''}</div>${w.forecast?`<div class="pace-detail">${t('按最近 {n} 分钟推算',{n:Math.round(w.forecast.minutes)})} · ${t('预计剩余')} ${duration(w.forecast.fastSeconds)} – ${duration(w.forecast.slowSeconds)}<span title="${t('持续当前使用速度的估算，实际可用时间会变化。')}"> ⓘ</span></div>`:`<div class="pace-detail">${live?t('至少15分钟的有效变化后提供估算。'):t('最近观测')+' '+datetime(w.observedAt)}</div>`}${!compact?`<div class="quota-footer"><span class="pill ${live?'green':''}">${live?t('已连接'):t('历史快照')}</span><button class="text-button" data-page="sources">${t('管理')}</button></div>`:''}</section>`;
}
function billingCard(){const c=state.data.cycle;if(c.paid===null)return `<section class="panel billing-card"><h2>${t('本账期')}</h2><p>${dateOnly(c.start)} — ${dateOnly(c.end)}</p><div class="bill-value">${money(pricedValue(c))}</div><span class="caption">${t('已计价的 API 等价成本')}</span><div class="section-gap"><button class="button" data-page="settings">${t('填写套餐实付')}</button></div></section>`;
  const passed=c.diff!==null&&c.diff>=0;const unknown=pricedValue(c)===null;return `<section class="panel billing-card"><div class="row between"><h2>${t('本账期')}</h2><button class="text-button" data-page="settings">${t('设置')}</button></div><p>${dateOnly(c.start)} — ${dateOnly(c.end)}</p><div class="bill-value">${money(pricedValue(c))} <small>/ ${money(c.paid)}</small></div><div class="caption">${t('API 等价成本 / 账期实付')}</div><div class="bill-progress"><span style="width:${Math.min(100,Math.max(0,(c.progress||0)*100))}%"></span></div><div class="bill-result"><strong>${t(unknown?'尚无可计价记录':passed?'已超过实付':'距覆盖实付还差')}</strong><span>${money(unknown?null:passed?c.diff:c.remaining)}</span></div><div class="caption">${c.unpriced?t('部分记录未计价，当前金额为已计价部分。'):t('仅基于已采集记录，不代表实际退款或现金节省。')}</div></section>`;}
function healthSummary(){const d=state.data,h=d.health,n=h.readErrors+h.parseErrors+h.partial+d.summary.unpriced;return `<button class="health-link ${n?'warning':''}" data-action="health"><span class="status-dot"></span>${n?t('数据需要核对'):t('数据状态')} · ${t('计价覆盖率')} ${percentage(d.summary.pricedTokens,d.summary.tokens)} <span>↗</span></button>`;}
function projectCard(){const d=state.data;return `<section class="panel project-card"><div class="panel-head"><h2>${t('用在哪些项目')}</h2><button class="text-button" data-page="activity">${t('查看全部')}</button></div><div class="project-list">${d.projects.length?d.projects.slice(0,5).map(p=>`<button class="project-item" data-project="${esc(p.key)}"><div class="row between"><span>${esc(p.key)}</span><strong>${money(pricedValue(p))}</strong></div><div class="model-track"><span style="width:${d.summary.usd?p.usd/d.summary.usd*100:0}%"></span></div><div class="row between caption"><span>${t('{n} 个会话',{n:p.sessions})}</span><span>${compact(p.tokens)} tokens</span></div></button>`).join(''):`<div class="empty">${t('暂无记录')}</div>`}</div></section>`;}
function modelAdviceCard(){const a=state.data.mixAdvice;if(!a||a.state!=='ready')return `<section class="panel model-advice-card"><div class="panel-head"><div><h2>${help('模型组合')}</h2><p>${t('正在学习你的模型习惯和额度速度')}</p></div><span class="pill">${t('学习中')}</span></div><div class="advice-empty">${t('至少使用两个可计价模型，并积累15分钟额度变化后生成建议。')}</div></section>`;
 const current=new Map(a.current.map(m=>[m.model,m.share])),title=a.basis==='local_history'?t('基于本地历史用量'):a.direction==='reduce'?t('降低高强度模型占比'):a.direction==='increase'?t('可提高高强度模型占比'):t('维持当前模型组合'),pace=a.paceChange===null?t('等待实时额度速度'):a.paceChange===0?t('当前速度接近目标'):t(a.paceChange>0?'目标速度提高 {n}%':'目标速度降低 {n}%',{n:Math.abs(a.paceChange)});
 return `<section class="panel model-advice-card"><div class="panel-head"><div><h2>${help('模型组合')}</h2><p>${title}</p></div><span class="pill ${a.confidence==='medium'?'green':''}">${help(a.confidence==='medium'?'中等可信度':'低可信度','建议可信度')}</span></div><div class="advice-pace"><strong>${pace}</strong><span>${t('以当前额度窗口重置时间为目标')}</span></div><div class="advice-models">${[...a.recommended].sort((x,y)=>y.share-x.share).slice(0,4).map(m=>{const before=current.get(m.model)||0,delta=Math.round((m.share-before)*100);return `<div class="advice-row"><span title="${esc(m.model)}">${esc(m.model)}</span><div class="model-track"><span style="width:${Math.max(2,m.share*100)}%"></span></div><strong>${Math.round(m.share*100)}%</strong><small class="${delta>0?'green':delta<0?'warning':''}">${delta?(delta>0?'+':'')+delta+'%':'—'}</small></div>`;}).join('')}</div><div class="advice-note">${a.basis==='local_history'?t('建议基于已有本地历史；连接并观测额度后会校准。'):`${t('依据近14天模型用量、')}${help('API 等价强度')}${t('和近期额度速度；下个窗口会继续校准。')}`}</div></section>`;}
function trendCard(){const d=state.data,days=d.days||[],cost=state.metric==='cost',value=x=>cost?Number(x.usd||0):Number(x.tokens||0),active=days.filter(x=>x.events>0),total=days.reduce((n,x)=>n+value(x),0),avg=active.length?total/active.length:0,peak=active.reduce((a,b)=>value(b)>value(a)?b:a,null),recent=days.slice(-7).reduce((n,x)=>n+value(x),0),prior=days.slice(-14,-7).reduce((n,x)=>n+value(x),0),change=prior?((recent-prior)/prior*100):null;
 const metricLabel=cost?t('成本'):'Tokens';
 return `<section class="panel trend-card"><div class="panel-head"><div><h2>${t('用量趋势')}</h2><p>${days.length?dateOnly(days[0].date)+' — '+dateOnly(days.at(-1).date):t('暂无记录')}</p></div><div class="segments"><button data-metric="cost" class="${cost?'active':''}">${t('成本')}</button><button data-metric="tokens" class="${!cost?'active':''}">Tokens</button></div></div><div class="trend-stats"><div><span>${t('日均 {metric}',{metric:metricLabel})}</span><strong>${cost?money(avg):compact(avg)}</strong><small>${t('仅含活跃日')}</small></div><div><span>${t('峰值日')}</span><strong>${peak?dateOnly(peak.date):'—'}</strong><small>${peak?(cost?money(value(peak)):compact(value(peak))):'—'}</small></div><div><span>${t('活跃天数')}</span><strong>${fmt.format(active.length)}</strong><small>${t('共 {n} 天',{n:days.length})}</small></div><div><span>${t('较前 7 天')}</span><strong class="${change!==null&&change>0?'warning':change!==null?'green':''}">${change===null?'—':(change>=0?'+':'')+decimal(change,1)+'%'}</strong><small>${t('最近 7 天')}</small></div></div><div class="chart-area">${chart()}</div><div class="trend-footer"><span>${t('点击柱状图查看当天明细')}</span><span>${cost?t('已计价记录'):t('已采集记录')} · ${esc(d.timezone)}</span></div></section>`;}
overview=function(){const d=state.data;if(!d.settings.roots.length&&!d.stats.records)return empty();const s=d.summary;const change=d.comparison?.change;
 return head(t('总览'),periodSelect()+`<button class="button" data-action="report">${t('分享摘要')}</button><button class="button" data-action="compact" title="Ctrl+Shift+M">${t('专注窗口')}</button>`)+`<div class="decision-grid">${quotaCard()}${billingCard()}</div><div class="metrics"><div class="metric"><div class="metric-label">${help('Tokens')}</div><div class="metric-value">${compact(s.tokens)}</div><div class="metric-note">${t('{n} 个会话',{n:s.sessions})}</div></div><div class="metric"><div class="metric-label">${help('API 等价成本')}</div><div class="metric-value">${money(pricedValue(s))}</div><div class="metric-note">${change===null||change===undefined?t('已计价记录'):(change>=0?'+':'−')+decimal(Math.abs(change*100),1)+'% · '+t('较前一等长时段')}</div></div><div class="metric"><div class="metric-label">${help('缓存读取占比')}</div><div class="metric-value">${percentage(s.cached,s.tokens-s.output)}</div><div class="metric-note">${compact(s.cached)} tokens</div></div><div class="metric"><div class="metric-label">${help('计价覆盖率')}</div><div class="metric-value">${percentage(s.pricedTokens,s.tokens)}</div><button class="text-button" data-action="health">${t('{n} 条未计价',{n:s.unpriced})} ↗</button></div></div><div class="two-col">${trendCard()}${projectCard()}</div>${modelAdviceCard()}<div class="overview-footer">${healthSummary()}<span class="caption">${t('价格')} ${esc(d.catalog.asOf)} · Standard · USD</span></div>`;
};
function filterChips(){const chips=[['project',state.project],['session',state.session?state.session.slice(0,12):''],['day',state.day],['unpriced',state.unpriced?t('未计价'):'']].filter(([,v])=>v);return chips.length?`<div class="filter-chips">${chips.map(([key,value])=>`<button class="chip" data-clear="${key}">${esc(value)} ×</button>`).join('')}<button class="text-button" data-action="clearFilters">${t('清除筛选')}</button></div>`:'';}
function sessionsTable(){const d=state.data;return `<div class="table-wrap"><table><thead><tr><th>${t('会话 / 项目')}</th><th>${t('最近活动')}</th><th>Tokens</th><th>${t('API 等价成本')}</th><th></th></tr></thead><tbody>${d.sessions.length?d.sessions.map(s=>`<tr><td><strong>${esc(s.project)}</strong><div class="sub">${esc(s.key.slice(0,12))} · ${esc(s.models.join(', '))}</div>${s.parent?`<span class="pill">${t('子任务')}</span>`:''}</td><td>${datetime(s.last)}</td><td>${compact(s.tokens)}</td><td>${money(pricedValue(s))}${s.unpriced?`<div class="sub warning">${t('{n} 条未计价',{n:s.unpriced})}</div>`:''}</td><td><button class="text-button" data-session="${esc(s.key)}">${t('查看记录')} →</button></td></tr>`).join(''):`<tr><td colspan="5"><div class="empty">${t('暂无记录')}</div></td></tr>`}</tbody></table></div>`;}
activity=function(){const d=state.data,total=state.view==='sessions'?d.sessionTotal:d.summary.events;const deviceFilter=`<select id="device" aria-label="${t('筛选设备')}"><option value="">${t('全部设备')}</option>${d.devices.map(device=>`<option value="${esc(device.id)}" ${state.device===device.id?'selected':''}>${esc(device.label)}</option>`).join('')}</select>`;return head(t('用量'),periodSelect()+exportButton())+`<div class="usage-toolbar"><div class="segments"><button data-view="sessions" class="${state.view==='sessions'?'active':''}">${t('会话')}</button><button data-view="records" class="${state.view==='records'?'active':''}">${t('用量记录')}</button></div><select id="sort" aria-label="${t('排序')}"><option value="cost" ${state.sort==='cost'?'selected':''}>${t('成本最高')}</option><option value="recent" ${state.sort==='recent'?'selected':''}>${t('最近活动')}</option></select><span class="caption">${money(d.summary.usd)} · ${compact(d.summary.tokens)} tokens</span></div><div class="filters"><input class="input" id="search" aria-label="${t('搜索项目或会话')}" placeholder="${t('搜索项目、模型或会话')}" value="${esc(state.query)}">${deviceFilter}<select id="model" aria-label="${t('筛选模型')}"><option value="">${t('全部模型')}</option>${d.allModels.map(m=>`<option value="${esc(m)}" ${state.model===m?'selected':''}>${esc(m)}</option>`).join('')}</select><button class="button" data-action="onlyUnpriced" aria-pressed="${state.unpriced}">${t('仅未计价')}</button></div>${filterChips()}<section class="panel">${state.view==='sessions'?sessionsTable():rowsTable(d.rows)}<div class="pagination"><span>${total?d.offset+1:0}–${Math.min(d.offset+d.limit,total)} / ${fmt.format(total)}</span><div class="row"><button class="button small" data-action="prev" ${!d.offset?'disabled':''}>${t('上一页')}</button><button class="button small" data-action="next" ${d.offset+d.limit>=total?'disabled':''}>${t('下一页')}</button></div></div></section>`;};
settings=function(){let html=baseSettings();const s=state.data.settings;
 const cycle=`<div class="field-pair"><div class="field"><label for="cycleMode">${t('账期模式')}</label><select name="cycleMode" id="cycleMode"><option value="manual" ${s.cycleMode==='manual'?'selected':''}>${t('手动日期')}</option><option value="monthly" ${s.cycleMode==='monthly'?'selected':''}>${t('每月自动续期')}</option></select></div><div class="field"><label for="billingDay">${t('每月续费日')}</label><input class="input" type="number" id="billingDay" name="billingDay" min="1" max="31" value="${s.billingDay}"><small>${t('短月份按最后一天续期。')}</small></div></div>`;
 html=html.replace(`<h2>${t('账期')}</h2>`,`<h2>${t('账期')}</h2>`+cycle).replace(t('额外额度 · USD'),t('本账期额外实付 · USD'));
 if(s.cycleMode==='monthly')html=html.replace('name="cycleStart"','name="cycleStart" readonly').replace('name="cycleEnd"','name="cycleEnd" readonly');
 const notifications=`<div class="notification-settings"><h3>${t('额度提醒')}</h3><label class="check-line"><input type="checkbox" name="notifications" ${s.notifications?'checked':''}>${t('剩余20%、5%及额度恢复时提醒')}</label><small class="caption">${t('仅使用新鲜账户数据，每个窗口不重复提醒。')}</small><div class="field-pair section-gap"><div class="field"><label for="quietStart">${t('免打扰开始（小时）')}</label><input class="input" name="quietStart" id="quietStart" type="number" min="0" max="23" value="${s.quietStart}"></div><div class="field"><label for="quietEnd">${t('免打扰结束（小时）')}</label><input class="input" name="quietEnd" id="quietEnd" type="number" min="0" max="23" value="${s.quietEnd}"></div></div><small class="caption">${t('起止相同为全天允许。后台提醒需保持应用运行。')}</small></div>`;
 return html.replace(`<div class="section-gap"><button type="button"`,notifications+`<div class="section-gap"><button type="button"`);
};
sources=function(){let html=baseSources(),remote=state.data.devices.filter(device=>!device.local).length;if(remote)html=html.replace(`<span>${t('未接入')}</span>`,`<span>${t('{n} 台已导入设备',{n:remote})}</span>`);for(const root of state.data.settings.roots){const status=state.data.scanner.roots?.find(r=>r.path===root)?.state;html=html.replace(`<div class="path-item">${esc(root)}</div>`,`<div class="path-item"><span>${esc(root)}</span><div class="row between"><small class="${status==='unavailable'?'warning':'muted'}">${t(status==='unavailable'?'目录不可用':status==='empty'?'未发现记录':'已添加')}</small><button class="text-button" data-remove-root="${esc(root)}">${t('停止监测')}</button></div></div>`);}return html;};
function focusView(){const d=state.data;return `<div class="focus-top"><strong>Subscription Lens</strong><div class="row"><button class="button small" data-action="pin" aria-pressed="${d.desktop.pinned}">${t(d.desktop.pinned?'取消置顶':'置顶')}</button><button class="button small" data-action="expand">${t('展开')}</button></div></div>${quotaCard(true)}<div class="focus-summary"><span>${t('本账期')}</span><strong>${money(pricedValue(d.cycle))}</strong><small>${t('API 等价成本')}</small></div><div class="focus-footer"><span>${t('最近观测')} ${clock(d.account.quota?.observedAt||d.quota?.observedAt)}</span><button class="text-button" data-action="refreshFocus">${t('刷新')}</button></div>`;}
render=function(){if(!state.data)return;document.body.classList.toggle('compact-mode',!!state.data.desktop?.compact);if(state.data.desktop?.compact){localizeShell();applyTheme();$('#main').innerHTML=focusView();return;}baseRender();};
navigate=function(page){state.project='';state.session='';state.day='';state.unpriced=false;baseNavigate(page);};
function openHealth(){const d=state.data,h=d.health;const names={model:'没有匹配的模型价格',tokens:'缺少 Token 分类',counter:'累计计数不一致',invalid:'Token 分类不一致',context:'缺少上下文档位价格',category:'缺少分类价格'};modal(t('数据状态'),`<div class="info-row"><span>${t('计价覆盖率')}</span><strong>${percentage(d.summary.pricedTokens,d.summary.tokens)}</strong></div>${h.reasons.map(r=>`<div class="info-row"><span>${t(names[r.reason]||'未计价')}</span><span>${fmt.format(r.count)}</span></div>`).join('')}<div class="info-row"><span>${t('读取或解析异常')}</span><span>${h.readErrors+h.parseErrors}</span></div><div class="info-row"><span>${t('历史记录不完整')}</span><span>${h.partial}</span></div><div class="info-row"><span>${t('价格快照日期')}</span><span>${esc(d.catalog.asOf)}</span></div><p>${t('覆盖率仅衡量已采集记录能否计价，不代表账户历史完整。')}</p><div class="row"><button class="button" data-action="healthRecords">${t('查看未计价')}</button><button class="button" data-action="healthPrices">${t('维护价格')}</button><button class="button" data-action="healthSources">${t('检查来源')}</button></div>`);}
async function openReport(){const d=await api('previewReport',filters());modal(t('分享摘要'),`<div class="report-preview"><div class="caption">Subscription Lens · ${t('本机 · Codex')}</div><h3>${datetime(d.from)} — ${datetime(new Date(d.to).getTime()-1)}</h3><div class="report-numbers"><div><span>Tokens</span><strong>${compact(d.tokens)}</strong></div><div><span>${t('API 等价成本')}</span><strong>${money(d.usd)}</strong></div></div><p>${t('计价覆盖率')} ${d.coverage===null?'—':percentage(d.coverage,1)} · ${t('价格')} ${esc(d.priceDate)}</p></div><p>${t('仅含汇总，不含账户、项目名、路径或会话标识。')}</p><button class="button primary" data-action="saveReport">${t('导出摘要')}</button>`);}
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const a=button.dataset.action;
 const handled=button.dataset.project!==undefined||button.dataset.session||button.dataset.day||button.dataset.view||button.dataset.clear||button.dataset.removeRoot||['compact','expand','pin','health','report','saveReport','healthRecords','healthPrices','healthSources','clearFilters','onlyUnpriced','refreshFocus'].includes(a);if(!handled)return;event.stopImmediatePropagation();
 if(button.dataset.project!==undefined){state.project=button.dataset.project;state.session='';state.day='';state.page='activity';state.view='sessions';state.offset=0;load();return;}
 if(button.dataset.session){state.session=button.dataset.session;state.view='records';state.offset=0;load();return;}
 if(button.dataset.day){state.day=button.dataset.day;state.page='activity';state.view='sessions';state.offset=0;load();return;}
 if(button.dataset.view){state.view=button.dataset.view;state.offset=0;load();return;}
 if(button.dataset.clear){state[button.dataset.clear]=button.dataset.clear==='unpriced'?false:'';state.offset=0;load();return;}
 if(button.dataset.removeRoot){const root=button.dataset.removeRoot;modal(t('停止监测'),`<p>${t('停止读取此目录，已采集历史和原始文件均保留。')}</p><button class="button primary" id="confirm-remove">${t('停止监测')}</button>`);$('#confirm-remove').onclick=()=>action(async()=>{await api('removeRoot',root);$('#dialog').close();});return;}
 if(a==='compact'||a==='expand'){action(()=>api('setCompact',a==='compact'));return;}
 if(a==='pin'){action(()=>api('setPinned',!state.data.desktop.pinned));return;}
 if(a==='health'){openHealth();return;}
 if(a==='report'){openReport().catch(e=>toast(e.message));return;}
 if(a==='saveReport'){action(()=>api('exportReport',filters()),()=>t('已保存'),button);return;}
 if(a==='healthPrices'||a==='healthSources'){ $('#dialog').close();navigate(a==='healthPrices'?'models':'sources');return;}
 if(a==='healthRecords'){$('#dialog').close();state.page='activity';state.view='records';state.unpriced=true;state.offset=0;load();return;}
 if(a==='onlyUnpriced'){state.unpriced=!state.unpriced;state.offset=0;load();return;}
 if(a==='clearFilters'){state.project='';state.session='';state.day='';state.unpriced=false;state.query='';state.model='';state.offset=0;load();return;}
 if(a==='refreshFocus'){action(()=>api('refresh'));}
},true);
document.addEventListener('change',event=>{if(event.target.id==='quota-window'){state.quotaKey=event.target.value;render();}if(event.target.id==='sort'){state.sort=event.target.value;state.offset=0;load();}if(event.target.id==='cycleMode'){for(const id of ['cycleStart','cycleEnd'])$('#'+id).readOnly=event.target.value==='monthly';}if(event.target.id==='period'){state.day='';state.session='';}},true);
document.addEventListener('submit',event=>{if(event.target.id!=='settings-form')return;event.preventDefault();event.stopImmediatePropagation();const f=new FormData(event.target);const settings={};for(const key of ['cycleStart','cycleEnd','cycleMode','language','theme'])settings[key]=f.get(key);for(const key of ['extra','billingDay','quietStart','quietEnd'])settings[key]=Number(f.get(key));settings.paid=f.get('paid')===''?null:Number(f.get('paid'));for(const key of ['tray','startup','notifications'])settings[key]=f.has(key);action(async()=>{const result=await api('saveSettings',settings);state.dirty=false;state.data.settings=result;return result;},()=>t('已保存'));},true);
document.addEventListener('keydown',event=>{if(event.ctrlKey&&event.shiftKey&&event.key.toLowerCase()==='m'){event.preventDefault();action(()=>api('setCompact',!state.data.desktop?.compact));}else if(event.ctrlKey&&event.key.toLowerCase()==='k'){event.preventDefault();if(state.data.desktop?.compact)return;state.page='activity';load().then(()=>$('#search')?.focus());}else if(event.key==='Escape'&&!$('#dialog').open&&state.data.desktop?.compact){action(()=>api('setCompact',false));}});
for(const type of ['click','keydown'])document.addEventListener(type,event=>{const target=event.target.closest('[data-chart-day]');if(!target||type==='keydown'&&!['Enter',' '].includes(event.key))return;event.preventDefault();state.day=target.dataset.chartDay;state.page='activity';state.view='sessions';state.offset=0;load();});
// Keep relative reset times current without taking focus from forms or searches.
setInterval(()=>{if(state.data&&!state.dirty&&!$('#dialog').open&&['overview'].includes(state.page)&&!['INPUT','SELECT'].includes(document.activeElement?.tagName))load();},30000);
