// Generated by scripts/build-locales.cjs. Edit src/locales.json.
window.LensLocales = {
  "总览": [
    "Overview",
    "Overzicht"
  ],
  "用量": [
    "Usage",
    "Gebruik"
  ],
  "价格": [
    "Pricing",
    "Tarieven"
  ],
  "连接": [
    "Connect",
    "Verbinden"
  ],
  "设置": [
    "Settings",
    "Instellingen"
  ],
  "关于": [
    "About",
    "Over"
  ],
  "文字大小": [
    "Text size",
    "Tekstgrootte"
  ],
  "标准": [
    "Standard",
    "Standaard"
  ],
  "较大": [
    "Large",
    "Groot"
  ],
  "特大": [
    "Extra large",
    "Extra groot"
  ],
  "增大界面文字和可点击目标，设置立即生效。": [
    "Increase interface text and click targets; changes apply immediately.",
    "Vergroot tekst en klikdoelen; wijzigingen gelden direct."
  ],
  "日均 {metric}": [
    "Daily average {metric}",
    "Dagelijks gemiddelde {metric}"
  ],
  "仅含活跃日": [
    "Active days only",
    "Alleen actieve dagen"
  ],
  "峰值日": [
    "Peak day",
    "Piekdag"
  ],
  "活跃天数": [
    "Active days",
    "Actieve dagen"
  ],
  "共 {n} 天": [
    "{n} days total",
    "{n} dagen totaal"
  ],
  "较前 7 天": [
    "vs previous 7 days",
    "vs vorige 7 dagen"
  ],
  "最近 7 天": [
    "Last 7 days",
    "Afgelopen 7 dagen"
  ],
  "点击柱状图查看当天明细": [
    "Select a bar to inspect that day",
    "Selecteer een balk voor die dag"
  ],
  "导航": [
    "Navigation",
    "Navigatie"
  ],
  "刷新": [
    "Refresh",
    "Vernieuwen"
  ],
  "关闭": [
    "Close",
    "Sluiten"
  ],
  "正在加载…": [
    "Loading…",
    "Laden…"
  ],
  "未找到 Codex": [
    "Codex not found",
    "Codex niet gevonden"
  ],
  "连接超时": [
    "Connection timed out",
    "Verbinding verlopen"
  ],
  "当前版本不支持": [
    "Not supported by this version",
    "Niet ondersteund door deze versie"
  ],
  "账户查询失败": [
    "Account query failed",
    "Accountgegevens ophalen mislukt"
  ],
  "无法连接": [
    "Unable to connect",
    "Kan geen verbinding maken"
  ],
  "连接已关闭": [
    "Connection closed",
    "Verbinding gesloten"
  ],
  "无法启动 Codex": [
    "Unable to start Codex",
    "Kan Codex niet starten"
  ],
  "未返回额度": [
    "No limits returned",
    "Geen limieten ontvangen"
  ],
  "登录未完成": [
    "Sign-in incomplete",
    "Aanmelden niet voltooid"
  ],
  "无法读取数据，请重新打开应用。": [
    "Unable to read data. Reopen the app.",
    "Kan gegevens niet lezen. Open de app opnieuw."
  ],
  "读取中 ": [
    "Reading ",
    "Bezig met lezen "
  ],
  "更新于 ": [
    "Updated ",
    "Bijgewerkt om "
  ],
  "未开始监测": [
    "Monitoring not started",
    "Monitoring niet gestart"
  ],
  "时间范围": [
    "Date range",
    "Periode"
  ],
  "今天": [
    "Today",
    "Vandaag"
  ],
  "本月": [
    "This month",
    "Deze maand"
  ],
  "本账期": [
    "Billing period",
    "Factuurperiode"
  ],
  "全部": [
    "All time",
    "Alles"
  ],
  "导出": [
    "Export",
    "Exporteren"
  ],
  "添加 Codex 使用记录": [
    "Add Codex usage records",
    "Codex-gebruiksgegevens toevoegen"
  ],
  "选择本机的 Codex 目录，开始统计。": [
    "Select your local Codex folder to start.",
    "Selecteer je lokale Codex-map om te beginnen."
  ],
  "首次连接会回读已有历史记录": [
    "Existing local history is imported on first connection.",
    "Bestaande lokale geschiedenis wordt bij de eerste verbinding ingelezen."
  ],
  "原始 Credits 与 API 等价成本分开统计": [
    "Native Credits and API-equivalent cost are tracked separately.",
    "Native Credits en API-equivalente kosten worden afzonderlijk bijgehouden."
  ],
  "Qoder Quest 使用本机上下文快照估算 Tokens；原始 Credits 仍需在 Qoder 内查看": [
    "Qoder Quest tokens use local context snapshots as an estimate; view native Credits in Qoder.",
    "Qoder Quest-tokens zijn een schatting uit lokale contextsnapshots; bekijk native Credits in Qoder."
  ],
  "平均成本 / 1M Tokens": [
    "Average cost / 1M Tokens",
    "Gemiddelde kosten / 1M tokens"
  ],
  "已计价 Tokens": [
    "Priced Tokens",
    "Geprijsde tokens"
  ],
  "开始监测": [
    "Start monitoring",
    "Monitoring starten"
  ],
  "选择目录": [
    "Choose folder",
    "Map kiezen"
  ],
  "暂无记录": [
    "No records",
    "Geen gegevens"
  ],
  "每日 API 等价成本": [
    "Daily API-equivalent cost",
    "Dagelijkse equivalente API-kosten"
  ],
  "每日 Token 用量": [
    "Daily token usage",
    "Dagelijks tokengebruik"
  ],
  "短期额度": [
    "Short-term limit",
    "Kortetermijnlimiet"
  ],
  "长期额度": [
    "Long-term limit",
    "Langetermijnlimiet"
  ],
  " 天": [
    " days",
    " dagen"
  ],
  " 小时": [
    " hours",
    " uur"
  ],
  "套餐额度": [
    "Plan limits",
    "Abonnementslimieten"
  ],
  "已连接": [
    "Connected",
    "Verbonden"
  ],
  "历史快照": [
    "Last snapshot",
    "Laatste momentopname"
  ],
  "未连接": [
    "Disconnected",
    "Niet verbonden"
  ],
  "管理": [
    "Manage",
    "Beheren"
  ],
  "% 剩余": [
    "% remaining",
    "% resterend"
  ],
  "待刷新": [
    "Refresh required",
    "Vernieuwen vereist"
  ],
  "已用 ": [
    "Used ",
    "Gebruikt "
  ],
  " 重置": [
    " reset",
    " hersteld"
  ],
  "未提供重置时间": [
    "Reset time unavailable",
    "Hersteltijd onbekend"
  ],
  "账户接口": [
    "Account API",
    "Account-API"
  ],
  "本机记录": [
    "Local records",
    "Lokale gegevens"
  ],
  "连接套餐账户，查看额度。": [
    "Connect your account to view limits.",
    "Verbind je account om limieten te bekijken."
  ],
  "连接账户": [
    "Connect account",
    "Account verbinden"
  ],
  "时间": [
    "Time",
    "Tijd"
  ],
  "项目 / 模型": [
    "Project / model",
    "Project / model"
  ],
  "缓存读取": [
    "Cache read",
    "Cache lezen"
  ],
  "API 等价成本": [
    "API-equivalent cost",
    "Equivalente API-kosten"
  ],
  "详情": [
    "Details",
    "Details"
  ],
  "未计价": [
    "Unpriced",
    "Niet berekend"
  ],
  "本机 · Codex": [
    "Local · Codex",
    "Lokaal · Codex"
  ],
  " 条记录 · ": [
    " records · ",
    " records · "
  ],
  " 个会话": [
    " sessions",
    " sessies"
  ],
  "缓存读取占比": [
    "Cache read share",
    "Aandeel cachelezingen"
  ],
  " 缓存 Tokens": [
    " cached tokens",
    " gecachte tokens"
  ],
  "计价覆盖率": [
    "Pricing coverage",
    "Tariefdekking"
  ],
  " 条未计价": [
    " unpriced records",
    " niet-berekende records"
  ],
  "用量趋势": [
    "Usage trend",
    "Gebruiksverloop"
  ],
  "成本": [
    "Cost",
    "Kosten"
  ],
  "模型用量": [
    "Usage by model",
    "Gebruik per model"
  ],
  "账期对比": [
    "Billing comparison",
    "Kostenvergelijking"
  ],
  "套餐实付": [
    "Plan payment",
    "Betaald abonnement"
  ],
  "额外额度": [
    "Extra credits",
    "Extra tegoed"
  ],
  "费用覆盖倍数": [
    "Cost coverage ratio",
    "Kostenverhouding"
  ],
  "最近记录": [
    "Recent records",
    "Recente gegevens"
  ],
  "查看全部": [
    "View all",
    "Alles bekijken"
  ],
  "价格 ": [
    "Prices ",
    "Tarieven "
  ],
  " · 按此价格快照估算，不含工具费用": [
    " · Snapshot estimate; excludes tool fees",
    " · Schatting op basis van deze tarieven; exclusief toolkosten"
  ],
  " · API 等价成本非实际账单": [
    " · API equivalent, not an actual bill",
    " · API-equivalent, geen werkelijke factuur"
  ],
  "已计价记录": [
    "Priced records",
    "Berekende records"
  ],
  "已采集记录": [
    "Collected records",
    "Verzamelde records"
  ],
  "填写账期实付后计算。": [
    "Enter your payment to calculate.",
    "Vul je betaling in om te berekenen."
  ],
  "选择“本账期”查看对比。": [
    "Select Billing period to compare.",
    "Selecteer Factuurperiode om te vergelijken."
  ],
  "API 等价成本减去套餐与额外额度实付。": [
    "API-equivalent cost minus plan and extra credit payments.",
    "Equivalente API-kosten min de betalingen voor abonnement en extra tegoed."
  ],
  "存在未计价记录": [
    "Some records are unpriced",
    "Sommige records zijn niet berekend"
  ],
  "已记录数据": [
    "Recorded usage",
    "Vastgelegd gebruik"
  ],
  "搜索项目或会话": [
    "Search projects or sessions",
    "Projecten of sessies zoeken"
  ],
  "搜索项目、模型或会话": [
    "Search projects, models or sessions",
    "Projecten, modellen of sessies zoeken"
  ],
  "筛选模型": [
    "Filter by model",
    "Filteren op model"
  ],
  "全部模型": [
    "All models",
    "Alle modellen"
  ],
  " 条记录": [
    " records",
    " records"
  ],
  "上一页": [
    "Previous",
    "Vorige"
  ],
  "下一页": [
    "Next",
    "Volgende"
  ],
  "导入": [
    "Import",
    "Importeren"
  ],
  "USD / 百万 Tokens": [
    "USD / million tokens",
    "USD / miljoen tokens"
  ],
  "Standard 基准 · ": [
    "Standard rates · ",
    "Standard-tarieven · "
  ],
  " · 按当前目录重估历史用量。": [
    " · Current catalog applied to historical usage.",
    " · Huidige tarieven toegepast op historisch gebruik."
  ],
  "官方价格 ↗": [
    "Official pricing ↗",
    "Officiële tarieven ↗"
  ],
  "模型": [
    "Model",
    "Model"
  ],
  "普通输入": [
    "Uncached input",
    "Invoer zonder cache"
  ],
  "缓存写入": [
    "Cache write",
    "Cache schrijven"
  ],
  "输出": [
    "Output",
    "Uitvoer"
  ],
  "长上下文阈值": [
    "Long-context threshold",
    "Drempel lange context"
  ],
  "恢复内置价格": [
    "Restore bundled prices",
    "Meegeleverde tarieven herstellen"
  ],
  "长上下文自动使用对应档位。缺少模型或分类价格的记录保留为未计价。价格导入会重新计算已有记录。": [
    "Long-context rates apply automatically. Missing rates remain unpriced. Importing prices recalculates existing records.",
    "Tarieven voor lange context worden automatisch toegepast. Ontbrekende tarieven blijven onberekend. Bij het importeren worden bestaande records opnieuw berekend."
  ],
  "等待登录": [
    "Awaiting sign-in",
    "Wachten op aanmelding"
  ],
  "连接中": [
    "Connecting",
    "Verbinden"
  ],
  "未登录": [
    "Signed out",
    "Niet aangemeld"
  ],
  "连接异常": [
    "Connection issue",
    "Verbindingsprobleem"
  ],
  "Codex 使用记录": [
    "Codex usage records",
    "Codex-gebruiksgegevens"
  ],
  "会话": [
    "Sessions",
    "Sessies"
  ],
  "用量记录": [
    "Usage records",
    "Gebruiksrecords"
  ],
  "文件": [
    "Files",
    "Bestanden"
  ],
  "添加目录": [
    "Add folder",
    "Map toevoegen"
  ],
  "重新扫描": [
    "Rescan",
    "Opnieuw scannen"
  ],
  "套餐账户": [
    "Subscription account",
    "Abonnementsaccount"
  ],
  "套餐": [
    "Plan",
    "Abonnement"
  ],
  "最近查询": [
    "Last checked",
    "Laatst gecontroleerd"
  ],
  "账户累计 Tokens": [
    "Account lifetime tokens",
    "Totaal aantal accounttokens"
  ],
  "选择 Codex 程序": [
    "Choose Codex executable",
    "Codex-programma kiezen"
  ],
  "数据范围": [
    "Data coverage",
    "Gegevensbereik"
  ],
  "本机明细": [
    "Local details",
    "Lokale details"
  ],
  "账户汇总": [
    "Account summary",
    "Accountoverzicht"
  ],
  "其他设备 / 云端任务明细": [
    "Other devices / cloud task details",
    "Andere apparaten / details van cloudtaken"
  ],
  "未接入": [
    "Not connected",
    "Niet aangesloten"
  ],
  "普通 ChatGPT 聊天": [
    "Regular ChatGPT chats",
    "Gewone ChatGPT-gesprekken"
  ],
  "不支持": [
    "Not supported",
    "Niet ondersteund"
  ],
  "已添加": [
    "Added",
    "Toegevoegd"
  ],
  "未添加": [
    "Not added",
    "Niet toegevoegd"
  ],
  " 个文件读取失败 · ": [
    " files unreadable · ",
    " onleesbare bestanden · "
  ],
  " 条记录未解析": [
    " records not parsed",
    " niet-verwerkte records"
  ],
  "查询失败": [
    "Query failed",
    "Ophalen mislukt"
  ],
  "使用 Codex 已登录的套餐账户。": [
    "Uses the subscription account signed in to Codex.",
    "Gebruikt het abonnementsaccount waarmee je bij Codex bent aangemeld."
  ],
  "取消登录": [
    "Cancel sign-in",
    "Aanmelden annuleren"
  ],
  "登录 ChatGPT": [
    "Sign in to ChatGPT",
    "Aanmelden bij ChatGPT"
  ],
  "刷新连接": [
    "Refresh connection",
    "Verbinding vernieuwen"
  ],
  "断开": [
    "Disconnect",
    "Verbinding verbreken"
  ],
  "官方接口返回范围": [
    "As returned by the official API",
    "Zoals opgegeven door de officiële API"
  ],
  "未获取": [
    "Not retrieved",
    "Niet opgehaald"
  ],
  "账期": [
    "Billing period",
    "Factuurperiode"
  ],
  "开始日期": [
    "Start date",
    "Begindatum"
  ],
  "结束日期（不含当天）": [
    "End date (exclusive)",
    "Einddatum (exclusief)"
  ],
  "套餐实付 · USD": [
    "Plan payment · USD",
    "Abonnementsbetaling · USD"
  ],
  "未填写": [
    "Not entered",
    "Niet ingevuld"
  ],
  "额外额度 · USD": [
    "Extra credits · USD",
    "Extra tegoed · USD"
  ],
  "时区：": [
    "Time zone: ",
    "Tijdzone: "
  ],
  "。非美元账单请先换算为 USD。": [
    ". Convert other currencies to USD first.",
    ". Reken andere valuta eerst om naar USD."
  ],
  "应用": [
    "Application",
    "Applicatie"
  ],
  "外观": [
    "Appearance",
    "Weergave"
  ],
  "关闭窗口后继续在托盘运行": [
    "Keep running in the system tray when closed",
    "Na sluiten actief blijven in het systeemvak"
  ],
  "登录 Windows 时启动": [
    "Start when signing in to Windows",
    "Starten bij aanmelden bij Windows"
  ],
  "导出诊断": [
    "Export diagnostics",
    "Diagnostiek exporteren"
  ],
  "保存": [
    "Save",
    "Opslaan"
  ],
  "跟随系统": [
    "System default",
    "Systeeminstelling"
  ],
  "浅色": [
    "Light",
    "Licht"
  ],
  "深色": [
    "Dark",
    "Donker"
  ],
  "没有匹配的模型价格": [
    "No matching model price",
    "Geen passend modeltarief"
  ],
  "累计计数不一致": [
    "Cumulative counts do not match",
    "Cumulatieve aantallen komen niet overeen"
  ],
  "缺少 Token 分类": [
    "Token breakdown missing",
    "Tokenverdeling ontbreekt"
  ],
  "Token 分类不一致": [
    "Inconsistent token breakdown",
    "Tokenverdeling klopt niet"
  ],
  "缺少上下文档位价格": [
    "Context tier price missing",
    "Tarief voor contextniveau ontbreekt"
  ],
  "缺少分类价格": [
    "Category price missing",
    "Categorietarief ontbreekt"
  ],
  "用量详情": [
    "Usage details",
    "Gebruiksdetails"
  ],
  "其中推理（已含在输出）": [
    "Reasoning (included in output)",
    "Redenering (in uitvoer inbegrepen)"
  ],
  "会话 ": [
    "Session ",
    "Sessie "
  ],
  "长上下文": [
    "Long context",
    "Lange context"
  ],
  "标准上下文": [
    "Standard context",
    "Standaardcontext"
  ],
  "记录状态：": [
    "Record status: ",
    "Recordstatus: "
  ],
  "已导出 ": [
    "Exported ",
    "Geëxporteerd: "
  ],
  "价格已更新": [
    "Prices updated",
    "Tarieven bijgewerkt"
  ],
  "扫描完成": [
    "Scan complete",
    "Scan voltooid"
  ],
  "已保存": [
    "Saved",
    "Opgeslagen"
  ],
  "余量": [
    "Subscription Lens",
    "Subscription Lens"
  ],
  "Codex 套餐用量监测。数据保存在本机，应用不保存聊天正文。": [
    "Codex subscription usage monitor. Data stays on this device; chat content is not stored.",
    "Monitor voor Codex-abonnementsgebruik. Gegevens blijven op dit apparaat; gespreksinhoud wordt niet opgeslagen."
  ],
  "API 等价成本按价格快照计算，不含工具费用。普通 ChatGPT 聊天和未接入设备不计入明细。": [
    "API-equivalent costs use a pricing snapshot and exclude tool fees. Regular ChatGPT chats and unconnected devices are not included.",
    "Equivalente API-kosten zijn gebaseerd op een tariefmomentopname, exclusief toolkosten. Gewone ChatGPT-gesprekken en niet-aangesloten apparaten zijn niet inbegrepen."
  ],
  "独立工具，与 OpenAI 无隶属关系。": [
    "Independent tool, not affiliated with OpenAI.",
    "Onafhankelijke tool, niet verbonden aan OpenAI."
  ],
  "价格来源": [
    "Pricing source",
    "Tariefbron"
  ],
  "语言": [
    "Language",
    "Taal"
  ],
  "打开余量": [
    "Open Subscription Lens",
    "Subscription Lens openen"
  ],
  "刷新用量": [
    "Refresh usage",
    "Gebruik vernieuwen"
  ],
  "退出": [
    "Quit",
    "Afsluiten"
  ],
  "无效窗口": [
    "Invalid window",
    "Ongeldig venster"
  ],
  "操作失败": [
    "Operation failed",
    "Bewerking mislukt"
  ],
  "选择 Codex 目录": [
    "Choose Codex folder",
    "Codex-map kiezen"
  ],
  "选择 codex.exe": [
    "Choose codex.exe",
    "codex.exe kiezen"
  ],
  "请选择 codex.exe": [
    "Select codex.exe",
    "Selecteer codex.exe"
  ],
  "请选择 Codex 程序": [
    "Select the Codex executable",
    "Selecteer het Codex-programma"
  ],
  "登录地址未通过校验": [
    "Sign-in URL could not be verified",
    "Aanmeldadres kon niet worden geverifieerd"
  ],
  "请稍后刷新": [
    "Wait before refreshing again",
    "Wacht even voordat je opnieuw vernieuwt"
  ],
  "正在读取，请稍后重试": [
    "Reading data. Try again shortly.",
    "Gegevens worden gelezen. Probeer het zo opnieuw."
  ],
  "导出用量": [
    "Export usage",
    "Gebruik exporteren"
  ],
  "导出价格目录": [
    "Export price catalog",
    "Tarieflijst exporteren"
  ],
  "导入价格目录": [
    "Import price catalog",
    "Tarieflijst importeren"
  ],
  "价格文件过大": [
    "Price file is too large",
    "Tariefbestand is te groot"
  ],
  "无法启动": [
    "Unable to start",
    "Kan niet starten"
  ],
  "应用数据无法打开。请检查数据目录权限。": [
    "Unable to open app data. Check data folder permissions.",
    "Kan appgegevens niet openen. Controleer de machtigingen van de gegevensmap."
  ],
  "日期无效": [
    "Invalid date",
    "Ongeldige datum"
  ],
  "结束日期必须晚于开始日期": [
    "End date must be after start date",
    "Einddatum moet na begindatum liggen"
  ],
  "实付金额无效": [
    "Invalid payment amount",
    "Ongeldig betalingsbedrag"
  ],
  "主题无效": [
    "Invalid theme",
    "Ongeldig thema"
  ],
  "语言无效": [
    "Invalid language",
    "Ongeldige taal"
  ],
  "请选择包含 sessions 或 archived_sessions 的 Codex 目录": [
    "Select a Codex folder containing sessions or archived_sessions",
    "Selecteer een Codex-map met sessions of archived_sessions"
  ],
  "价格必须是非负数": [
    "Prices must be non-negative",
    "Tarieven mogen niet negatief zijn"
  ],
  "价格精度超出支持范围": [
    "Price precision exceeds the supported limit",
    "Tariefprecisie overschrijdt de ondersteunde limiet"
  ],
  "价格文件格式错误": [
    "Invalid price file format",
    "Ongeldige bestandsindeling voor tarieven"
  ],
  "价格条目过多": [
    "Too many price entries",
    "Te veel tariefregels"
  ],
  "模型标识无效": [
    "Invalid model identifier",
    "Ongeldige modelidentificatie"
  ],
  "上下文阈值无效": [
    "Invalid context threshold",
    "Ongeldige contextdrempel"
  ],
  "缺少价格档位": [
    "Missing price tier",
    "Tariefniveau ontbreekt"
  ],
  "价格超出范围": [
    "Price is out of range",
    "Prijs valt buiten het bereik"
  ],
  "价格目录为空": [
    "Price catalog is empty",
    "Tarieflijst is leeg"
  ],
  "连接已取消": [
    "Connection cancelled",
    "Verbinding geannuleerd"
  ],
  "Codex 未连接": [
    "Codex is not connected",
    "Codex is niet verbonden"
  ],
  "查询超时": [
    "Query timed out",
    "Ophalen duurde te lang"
  ],
  "账户接口暂不可用": [
    "Account API temporarily unavailable",
    "Account-API tijdelijk niet beschikbaar"
  ],
  "Codex 连接已关闭": [
    "Codex connection closed",
    "Codex-verbinding gesloten"
  ],
  "未分类": [
    "Uncategorized",
    "Niet ingedeeld"
  ],
  "读取失败": [
    "Read failed",
    "Lezen mislukt"
  ],
  "目录不存在": [
    "Folder not found",
    "Map niet gevonden"
  ],
  "权限不足": [
    "Permission denied",
    "Geen toegang"
  ],
  "计数已重置": [
    "Counter reset",
    "Teller gereset"
  ],
  "历史记录不完整": [
    "Incomplete history",
    "Onvolledige geschiedenis"
  ],
  "计数存在歧义": [
    "Ambiguous counters",
    "Onduidelijke tellers"
  ],
  "{n} 条记录": [
    "{n} record || {n} records",
    "{n} record || {n} records"
  ],
  "{n} 个会话": [
    "{n} session || {n} sessions",
    "{n} sessie || {n} sessies"
  ],
  "{n} 条未计价": [
    "{n} unpriced record || {n} unpriced records",
    "{n} niet-berekend record || {n} niet-berekende records"
  ],
  "{n} 个文件读取失败": [
    "{n} unreadable file || {n} unreadable files",
    "{n} onleesbaar bestand || {n} onleesbare bestanden"
  ],
  "{n} 条记录未解析": [
    "{n} unparsed record || {n} unparsed records",
    "{n} niet-verwerkt record || {n} niet-verwerkte records"
  ],
  "已导出 {n} 条记录": [
    "Exported {n} record || Exported {n} records",
    "{n} record geëxporteerd || {n} records geëxporteerd"
  ],
  "重置于 {time}": [
    "Resets {time}",
    "Herstel op {time}"
  ],
  "选择额度窗口": [
    "Quota window",
    "Limietvenster"
  ],
  "剩余额度": [
    "Remaining",
    "Resterend"
  ],
  "距重置": [
    "Until reset",
    "Tot herstel"
  ],
  "按最近 {n} 分钟推算": [
    "Based on the last {n} minutes",
    "Op basis van de afgelopen {n} minuten"
  ],
  "按本额度窗口 {n} 分钟观测推算": [
    "Based on {n} minutes observed in this quota window",
    "Op basis van {n} minuten metingen in dit quotavenster"
  ],
  "预计剩余": [
    "Estimated remaining time",
    "Geschatte resterende tijd"
  ],
  "持续当前使用速度的估算，实际可用时间会变化。": [
    "Assumes the current usage pace continues. Actual availability will vary.",
    "Gaat uit van aanhoudend gebruik in hetzelfde tempo. Werkelijke beschikbaarheid kan afwijken."
  ],
  "至少15分钟的有效变化后提供估算。": [
    "Estimates need at least 15 minutes of measurable usage.",
    "Schattingen vereisen minstens 15 minuten meetbaar gebruik."
  ],
  "最近观测": [
    "Last observed",
    "Laatst gemeten"
  ],
  "已计价的 API 等价成本": [
    "Priced API-equivalent usage",
    "Berekend API-equivalent gebruik"
  ],
  "填写套餐实付": [
    "Enter plan payment",
    "Abonnementsbetaling invullen"
  ],
  "API 等价成本 / 账期实付": [
    "API equivalent / period payment",
    "API-equivalent / periodebetaling"
  ],
  "部分记录未计价，当前金额为已计价部分。": [
    "Some records are unpriced; this is the priced portion.",
    "Sommige records zijn niet berekend; dit is het berekende deel."
  ],
  "仅基于已采集记录，不代表实际退款或现金节省。": [
    "Based on collected records; not a refund or cash savings.",
    "Gebaseerd op verzamelde records; geen terugbetaling of geldbesparing."
  ],
  "数据需要核对": [
    "Review data",
    "Gegevens controleren"
  ],
  "数据状态": [
    "Data health",
    "Gegevensstatus"
  ],
  "用在哪些项目": [
    "Usage by project",
    "Gebruik per project"
  ],
  "分享摘要": [
    "Share summary",
    "Overzicht delen"
  ],
  "专注窗口": [
    "Compact view",
    "Compact venster"
  ],
  "较前一等长时段": [
    "vs. preceding equal period",
    "t.o.v. vorige even lange periode"
  ],
  "点击日期查看任务": [
    "Select a date to see sessions",
    "Selecteer een datum voor sessies"
  ],
  "清除筛选": [
    "Clear filters",
    "Filters wissen"
  ],
  "会话 / 项目": [
    "Session / project",
    "Sessie / project"
  ],
  "最近活动": [
    "Last activity",
    "Laatste activiteit"
  ],
  "子任务": [
    "Subagent",
    "Subagent"
  ],
  "查看记录": [
    "View records",
    "Records bekijken"
  ],
  "排序": [
    "Sort",
    "Sorteren"
  ],
  "成本最高": [
    "Highest cost",
    "Hoogste kosten"
  ],
  "仅未计价": [
    "Unpriced only",
    "Alleen onberekend"
  ],
  "账期模式": [
    "Billing mode",
    "Factuurmodus"
  ],
  "手动日期": [
    "Manual dates",
    "Handmatige datums"
  ],
  "每月自动续期": [
    "Monthly renewal",
    "Maandelijkse verlenging"
  ],
  "每月续费日": [
    "Monthly renewal day",
    "Maandelijkse verlengdag"
  ],
  "短月份按最后一天续期。": [
    "Uses the last day in shorter months.",
    "Gebruikt de laatste dag in kortere maanden."
  ],
  "额度提醒": [
    "Quota alerts",
    "Limietmeldingen"
  ],
  "剩余20%、5%及额度恢复时提醒": [
    "Notify at 20%, 5% remaining and recovery",
    "Melden bij 20%, 5% resterend en herstel"
  ],
  "仅使用新鲜账户数据，每个窗口不重复提醒。": [
    "Fresh account data only; no repeat alerts within a window.",
    "Alleen actuele accountgegevens; geen herhaalde melding binnen een venster."
  ],
  "免打扰开始（小时）": [
    "Quiet hours start (hour)",
    "Stille uren vanaf (uur)"
  ],
  "免打扰结束（小时）": [
    "Quiet hours end (hour)",
    "Stille uren tot (uur)"
  ],
  "起止相同为全天允许。后台提醒需保持应用运行。": [
    "Same start and end allows all hours. Keep the app running for alerts.",
    "Gelijke tijden staan alle uren toe. Laat de app actief voor meldingen."
  ],
  "停止监测": [
    "Stop monitoring",
    "Monitoring stoppen"
  ],
  "展开": [
    "Expand",
    "Uitklappen"
  ],
  "读取或解析异常": [
    "Read or parse errors",
    "Lees- of verwerkingsfouten"
  ],
  "价格快照日期": [
    "Price snapshot date",
    "Datum tariefmomentopname"
  ],
  "覆盖率仅衡量已采集记录能否计价，不代表账户历史完整。": [
    "Coverage measures pricing of collected records, not completeness of account history.",
    "Dekking betreft tarieven van verzamelde records, niet de volledigheid van de accountgeschiedenis."
  ],
  "查看未计价": [
    "Review unpriced records",
    "Onberekende records bekijken"
  ],
  "维护价格": [
    "Manage prices",
    "Tarieven beheren"
  ],
  "检查来源": [
    "Check sources",
    "Bronnen controleren"
  ],
  "仅含汇总，不含账户、项目名、路径或会话标识。": [
    "Totals only. No account, project names, paths or session IDs.",
    "Alleen totalen. Geen account, projectnamen, paden of sessie-ID’s."
  ],
  "导出摘要": [
    "Export summary",
    "Overzicht exporteren"
  ],
  "停止读取此目录，已采集历史和原始文件均保留。": [
    "Stop reading this folder. Collected history and original files are kept.",
    "Deze map niet meer lezen. Verzamelde geschiedenis en originele bestanden blijven behouden."
  ],
  "额度已恢复": [
    "Quota restored",
    "Limiet hersteld"
  ],
  "用量摘要": [
    "Usage summary",
    "Gebruiksoverzicht"
  ],
  "已筛选": [
    "Filtered",
    "Gefilterd"
  ],
  "额度需要刷新": [
    "Quota needs refreshing",
    "Limiet moet worden vernieuwd"
  ],
  "等待重置确认": [
    "Awaiting reset confirmation",
    "Wachten op bevestiging van herstel"
  ],
  "额度已用尽": [
    "Quota exhausted",
    "Limiet bereikt"
  ],
  "正在积累额度观测": [
    "Learning your usage pace",
    "Gebruikstempo wordt gemeten"
  ],
  "按近期速度可能提前用尽": [
    "May run out before reset at this pace",
    "Kan bij dit tempo vóór herstel opraken"
  ],
  "按近期速度可用至重置": [
    "On pace to last until reset",
    "Bij dit tempo voldoende tot herstel"
  ],
  "暂不能确定是否够用": [
    "Not enough certainty to predict",
    "Nog te onzeker om te voorspellen"
  ],
  "已超过实付": [
    "Above payment",
    "Boven de betaling"
  ],
  "距覆盖实付还差": [
    "Remaining to match payment",
    "Nog nodig om betaling te evenaren"
  ],
  "目录不可用": [
    "Folder unavailable",
    "Map niet beschikbaar"
  ],
  "未发现记录": [
    "No records found",
    "Geen records gevonden"
  ],
  "取消置顶": [
    "Unpin",
    "Losmaken"
  ],
  "置顶": [
    "Pin",
    "Vastzetten"
  ],
  "账期模式无效": [
    "Invalid billing mode",
    "Ongeldige factuurmodus"
  ],
  "设置数值无效": [
    "Invalid setting value",
    "Ongeldige instellingswaarde"
  ],
  "本账期额外实付 · USD": [
    "Extra payment this period · USD",
    "Extra betaling deze periode · USD"
  ],
  "尚无可计价记录": [
    "No priced records yet",
    "Nog geen berekende records"
  ],
  "Codex 套餐": [
    "Codex subscription",
    "Codex-abonnement"
  ],
  "多供应商": [
    "Providers",
    "Aanbieders"
  ],
  "API 用量文件": [
    "API usage file",
    "API-gebruiksbestand"
  ],
  "统计来源": [
    "Data source",
    "Gegevensbron"
  ],
  "未添加来源": [
    "No sources added",
    "Geen bronnen toegevoegd"
  ],
  "供应商": [
    "Provider",
    "Aanbieder"
  ],
  "全部供应商": [
    "All providers",
    "Alle aanbieders"
  ],
  "管理来源": [
    "Manage sources",
    "Bronnen beheren"
  ],
  "平台兼容性": [
    "Platform compatibility",
    "Platformcompatibiliteit"
  ],
  "仅在有明确本地数据来源时标记为已支持": [
    "A platform is supported only when a clear local data source exists",
    "Een platform wordt alleen ondersteund bij een duidelijke lokale gegevensbron"
  ],
  "证据分级": [
    "Evidence levels",
    "Bewijsniveaus"
  ],
  "已支持": [
    "Supported",
    "Ondersteund"
  ],
  "部分支持": [
    "Partial",
    "Gedeeltelijk"
  ],
  "候选": [
    "Candidate",
    "Kandidaat"
  ],
  "Qoder Quest 本机上下文快照与 stream JSON；Credits 单独保留": [
    "Qoder Quest local context snapshots and stream JSON; Credits remain separate",
    "Lokale contextsnapshots en stream-JSON van Qoder Quest; Credits blijven afzonderlijk"
  ],
  "本机项目 JSONL 用量；只读解析，不读取配置密钥": [
    "Local project JSONL usage; read-only parsing without configuration keys",
    "Lokale JSONL-gebruiksgegevens; alleen-lezen parsing zonder configuratiesleutels"
  ],
  "通过 CC Switch、兼容网关或 JSONL 导入；暂无独立客户端连接器": [
    "Import through CC Switch, a compatible gateway or JSONL; no dedicated client connector yet",
    "Importeer via CC Switch, een compatibele gateway of JSONL; nog geen eigen clientconnector"
  ],
  "等待稳定的本地导出或日志格式；可先使用 JSONL 导入": [
    "Waiting for a stable local export or log format; JSONL import is available meanwhile",
    "Wachten op een stabiel lokaal export- of logformaat; JSONL-import is voorlopig beschikbaar"
  ],
  "等待稳定的本地导出或日志格式；暂不读取凭据或网页数据": [
    "Waiting for a stable local export or log format; credentials and web data are not read",
    "Wachten op een stabiel lokaal export- of logformaat; inloggegevens en webgegevens worden niet gelezen"
  ],
  "添加使用记录": [
    "Add usage records",
    "Gebruiksgegevens toevoegen"
  ],
  "连接 CC Switch 数据库、Claude Code、Gemini CLI 或 API 用量文件。": [
    "Connect CC Switch, Claude Code, Gemini CLI or an API usage file.",
    "Verbind CC Switch, Claude Code, Gemini CLI of een API-gebruiksbestand."
  ],
  "添加监控来源": [
    "Add source",
    "Bron toevoegen"
  ],
  "读取来源失败": [
    "Source could not be read",
    "Bron kon niet worden gelezen"
  ],
  "已暂停": [
    "Paused",
    "Gepauzeerd"
  ],
  "正在读取": [
    "Reading",
    "Bezig met lezen"
  ],
  "最近同步": [
    "Last synced",
    "Laatst gesynchroniseerd"
  ],
  "未解析记录": [
    "Unparsed records",
    "Niet-verwerkte records"
  ],
  "按所选来源统计，避免重复汇总。": [
    "Totals use the selected source only.",
    "Totalen gebruiken alleen de geselecteerde bron."
  ],
  "发现 {n} 条跨来源重叠记录": [
    "Found {n} records that overlap another source",
    "{n} records overlappen met een andere bron"
  ],
  "已匹配其他来源": [
    "Matched in another source",
    "Komt overeen met een andere bron"
  ],
  "可能与其他来源重复": [
    "May overlap another source",
    "Mogelijk overlap met een andere bron"
  ],
  "重叠来源": [
    "Overlapping sources",
    "Overlappende bronnen"
  ],
  "重叠筛选": [
    "Overlap filter",
    "Overlapfilter"
  ],
  "全部记录": [
    "All records",
    "Alle records"
  ],
  "精确重叠": [
    "Exact overlaps",
    "Exacte overlap"
  ],
  "可能重叠": [
    "Possible overlaps",
    "Mogelijke overlap"
  ],
  "预估剩余时间": [
    "Estimated remaining time",
    "Geschatte resterende tijd"
  ],
  "本额度窗口累计": [
    "Full quota window",
    "Volledig quotavenster"
  ],
  "最近24小时": [
    "Recent 24 hours",
    "Afgelopen 24 uur"
  ],
  "最近2小时": [
    "Recent 2 hours",
    "Afgelopen 2 uur"
  ],
  "当前模式暂无足够观测。": [
    "There are not enough observations for this mode yet.",
    "Er zijn nog niet genoeg metingen voor deze modus."
  ],
  "按 {n} 分钟有效观测推算": [
    "Based on {n} minutes of valid observations",
    "Gebaseerd op {n} minuten geldige metingen"
  ],
  "全部来源": [
    "All sources",
    "Alle bronnen"
  ],
  "精确去重": [
    "Exact duplicates removed",
    "Exacte duplicaten verwijderd"
  ],
  "精确重复记录只计一次，可能重叠仍保留提示。": [
    "Exact duplicate records are counted once; possible overlaps remain flagged.",
    "Exacte dubbele records tellen eenmaal mee; mogelijke overlap blijft gemarkeerd."
  ],
  "高级：手动添加其他来源": [
    "Advanced: add another source manually",
    "Geavanceerd: een andere bron handmatig toevoegen"
  ],
  "适用于自定义目录、网关导出或 API JSONL 文件。": [
    "For custom folders, gateway exports or API JSONL files.",
    "Voor aangepaste mappen, gateway-exports of API-JSONL-bestanden."
  ],
  "请求数": [
    "Requests",
    "Verzoeken"
  ],
  "记录中的估算费用": [
    "Estimated cost",
    "Geschatte kosten"
  ],
  "不是实际账单": [
    "Not an invoice",
    "Geen factuur"
  ],
  "来源报告费用": [
    "Source-reported cost",
    "Door bron gemelde kosten"
  ],
  "仅统计明确标记的费用": [
    "Explicitly reported amounts only",
    "Alleen expliciet gemelde bedragen"
  ],
  "成功率": [
    "Success rate",
    "Succespercentage"
  ],
  "失败": [
    "failed",
    "mislukt"
  ],
  "有状态记录": [
    "records with status",
    "records met status"
  ],
  "延迟 P95": [
    "Latency P95",
    "Latentie P95"
  ],
  "仅含有延迟的记录": [
    "Records with latency only",
    "Alleen records met latentie"
  ],
  "每日用量": [
    "Daily usage",
    "Dagelijks gebruik"
  ],
  "首 Token 延迟 P50": [
    "Time to first token P50",
    "Tijd tot eerste token P50"
  ],
  "费用": [
    "Cost",
    "Kosten"
  ],
  "状态": [
    "Status",
    "Status"
  ],
  "延迟": [
    "Latency",
    "Latentie"
  ],
  "来源报告": [
    "Source-reported",
    "Door bron gemeld"
  ],
  "估算": [
    "Estimated",
    "Geschat"
  ],
  "搜索供应商或模型": [
    "Search providers or models",
    "Zoek aanbieders of modellen"
  ],
  "仅失败请求": [
    "Failed requests only",
    "Alleen mislukte verzoeken"
  ],
  "多供应商使用记录": [
    "Provider usage records",
    "Gebruiksgegevens van aanbieders"
  ],
  "本机只读": [
    "Local · read-only",
    "Lokaal · alleen-lezen"
  ],
  "只采集用量与性能字段，不读取密钥配置，不保存聊天正文。": [
    "Stores usage and performance metadata. No key configuration or chat content is stored.",
    "Slaat gebruiks- en prestatiegegevens op. Geen sleutelconfiguratie of chatinhoud."
  ],
  "来源类型": [
    "Source type",
    "Brontype"
  ],
  "CC Switch 选择数据库文件；Claude Code 选择 projects，Gemini CLI 选择 tmp。": [
    "Select the CC Switch database, Claude Code projects folder or Gemini CLI tmp folder.",
    "Selecteer de CC Switch-database, de projects-map van Claude Code of de tmp-map van Gemini CLI."
  ],
  "暂停采集": [
    "Pause collection",
    "Verzamelen pauzeren"
  ],
  "继续采集": [
    "Resume collection",
    "Verzamelen hervatten"
  ],
  "添加计价规则": [
    "Add pricing rule",
    "Prijsregel toevoegen"
  ],
  "自定义规则仅为未计价记录估算费用，不覆盖来源报告的金额。": [
    "Custom rules estimate unpriced records without replacing source amounts.",
    "Eigen regels schatten ongeprijsde records zonder bronbedragen te vervangen."
  ],
  "百万 Tokens": [
    "million tokens",
    "miljoen tokens"
  ],
  "首 Token 延迟": [
    "Time to first token",
    "Tijd tot eerste token"
  ],
  "计价模型": [
    "Pricing model",
    "Prijsmodel"
  ],
  "供应商用量": [
    "Usage by provider",
    "Gebruik per aanbieder"
  ],
  "分布摘要": [
    "Distribution summary",
    "Samenvatting van verdeling"
  ],
  "点击供应商查看模型用量": [
    "Select a provider to inspect model usage",
    "Selecteer een aanbieder om modelgebruik te bekijken"
  ],
  "点击模型查看记录": [
    "Select a model to inspect its records",
    "Selecteer een model om de records te bekijken"
  ],
  "统计指标": [
    "Metric",
    "Maatstaf"
  ],
  "已计价费用": [
    "Priced cost",
    "Berekende kosten"
  ],
  "估算与来源报告费用合计": [
    "Estimated and source-reported costs combined",
    "Geschatte en door de bron gemelde kosten samen"
  ],
  "不支持的来源": [
    "Unsupported source",
    "Niet-ondersteunde bron"
  ],
  "来源类型不匹配": [
    "Source type does not match",
    "Brontype komt niet overeen"
  ],
  "来源已添加": [
    "Source already added",
    "Bron is al toegevoegd"
  ],
  "来源不存在": [
    "Source does not exist",
    "Bron bestaat niet"
  ],
  "预算金额无效": [
    "Invalid budget amount",
    "Ongeldig budgetbedrag"
  ],
  "不支持的用量数据库": [
    "Unsupported usage database",
    "Niet-ondersteunde gebruiksdatabase"
  ],
  "来源暂不可用": [
    "Source is temporarily unavailable",
    "Bron is tijdelijk niet beschikbaar"
  ],
  "用量分布": [
    "Usage distribution",
    "Gebruiksverdeling"
  ],
  "套餐与账期": [
    "Plan and billing cycle",
    "Abonnement en factuurperiode"
  ],
  "项目": [
    "Projects",
    "Projecten"
  ],
  "连接本机编码工具或用量文件。": [
    "Connect a local coding tool or usage file.",
    "Koppel een lokale codeertool of gebruiksbestand."
  ],
  "选择工具的数据目录；应用只读取明确的用量记录。": [
    "Choose the tool's data folder; the app reads only explicit usage records.",
    "Kies de gegevensmap van de tool; de app leest alleen expliciete gebruiksrecords."
  ],
  "性能": [
    "Performance",
    "Prestaties"
  ],
  "已发现的工具": [
    "Detected tools",
    "Gedetecteerde tools"
  ],
  "从常用本机目录自动发现": [
    "Found automatically in standard local folders",
    "Automatisch gevonden in standaard lokale mappen"
  ],
  "连接全部": [
    "Connect all",
    "Alles verbinden"
  ],
  "已全部连接": [
    "All connected",
    "Alles verbonden"
  ],
  "未在常用目录发现工具，可手动选择。": [
    "No tools found in standard folders. Select a location manually.",
    "Geen tools gevonden in standaardmappen. Kies handmatig een locatie."
  ],
  "手动添加": [
    "Add manually",
    "Handmatig toevoegen"
  ],
  "已连接 {n} 个来源": [
    "Connected {n} sources",
    "{n} bronnen verbonden"
  ],
  "模型组合": [
    "Model mix",
    "Modelmix"
  ],
  "当前占比": [
    "Current share",
    "Huidig aandeel"
  ],
  "建议占比": [
    "Suggested share",
    "Aanbevolen aandeel"
  ],
  "增加": [
    "Increase",
    "Verhogen"
  ],
  "降低": [
    "Reduce",
    "Verlagen"
  ],
  "保持": [
    "Keep",
    "Behouden"
  ],
  "正在学习你的模型习惯和额度速度": [
    "Learning your model habits and quota pace",
    "Je modelgewoonten en quotatempo worden geleerd"
  ],
  "学习中": [
    "Learning",
    "Bezig met leren"
  ],
  "基于本地历史用量": [
    "Based on local usage history",
    "Gebaseerd op lokale gebruiksgeschiedenis"
  ],
  "等待实时额度速度": [
    "Waiting for live quota pace",
    "Wachten op live quotatempo"
  ],
  "建议基于已有本地历史；连接并观测额度后会校准。": [
    "This baseline uses existing local history; connect and observe quota pace to calibrate it.",
    "Deze basis gebruikt bestaande lokale geschiedenis; verbind en observeer het quotatempo voor kalibratie."
  ],
  "至少使用两个可计价模型，并积累15分钟额度变化后生成建议。": [
    "Use at least two priced models and collect 15 minutes of quota movement to get a recommendation.",
    "Gebruik minstens twee geprijsde modellen en verzamel 15 minuten quotawijzigingen voor een advies."
  ],
  "降低高强度模型占比": [
    "Reduce high-intensity model usage",
    "Gebruik van intensieve modellen verlagen"
  ],
  "可提高高强度模型占比": [
    "High-intensity model usage can increase",
    "Gebruik van intensieve modellen kan omhoog"
  ],
  "维持当前模型组合": [
    "Keep the current model mix",
    "Huidige modelmix behouden"
  ],
  "当前速度接近目标": [
    "Current pace is near target",
    "Huidig tempo ligt dicht bij doel"
  ],
  "中等可信度": [
    "Medium confidence",
    "Gemiddelde betrouwbaarheid"
  ],
  "低可信度": [
    "Low confidence",
    "Lage betrouwbaarheid"
  ],
  "以当前额度窗口重置时间为目标": [
    "Targets the current quota reset",
    "Gericht op de huidige quotareset"
  ],
  "依据近14天模型用量、API 等价强度和近期额度速度；下个窗口会继续校准。": [
    "Based on 14-day model usage, API-equivalent intensity, and recent quota pace; calibration continues next window.",
    "Gebaseerd op 14 dagen modelgebruik, API-equivalente intensiteit en recent quotatempo; kalibratie gaat volgend venster door."
  ],
  "模型建议": [
    "Model mix",
    "Modelmix"
  ],
  "目标速度提高 {n}%": [
    "Raise target pace by {n}%",
    "Doeltempo {n}% verhogen"
  ],
  "目标速度降低 {n}%": [
    "Lower target pace by {n}%",
    "Doeltempo {n}% verlagen"
  ],
  "API 等价强度": [
    "API-equivalent intensity",
    "API-equivalente intensiteit"
  ],
  "依据近14天模型用量、": [
    "Based on 14-day model usage, ",
    "Gebaseerd op 14 dagen modelgebruik, "
  ],
  "依据本额度窗口的模型用量、": [
    "Based on model usage in this quota window, ",
    "Gebaseerd op modelgebruik in dit quotavenster, "
  ],
  "和本窗口平均额度速度；下个窗口会继续校准。": [
    " and the average quota pace in this window; calibration continues next window.",
    " en het gemiddelde quotatempo in dit venster; kalibratie gaat volgend venster door."
  ],
  "和近期额度速度；下个窗口会继续校准。": [
    " and recent quota pace; calibration continues next window.",
    " en recent quotatempo; kalibratie gaat volgend venster door."
  ],
  "模型处理的文本单位，包括输入和输出；缓存分类只计算一次。": [
    "Units of text processed by a model, including input and output. Cache categories are counted once.",
    "Teksteenheden die een model verwerkt, inclusief invoer en uitvoer. Cachecategorieën worden één keer geteld."
  ],
  "按保存的 API 价格快照换算当前收集用量所得的金额，并非套餐账单或保证节省的费用。": [
    "What the collected usage would cost at the saved API price snapshot. It is not your subscription bill or guaranteed savings.",
    "Wat het verzamelde gebruik volgens de opgeslagen API-prijzen zou kosten. Dit is geen abonnementsfactuur of gegarandeerde besparing."
  ],
  "从先前提示缓存中重复使用的输入 Tokens；它们仍属于输入，不会重复计入总量。": [
    "Input tokens reused from a previous prompt cache. They remain part of input and are not added twice.",
    "Invoertokens die uit een eerdere promptcache worden hergebruikt. Ze blijven onderdeel van de invoer en worden niet dubbel geteld."
  ],
  "供应商写入可重复使用的提示缓存的输入 Tokens。": [
    "Input tokens written to a reusable prompt cache by the provider.",
    "Invoertokens die door de aanbieder naar een herbruikbare promptcache worden geschreven."
  ],
  "输入 Tokens 中从缓存读取的比例；比例较高通常会降低 API 等价成本。": [
    "The share of input tokens served from cache. A higher share can reduce API-equivalent cost.",
    "Het aandeel invoertokens dat uit de cache komt. Een hoger aandeel kan de API-equivalente kosten verlagen."
  ],
  "已收集 Tokens 中匹配完整价格规则的比例，不代表账户全部活动都已被收集。": [
    "The share of collected tokens that match a complete price rule. It does not measure whether all account activity was collected.",
    "Het aandeel verzamelde tokens met een volledige prijsregel. Dit zegt niet of alle accountactiviteit is verzameld."
  ],
  "模型或 Token 分类没有完整价格规则的记录；其 Tokens 仍计入用量。": [
    "A record whose model or token categories do not have a complete price rule. Its tokens remain included.",
    "Een record zonder volledige prijsregel voor het model of de tokencategorieën. De tokens blijven wel meetellen."
  ],
  "单次请求超过此规模后，模型会采用长上下文价格档位。": [
    "The request size above which a model uses its long-context price tier.",
    "De aanvraaggrootte waarboven een model het tarief voor lange context gebruikt."
  ],
  "Codex 返回的 ChatGPT/Codex 账户级容量，由不同客户端共享，并非单台设备的 Token 总量。": [
    "Account-level ChatGPT/Codex capacity returned by Codex. It is shared across clients and is not a per-device token total.",
    "Capaciteit op ChatGPT/Codex-accountniveau die Codex teruggeeft. Deze wordt gedeeld door clients en is geen tokentotaal per apparaat."
  ],
  "根据本机使用习惯、API 等价强度和账户额度速度，为近期模型建议的使用比例。": [
    "A suggested share for recently used models, based on local habits, API-equivalent intensity and account quota pace.",
    "Een voorgestelde verdeling voor recent gebruikte modellen, gebaseerd op lokale gewoonten, API-equivalente intensiteit en het tempo van het accountquotum."
  ],
  "表示可用价格和额度历史对建议的支持程度，并非结果保证。": [
    "Shows how much usable pricing and quota history supports the recommendation. It is not a guarantee.",
    "Geeft aan hoeveel bruikbare prijs- en quotageschiedenis het advies ondersteunt. Het is geen garantie."
  ],
  "根据 Token 数量和价格规则在本地计算的金额，并非供应商报告。": [
    "A locally calculated amount from token counts and a price rule. It is not reported by the provider.",
    "Een lokaal berekend bedrag op basis van tokens en een prijsregel. Het is niet door de aanbieder gerapporteerd."
  ],
  "导入来源记录中自带的金额；Subscription Lens 不将其验证为账单。": [
    "An amount included in the imported source record. Subscription Lens does not verify it as an invoice.",
    "Een bedrag uit het geïmporteerde bronrecord. Subscription Lens verifieert dit niet als factuur."
  ],
  "成功请求数除以包含状态码的记录数；没有状态的记录不参与计算。": [
    "Successful requests divided by records that include a status code. Records without status are excluded.",
    "Geslaagde aanvragen gedeeld door records met een statuscode. Records zonder status tellen niet mee."
  ],
  "95% 的已测请求在此时间内完成；没有延迟数据的记录不参与计算。": [
    "Ninety-five percent of measured requests completed within this time. Records without latency are excluded.",
    "Vijfennegentig procent van de gemeten aanvragen werd binnen deze tijd voltooid. Records zonder vertraging tellen niet mee."
  ],
  "所选本地来源的估算金额和来源报告金额，统一以 USD 显示，并非账户账单。": [
    "Estimated and source-reported USD amounts for the selected local source. It is not an account invoice.",
    "Geschatte en door de bron gemelde USD-bedragen voor de gekozen lokale bron. Dit is geen accountfactuur."
  ],
  "来源提供的请求耗时；缺失值不会按零计算。": [
    "Elapsed request time when the source provides it. Missing values are not treated as zero.",
    "Verstreken aanvraagtijd wanneer de bron die levert. Ontbrekende waarden worden niet als nul behandeld."
  ],
  "收到第一个输出 Token 所需时间的中位数，仅统计提供该指标的记录。": [
    "The median time until the first output token. Only records that provide this measurement are included.",
    "De mediane tijd tot het eerste uitvoertoken. Alleen records met deze meting tellen mee."
  ],
  "Codex 返回的账户级活动汇总；当前协议不按设备拆分。": [
    "An account-level activity summary returned by Codex. The current protocol does not split it by device.",
    "Een activiteitsoverzicht op accountniveau dat Codex teruggeeft. Het huidige protocol splitst dit niet per apparaat."
  ],
  "从这台电脑上已配置的 Codex 目录读取的会话，不会自动包含其他设备。": [
    "Sessions read from Codex folders configured on this computer. Other devices are not included automatically.",
    "Sessies uit Codex-mappen die op deze computer zijn ingesteld. Andere apparaten worden niet automatisch meegenomen."
  ],
  "登录账户返回的聚合活动信息，明细程度低于本机会话记录。": [
    "Aggregate activity returned for the signed-in account. It has less detail than local session records.",
    "Geaggregeerde activiteit voor het aangemelde account. Deze bevat minder detail dan lokale sessierecords."
  ],
  "除非单独导入数据，否则无法获取其他电脑或云端任务的详细记录。": [
    "Detailed records from other computers or cloud tasks are unavailable unless their data is imported separately.",
    "Gedetailleerde records van andere computers of cloudtaken zijn niet beschikbaar tenzij hun gegevens apart worden geïmporteerd."
  ],
  "本账期实际支付的套餐金额，由用户以 USD 手动填写。": [
    "The amount you actually paid for the subscription during this billing period, entered manually in USD.",
    "Het bedrag dat je in deze factuurperiode werkelijk voor het abonnement betaalde, handmatig ingevoerd in USD."
  ],
  "本账期额外支付或购买的额度，由用户以 USD 手动填写。": [
    "Additional payment or purchased credits for the current billing period, entered manually in USD.",
    "Extra betaling of gekochte credits voor de huidige factuurperiode, handmatig ingevoerd in USD."
  ],
  "API 等价成本除以套餐实付金额；它用于比较，并非现金节省。": [
    "API-equivalent cost divided by the subscription payment. It is a comparison, not cash savings.",
    "API-equivalente kosten gedeeld door de abonnementsbetaling. Dit is een vergelijking, geen contante besparing."
  ],
  "各模型每 Token 对应的已观测 API 等价成本，仅用作相对信号，并非官方套餐额度权重。": [
    "Observed API-equivalent cost per token for each model. It is used only as a relative signal and is not an official subscription quota weight.",
    "De waargenomen API-equivalente kosten per token voor elk model. Dit is alleen een relatief signaal en geen officieel quotagewicht."
  ],
  "设备": [
    "Devices",
    "Apparaten"
  ],
  "导出设备数据": [
    "Export device data",
    "Apparaatgegevens exporteren"
  ],
  "导入设备数据": [
    "Import device data",
    "Apparaatgegevens importeren"
  ],
  "账户额度由所有客户端共享；设备页只统计已采集或已导入的本机 Codex 记录。": [
    "Account quota is shared by every client. Devices only counts collected or imported local Codex records.",
    "Accountquota wordt door alle clients gedeeld. Apparaten telt alleen verzamelde of geïmporteerde lokale Codex-records."
  ],
  "设备名称": [
    "Device name",
    "Apparaatnaam"
  ],
  "重命名": [
    "Rename",
    "Naam wijzigen"
  ],
  "重命名设备": [
    "Rename device",
    "Apparaat hernoemen"
  ],
  "本机": [
    "This device",
    "Dit apparaat"
  ],
  "最后同步": [
    "Last sync",
    "Laatst gesynchroniseerd"
  ],
  "筛选设备": [
    "Filter device",
    "Apparaat filteren"
  ],
  "全部设备": [
    "All devices",
    "Alle apparaten"
  ],
  "数据包仅包含匿名会话标识、时间、模型和 Token 分类；不包含聊天正文、项目路径或登录凭据。": [
    "The package contains only anonymous session IDs, time, model and token categories; it excludes chat content, project paths and sign-in credentials.",
    "Het pakket bevat alleen anonieme sessie-ID's, tijd, model en tokencategorieën; chatinhoud, projectpaden en inloggegevens zijn uitgesloten."
  ],
  "已导入 {n} 条记录": [
    "Imported {n} records",
    "{n} records geïmporteerd"
  ],
  "查看用量": [
    "View usage",
    "Gebruik bekijken"
  ],
  "{n} 台已导入设备": [
    "{n} imported devices",
    "{n} geïmporteerde apparaten"
  ],
  "查看模型建议": [
    "View model recommendations",
    "Modeladvies bekijken"
  ],
  "每日趋势": [
    "Daily trend",
    "Dagelijkse trend"
  ],
  "活动热力图": [
    "Activity heatmap",
    "Activiteitskaart"
  ],
  "点击有颜色的日期查看当天明细": [
    "Select a colored day to inspect that day",
    "Selecteer een gekleurde dag voor die dag"
  ],
  "低": [
    "Low",
    "Laag"
  ],
  "高": [
    "High",
    "Hoog"
  ],
  "累计趋势": [
    "Cumulative trend",
    "Cumulatieve trend"
  ],
  "模型分布": [
    "Model distribution",
    "Modelverdeling"
  ],
  "当前周期": [
    "Current period",
    "Huidige periode"
  ],
  "最近 30 天": [
    "Last 30 days",
    "Laatste 30 dagen"
  ],
  "最近 90 天": [
    "Last 90 days",
    "Laatste 90 dagen"
  ],
  "全部历史": [
    "All history",
    "Volledige geschiedenis"
  ],
  "按模型查看所选时间范围": [
    "Models in selected range",
    "Modellen in geselecteerde periode"
  ],
  "点击图表查看当天明细": [
    "Select a chart point to inspect that day",
    "Selecteer een punt voor die dag"
  ],
  "查看会话": [
    "View sessions",
    "Sessies bekijken"
  ],
  "记录": [
    "Records",
    "Records"
  ],
  "导入当前 Codex 配置": [
    "Import current Codex config",
    "Huidige Codex-config importeren"
  ],
  "导入 Codex 配置": [
    "Import Codex config",
    "Codex-config importeren"
  ],
  "导入配置": [
    "Import config",
    "Configuratie importeren"
  ],
  "读取当前 Codex 的模型、地址和协议，不会启动代理。": [
    "Reads the current Codex models, endpoint, and protocol. It does not start the proxy.",
    "Leest de huidige Codex-modellen, endpoint en protocol. Start de proxy niet."
  ],
  "本机代理": [
    "Local proxy",
    "Lokale proxy"
  ],
  "代理正在运行，Codex 请求可经本机转发。": [
    "The proxy is running. Codex requests can be routed through this computer.",
    "De proxy is actief. Codex-verzoeken kunnen via deze computer worden doorgestuurd."
  ],
  "仅在使用第三方供应商、应用内密钥或需要请求记录时启动。": [
    "Start it only when using a third-party provider, an app-managed key, or request logging.",
    "Start dit alleen voor een externe provider, een door de app beheerde sleutel of verzoekregistratie."
  ],
  "启动代理": [
    "Start proxy",
    "Proxy starten"
  ],
  "管理 Codex 的模型路由": [
    "Manage Codex model routing",
    "Codex-modelroutering beheren"
  ],
  "路由": [
    "Routing",
    "Routering"
  ],
  "一键切换": [
    "Switch instantly",
    "Direct wisselen"
  ],
  "接入代理": [
    "Connect proxy",
    "Proxy koppelen"
  ],
  "首次接入代理需要重启 Codex，之后可直接切换。": [
    "The first proxy connection requires restarting Codex; later switches are instant.",
    "De eerste proxykoppeling vereist een herstart van Codex; daarna wissel je direct."
  ],
  "已切换供应商，无需重启 Codex。": [
    "Provider switched without restarting Codex.",
    "Provider gewisseld zonder Codex opnieuw te starten."
  ],
  "请先启动本机代理": [
    "Start the local proxy first.",
    "Start eerst de lokale proxy."
  ],
  "本机代理运行中": [
    "Local proxy running",
    "Lokale proxy actief"
  ],
  "本机代理未运行": [
    "Local proxy stopped",
    "Lokale proxy gestopt"
  ],
  "停止代理": [
    "Stop proxy",
    "Proxy stoppen"
  ],
  "启动本机代理": [
    "Start local proxy",
    "Lokale proxy starten"
  ],
  "代理仅监听本机，可记录路由请求并支持热切换。": [
    "The proxy listens on this computer only, records routed requests, and supports hot switching.",
    "De proxy luistert alleen lokaal, registreert gerouteerde verzoeken en ondersteunt snel wisselen."
  ],
  "当前": [
    "Current",
    "Actief"
  ],
  "凭据已配置": [
    "Credential configured",
    "Inloggegeven geconfigureerd"
  ],
  "等待环境变量": [
    "Waiting for environment variable",
    "Wachten op omgevingsvariabele"
  ],
  "启用": [
    "Enable",
    "Inschakelen"
  ],
  "测试连接": [
    "Test connection",
    "Verbinding testen"
  ],
  "连接成功 · {n} 个模型": [
    "Connected · {n} models",
    "Verbonden · {n} modellen"
  ],
  "使用 Codex 登录态，无需 OPENAI_API_KEY": [
    "Using your Codex login session; OPENAI_API_KEY is not required",
    "Codex-inlogsessie gebruikt; OPENAI_API_KEY is niet vereist"
  ],
  "Codex 登录态": [
    "Codex login session",
    "Codex-inlogsessie"
  ],
  "连接失败": [
    "Connection failed",
    "Verbinding mislukt"
  ],
  "已保存并连接成功 · {n} 个模型": [
    "Saved and connected · {n} models",
    "Opgeslagen en verbonden · {n} modellen"
  ],
  "已保存，连接测试失败": [
    "Saved, but the connection test failed",
    "Opgeslagen, maar de verbindingstest is mislukt"
  ],
  "编辑": [
    "Edit",
    "Bewerken"
  ],
  "保存并测试": [
    "Save and test",
    "Opslaan en testen"
  ],
  "清空": [
    "Clear",
    "Wissen"
  ],
  "供应商模板": [
    "Provider template",
    "Leverancierssjabloon"
  ],
  "OpenAI Codex": [
    "OpenAI Codex",
    "OpenAI Codex"
  ],
  "自定义": [
    "Custom",
    "Aangepast"
  ],
  "选择模板后自动填充，必要时再修改。": [
    "Choose a template to fill the form, then adjust only what you need.",
    "Kies een sjabloon om het formulier in te vullen en pas alleen aan wat nodig is."
  ],
  "推荐使用模板，地址和协议会自动匹配。": [
    "Templates are recommended because the endpoint and protocol are matched automatically.",
    "Sjablonen worden aanbevolen omdat endpoint en protocol automatisch worden afgestemd."
  ],
  "模板已填充，可直接保存或按需修改。": [
    "The template is ready. Save it as-is or adjust the fields.",
    "Het sjabloon is ingevuld. Sla het direct op of pas de velden aan."
  ],
  "填写供应商文档提供的地址、模型和环境变量。": [
    "Enter the endpoint, model and environment variable from the provider documentation.",
    "Vul endpoint, model en omgevingsvariabele uit de leveranciersdocumentatie in."
  ],
  "高级设置": [
    "Advanced settings",
    "Geavanceerde instellingen"
  ],
  "上游协议": [
    "Upstream protocol",
    "Upstream-protocol"
  ],
  "只填写变量名，API Key 保留在系统环境变量中。": [
    "Enter only the variable name; the API key stays in your system environment.",
    "Vul alleen de variabelenaam in; de API-sleutel blijft in de systeemomgeving."
  ],
  "API Key": [
    "API key",
    "API-sleutel"
  ],
  "留空则保留已保存密钥": [
    "Leave blank to keep the saved key",
    "Laat leeg om de opgeslagen sleutel te behouden"
  ],
  "密钥使用 Windows 加密存储，不会写入明文配置。": [
    "The key is encrypted with Windows secure storage and is never written to plain-text configuration.",
    "De sleutel wordt versleuteld opgeslagen met Windows-beveiliging en nooit als leesbare configuratie opgeslagen."
  ],
  "应用内密钥已保存": [
    "App key saved",
    "App-sleutel opgeslagen"
  ],
  "系统加密存储不可用": [
    "Windows secure storage is unavailable",
    "Windows-beveiligde opslag is niet beschikbaar"
  ],
  "Responses API 可直接由 Codex 使用。": [
    "Responses API can be used directly by Codex.",
    "De Responses API kan rechtstreeks door Codex worden gebruikt."
  ],
  "Chat Completions 需要兼容层，当前版本不能直接启用。": [
    "Chat Completions requires a compatibility layer and cannot be enabled directly in this version.",
    "Chat Completions vereist een compatibiliteitslaag en kan in deze versie niet rechtstreeks worden ingeschakeld."
  ],
  "地址格式正确": [
    "Endpoint format looks valid",
    "Endpointindeling ziet er geldig uit"
  ],
  "请输入有效的 HTTPS 地址": [
    "Enter a valid HTTPS endpoint",
    "Voer een geldig HTTPS-endpoint in"
  ],
  "已切换 Codex 供应商": [
    "Codex provider switched",
    "Codex-leverancier gewisseld"
  ],
  "已导入当前配置": [
    "Current config imported",
    "Huidige configuratie geïmporteerd"
  ],
  "本机代理已启动": [
    "Local proxy started",
    "Lokale proxy gestart"
  ],
  "本机代理已停止": [
    "Local proxy stopped",
    "Lokale proxy gestopt"
  ],
  "供应商已删除": [
    "Provider deleted",
    "Leverancier verwijderd"
  ],
  "添加自定义供应商": [
    "Add custom provider",
    "Aangepaste leverancier toevoegen"
  ],
  "仅保存配置，不保存 API Key": [
    "Configuration only; API keys are not stored.",
    "Alleen configuratie; API-sleutels worden niet opgeslagen."
  ],
  "名称": [
    "Name",
    "Naam"
  ],
  "API 地址": [
    "API endpoint",
    "API-eindpunt"
  ],
  "环境变量": [
    "Environment variable",
    "Omgevingsvariabele"
  ],
  "Chat Completions（需代理或兼容层）": [
    "Chat Completions (proxy or compatibility layer required)",
    "Chat Completions (proxy of compatibiliteitslaag vereist)"
  ],
  "保存供应商": [
    "Save provider",
    "Leverancier opslaan"
  ],
  "Responses API": [
    "Responses API",
    "Responses API"
  ],
  "Codex 的模型路由": [
    "Codex model routing",
    "Codex-modelroutering"
  ],
  "Codex Router": [
    "Codex Router",
    "Codex Router"
  ],
  "供应商地址无效": [
    "Provider endpoint is invalid",
    "Leverancier-eindpunt is ongeldig"
  ],
  "模型名称无效": [
    "Model name is invalid",
    "Modelnaam is ongeldig"
  ],
  "供应商名称无效": [
    "Provider name is invalid",
    "Leveranciersnaam is ongeldig"
  ],
  "供应商标识无效": [
    "Provider ID is invalid",
    "Leveranciers-ID is ongeldig"
  ],
  "环境变量名称无效": [
    "Environment variable name is invalid",
    "Naam van omgevingsvariabele is ongeldig"
  ],
  "供应商不存在": [
    "Provider not found",
    "Leverancier niet gevonden"
  ],
  "不能删除内置供应商": [
    "Built-in provider cannot be deleted",
    "Ingebouwde leverancier kan niet worden verwijderd"
  ],
  "不能删除当前供应商": [
    "The active provider cannot be deleted",
    "De actieve leverancier kan niet worden verwijderd"
  ],
  "不能导入当前配置": [
    "Cannot import current config",
    "Huidige configuratie kan niet worden geïmporteerd"
  ],
  "切换前自动备份 Codex 配置": [
    "Back up Codex config before switching",
    "Maak een back-up van de Codex-configuratie vóór het wisselen"
  ],
  "删除": [
    "Delete",
    "Verwijderen"
  ],
  "供应商已保存": [
    "Provider saved",
    "Leverancier opgeslagen"
  ],
  "请求过大": [
    "Request is too large",
    "Verzoek is te groot"
  ],
  "Chat Completions 供应商需要兼容适配，当前版本不能直接启用": [
    "Chat Completions providers need a compatibility adapter and cannot be enabled directly yet.",
    "Chat Completions-leveranciers vereisen een compatibiliteitsadapter en kunnen nog niet rechtstreeks worden ingeschakeld."
  ],
  "经代理启用": [
    "Enable via proxy",
    "Via proxy inschakelen"
  ],
  "Codex 供应商": [
    "Codex providers",
    "Codex-leveranciers"
  ],
  "切换失败": [
    "Switch failed",
    "Wisselen mislukt"
  ],
  "请先添加供应商": [
    "Add a provider first",
    "Voeg eerst een leverancier toe"
  ],
  "已切换供应商；请重启 Codex 以载入新配置。": [
    "Provider switched. Restart Codex to load the new configuration.",
    "Leverancier gewisseld. Start Codex opnieuw om de nieuwe configuratie te laden."
  ],
  "密钥会在启用时写入 Codex 的供应商配置；应用内保存仍使用 Windows 加密。": [
    "The key is written to Codex's provider configuration when enabled; the app copy remains protected by Windows encryption.",
    "De sleutel wordt bij inschakelen in de providerconfiguratie van Codex geschreven; de kopie in de app blijft met Windows-versleuteling beschermd."
  ],
  "添加供应商": [
    "Add provider",
    "Leverancier toevoegen"
  ],
  "返回路由": [
    "Back to routing",
    "Terug naar routering"
  ],
  "编辑供应商": [
    "Edit provider",
    "Leverancier bewerken"
  ],
  "为 Codex 添加一个 Responses API 供应商。": [
    "Add a Responses API provider for Codex.",
    "Voeg een Responses API-leverancier toe voor Codex."
  ],
  "填写兼容 OpenAI Responses 格式的服务端地址。": [
    "Enter an endpoint compatible with the OpenAI Responses format.",
    "Vul een endpoint in dat compatibel is met de OpenAI Responses-indeling."
  ],
  "默认模型": [
    "Default model",
    "Standaardmodel"
  ],
  "获取模型列表": [
    "Fetch models",
    "Modellen ophalen"
  ],
  "Codex 会以此模型发起默认请求；可随时改动。": [
    "Codex uses this model for its default request; you can change it any time.",
    "Codex gebruikt dit model voor standaardverzoeken; je kunt het altijd wijzigen."
  ],
  "可用模型": [
    "Available models",
    "Beschikbare modellen"
  ],
  "从服务端读取的模型；选择后会填入默认模型。": [
    "Models read from the endpoint; selecting one fills the default model.",
    "Modellen die van het endpoint zijn gelezen; kies er een om het standaardmodel in te vullen."
  ],
  "取消": [
    "Cancel",
    "Annuleren"
  ],
  "已获取 {n} 个模型": [
    "Fetched {n} models",
    "{n} modellen opgehaald"
  ],
  "模型映射": [
    "Model mapping",
    "Modeltoewijzing"
  ],
  "Codex 前台模型": [
    "Codex UI model",
    "Codex-interfacemodel"
  ],
  "供应商上游模型": [
    "Provider upstream model",
    "Upstreammodel van provider"
  ],
  "添加映射": [
    "Add mapping",
    "Toewijzing toevoegen"
  ],
  "移除映射": [
    "Remove mapping",
    "Toewijzing verwijderen"
  ],
  "Codex 前台只显示兼容模型名；每一行会在本机路由中转成对应的供应商模型。": [
    "The Codex UI only shows compatible model names; each row is routed locally to its provider model.",
    "De Codex-interface toont alleen compatibele modelnamen; elke rij wordt lokaal naar het providermodel geleid."
  ],
  "旧会话保持或切换到左侧的兼容模型名；无需选择 deepseek、qwen 等第三方 slug。": [
    "Keep or switch an existing chat to the compatible model name on the left; never select a third-party slug such as deepseek or qwen.",
    "Behoud of kies in een bestaand gesprek de compatibele modelnaam links; kies geen externe slug zoals deepseek of qwen."
  ],
  "启用后写入 Codex 模型菜单；重启 Codex 后可选择。": [
    "Written to the Codex model menu when enabled; restart Codex to select them.",
    "Wordt bij inschakelen naar het Codex-modelmenu geschreven; herstart Codex om ze te kiezen."
  ],
  "已恢复 OpenAI Official；重启 Codex 后，旧对话请选择官方模型或新建对话。": [
    "OpenAI Official restored. Restart Codex, then choose an official model in existing conversations or start a new one.",
    "OpenAI Official is hersteld. Herstart Codex en kies daarna een officieel model in bestaande gesprekken, of start een nieuw gesprek."
  ],
  "连接凭据": [
    "Connection credential",
    "Verbindingsreferentie"
  ],
  "先保存 API Key，再获取模型或测试连接。": [
    "Save an API key before fetching models or testing the connection.",
    "Sla eerst een API-sleutel op voordat je modellen ophaalt of de verbinding test."
  ],
  "已加密保存": [
    "Encrypted and saved",
    "Versleuteld opgeslagen"
  ],
  "环境变量可用": [
    "Environment variable available",
    "Omgevingsvariabele beschikbaar"
  ],
  "需要 API Key": [
    "API key required",
    "API-sleutel vereist"
  ],
  "输入新密钥以替换已保存密钥": [
    "Enter a new key to replace the saved key",
    "Voer een nieuwe sleutel in om de opgeslagen sleutel te vervangen"
  ],
  "输入 API Key": [
    "Enter API key",
    "Voer API-sleutel in"
  ],
  "已保存密钥会直接用于获取模型和测试；输入新密钥后保存即可替换。": [
    "The saved key is used directly for fetching and testing; save a new key to replace it.",
    "De opgeslagen sleutel wordt direct gebruikt voor ophalen en testen; sla een nieuwe sleutel op om hem te vervangen."
  ],
  "密钥在保存后使用 Windows 加密存储，之后不会回填到输入框。": [
    "After saving, the key is encrypted with Windows protection and is never filled back into this field.",
    "Na opslaan wordt de sleutel met Windows-beveiliging versleuteld en nooit terug in dit veld ingevuld."
  ],
  "使用 Codex 登录态": [
    "Use Codex sign-in",
    "Gebruik Codex-aanmelding"
  ],
  "官方供应商不需要单独的 API Key。": [
    "The official provider does not need a separate API key.",
    "De officiële provider heeft geen aparte API-sleutel nodig."
  ],
  "为 Codex 添加一个模型路由供应商。": [
    "Add a model-routing provider for Codex.",
    "Voeg een modelrouteringsprovider toe voor Codex."
  ],
  "上游模型": [
    "Upstream model",
    "Upstreammodel"
  ],
  "路由会将兼容的 Codex 模型别名映射到此模型。": [
    "The route maps a compatible Codex model alias to this model.",
    "De route vertaalt een compatibel Codex-modelalias naar dit model."
  ],
  "请先输入或保存 API Key。": [
    "Enter or save an API key first.",
    "Voer eerst een API-sleutel in of sla deze op."
  ],
  "从服务端读取的模型会显示在下方，选择后会填入此字段。": [
    "Models read from the endpoint appear below; selecting one fills this field.",
    "Modellen van het endpoint verschijnen hieronder; kies er een om dit veld in te vullen."
  ],
  "连接设置": [
    "Connection settings",
    "Verbindingsinstellingen"
  ],
  "通常不需要修改；模板会提供推荐值。": [
    "Usually no changes are needed; the template provides recommended values.",
    "Meestal zijn geen wijzigingen nodig; het sjabloon geeft aanbevolen waarden."
  ],
  "Chat Completions（由嵌入式路由转换）": [
    "Chat Completions (converted by the embedded router)",
    "Chat Completions (omgezet door de ingebedde router)"
  ],
  "环境变量名称": [
    "Environment variable name",
    "Naam van omgevingsvariabele"
  ],
  "仅在未保存应用内密钥时作为备用凭据。": [
    "Used as a fallback credential only when no in-app key is saved.",
    "Alleen gebruikt als reserve-referentie wanneer geen sleutel in de app is opgeslagen."
  ],
  "路由已启用；请重新打开 Codex 后发送下一条消息。": [
    "Routing is enabled. Reopen Codex, then send the next message.",
    "Routing is ingeschakeld. Open Codex opnieuw en stuur daarna het volgende bericht."
  ],
  "路由已切换；下一条消息会使用所选上游模型。": [
    "Routing switched. The next message uses the selected upstream model.",
    "Routing is gewisseld. Het volgende bericht gebruikt het gekozen upstreammodel."
  ],
  "旧会话如何使用路由": [
    "How existing chats use routing",
    "Hoe bestaande chats routing gebruiken"
  ],
  "保留 Codex 前台的兼容 GPT 模型；路由会在请求发送前替换为所选上游模型。": [
    "Keep a compatible GPT model in the Codex UI; routing replaces it with the selected upstream model before the request is sent.",
    "Behoud een compatibel GPT-model in de Codex-interface; routing vervangt dit vóór verzending door het gekozen upstreammodel."
  ],
  "官方": [
    "Official",
    "Officieel"
  ],
  "国内官方": [
    "Domestic official",
    "Binnenlands officieel"
  ],
  "聚合服务": [
    "Aggregator",
    "Aggregator"
  ],
  "第三方服务": [
    "Third-party service",
    "Externe dienst"
  ],
  "其他": [
    "Other",
    "Overig"
  ],
  "搜索供应商模板": [
    "Search provider presets",
    "Zoek providerpresets"
  ],
  "按名称排序": [
    "Sort by name",
    "Sorteren op naam"
  ],
  "没有匹配的供应商模板": [
    "No matching provider presets",
    "Geen overeenkomende providerpresets"
  ],
  "选择预设后可继续调整下方字段。": [
    "Choose a preset, then adjust the fields below if needed.",
    "Kies een preset en pas daarna zo nodig de velden hieronder aan."
  ],
  "先输入或保存 API Key，再获取模型目录。": [
    "Enter or save an API key before fetching the model catalog.",
    "Voer een API-sleutel in of sla hem op voordat je de modelcatalogus ophaalt."
  ],
  "按 CC Switch 的 Codex 供应商结构添加端点、凭据和模型目录。": [
    "Add an endpoint, credentials and model catalog using the CC Switch Codex provider structure.",
    "Voeg een endpoint, referenties en modelcatalogus toe volgens de Codex-providerstructuur van CC Switch."
  ],
  "保存到 Codex config.toml 的默认 model；留空时使用模型目录第一行。": [
    "The default model saved to Codex config.toml; the first model in the catalog is used when this is empty.",
    "Het standaardmodel dat in Codex config.toml wordt opgeslagen; het eerste catalogusmodel wordt gebruikt als dit leeg is."
  ],
  "模型目录会按 CC Switch 格式保存，编辑时保留显示名、上下文窗口和推理档位。": [
    "The model catalog is saved in the CC Switch format, preserving display names, context windows and reasoning levels when edited.",
    "De modelcatalogus wordt opgeslagen in het CC Switch-formaat; weergavenamen, contextvensters en redeneerniveaus blijven behouden bij bewerken."
  ],
  "上游格式": [
    "Upstream format",
    "Upstreamindeling"
  ],
  "Responses（原生）": [
    "Responses (native)",
    "Responses (native)"
  ],
  "这些字段对应 CC Switch 的 Codex 配置。": [
    "These fields correspond to the CC Switch Codex configuration.",
    "Deze velden komen overeen met de Codex-configuratie van CC Switch."
  ],
  "模型目录": [
    "Model catalog",
    "Modelcatalogus"
  ],
  "这是 Codex 看到的模型列表。每行保存显示名、真实模型 ID、上下文窗口和供应商接受的推理档位。": [
    "This is the model list shown to Codex. Each row saves a display name, real model ID, context window and reasoning levels accepted by the provider.",
    "Dit is de modellijst die Codex ziet. Elke rij bewaart een weergavenaam, echte model-ID, contextvenster en redeneerniveaus die de provider accepteert."
  ],
  "添加模型": [
    "Add model",
    "Model toevoegen"
  ],
  "显示名称 / 真实模型 ID": [
    "Display name / real model ID",
    "Weergavenaam / echte model-ID"
  ],
  "上下文 / 推理档位": [
    "Context / reasoning levels",
    "Context / redeneerniveaus"
  ],
  "显示名称": [
    "Display name",
    "Weergavenaam"
  ],
  "真实模型 ID": [
    "Real model ID",
    "Echte model-ID"
  ],
  "上下文窗口": [
    "Context window",
    "Contextvenster"
  ],
  "推理档位：low, high, max": [
    "Reasoning levels: low, high, max",
    "Redeneerniveaus: low, high, max"
  ],
  "移除模型": [
    "Remove model",
    "Model verwijderen"
  ],
  "还没有模型目录，点击添加模型或获取模型列表。": [
    "No model catalog yet. Add a model or fetch the model list.",
    "Nog geen modelcatalogus. Voeg een model toe of haal de modellijst op."
  ],
  "保存后会写入 CC Switch 兼容的 modelCatalog.models；不会把 API Key 写入配置文件。": [
    "Saving writes CC Switch-compatible modelCatalog.models; the API key is never written to the config file.",
    "Opslaan schrijft modelCatalog.models in CC Switch-formaat; de API-sleutel wordt nooit in het configuratiebestand gezet."
  ],
  "高级选项": [
    "Advanced options",
    "Geavanceerde opties"
  ]
};
