'use strict';
Object.assign(state,{multi:false,connection:'',provider:'',failed:false,overlap:''});
const beforeMonitorFilters=filters,beforeMonitorOverview=overview,beforeMonitorActivity=activity,beforeMonitorSources=sources,beforeMonitorModels=models,beforeMonitorHead=head;
filters=()=>({...beforeMonitorFilters(),connection:state.connection,provider:state.provider,failed:state.failed,overlap:state.overlap});
head=function(...args){const html=beforeMonitorHead(...args);return html+`<div class="monitor-switch segments"><button data-monitor-view="codex" class="${state.multi?'':'active'}">${t('Codex 套餐')}</button><button data-monitor-view="multi" class="${state.multi?'active':''}">${t('多供应商')}</button></div>`;};
const sourceName=s=>({'cc-switch':'CC Switch',claude:'Claude Code',gemini:'Gemini CLI',qwen:'Qwen Code',kimi:'Kimi Code',codebuddy:'CodeBuddy Code',qoder:'Qoder','usage-jsonl':t('API 用量文件')})[s.kind]||s.kind;
const headerBeforeMonitor=updateHeader;
updateHeader=function(){if(!state.multi)return headerBeforeMonitor();const m=state.data?.monitor,s=m?.sources.find(s=>s.id===m.source);$('#update-state').textContent=!s?t('未添加来源'):!s.enabled?t('已暂停'):s.state==='error'?t('读取来源失败'):s.state==='reading'?t('正在读取'):s.at?t('更新于 ')+clock(s.at):t('已添加');};
function monitorFilters(){const m=state.data.monitor;return `<div class="filters monitor-filters"><select id="monitor-source" aria-label="${t('统计来源')}">${m.sources.length?m.sources.map(s=>`<option value="${s.id}" ${s.id===m.source?'selected':''}>${esc(sourceName(s))} · ${esc(s.path.split(/[\\/]/).at(-1))}</option>`).join(''):`<option>${t('未添加来源')}</option>`}</select><select id="monitor-provider" aria-label="${t('供应商')}"><option value="">${t('全部供应商')}</option>${m.providers.map(p=>`<option ${p===state.provider?'selected':''} value="${esc(p)}">${esc(p)}</option>`).join('')}</select><select id="model" aria-label="${t('筛选模型')}"><option value="">${t('全部模型')}</option>${m.models.map(p=>`<option ${p===state.model?'selected':''} value="${esc(p)}">${esc(p)}</option>`).join('')}</select><button class="button" data-page="sources">${t('管理来源')}</button></div>`;}
function metric(label,value,note=''){const aided=['记录中的估算费用','来源报告费用','成功率','延迟 P95','缓存读取占比'].includes(label);return `<div class="metric"><div class="metric-label">${aided?help(label):t(label)}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`;}
function monitorEmpty(){return `<section class="panel padded"><h2>${t('添加使用记录')}</h2><p>${t('连接本机编码工具或用量文件。')}</p><button class="button primary" data-page="sources">${t('添加监控来源')}</button></section>`;}
function monitorNotice(){const m=state.data.monitor,s=m.sources.find(s=>s.id===m.source);if(!s)return '';const bad=s.state==='error',overlap=m.summary.overlapRecords||0,sourceNames=(m.summary.overlapSources||[]).map(id=>{const source=m.sources.find(item=>item.id===id);return source?sourceName(source):id;});return `<div class="monitor-footer caption ${bad||overlap?'warning':''}"><span>${t(bad?'读取来源失败':!s.enabled?'已暂停':s.state==='reading'?'正在读取':'最近同步')} ${s.at?datetime(s.at):'—'}</span><span>${s.invalid?`${t('未解析记录')} ${fmt.format(s.invalid)} · `:''}${overlap?`${t('发现 {n} 条跨来源重叠记录',{n:overlap})}${sourceNames.length?` · ${t('重叠来源')}: ${esc(sourceNames.join(', '))}`:''} · `:''}${t('按所选来源统计，避免重复汇总。')}</span></div>`;}
overview=function(){if(!state.multi)return beforeMonitorOverview();const m=state.data.monitor,s=m.summary;const header=head(t('总览'),periodSelect()+`<button class="button" data-monitor-export>${t('导出')}</button>`);if(!m.sources.length)return header+monitorEmpty();
 const costs=s.requests-s.unpriced,qoderContext=m.models.includes('Qoder Quest');return header+monitorFilters()+`<div class="metrics monitor-metrics">${metric('请求数',compact(s.requests),`${compact(s.tokens)} tokens`)}${metric('记录中的估算费用',s.estimatedRecords?money(s.estimated):'—','')}${metric('来源报告费用',s.reportedRecords?money(s.reported):'—','')}${metric('成功率',s.successRate===null?'—':percentage(s.successRate,1),`${fmt.format(s.failed)} ${t('失败')} / ${fmt.format(s.knownStatus)} ${t('有状态记录')}`)}${metric('延迟 P95',s.p95===null?'—':decimal(s.p95/1000,2)+' s',t('仅含有延迟的记录'))}${metric('缓存读取占比',percentage(s.cached,s.input),`${compact(s.cached)} tokens`)}</div>${qoderContext?`<div class="notice compact-notice">${t('Qoder Quest 使用本机上下文快照估算 Tokens；原始 Credits 仍需在 Qoder 内查看')}</div>`:''}${s.sourceCreditRecords?`<div class="notice compact-notice">Qoder Credits: ${decimal(s.sourceCredits,2)} · ${t('原始 Credits 与 API 等价成本分开统计')}</div>`:''}<div class="two-col">${monitorDistribution(m)}<section class="panel padded"><h2>${t('每日用量')}</h2><div class="monitor-days">${m.days.slice(-30).map(d=>`<button class="monitor-day" data-monitor-day="${d.key}" title="${d.key}: ${compact(d.tokens)} tokens"><span style="height:${Math.max(2,d.tokens/Math.max(...m.days.map(x=>x.tokens),1)*(innerHeight<720?65:130))}px"></span><small>${d.key.slice(8)}</small></button>`).join('')}</div><div class="row between caption"><span>${m.days.at(-30)?.key||m.days[0]?.key||'—'}</span><span>${m.days.at(-1)?.key||'—'}</span></div><div class="info-row"><span>${help('首 Token 延迟 P50')}</span><strong>${s.ttft===null?'—':decimal(s.ttft/1000,2)+' s'}</strong></div><div class="info-row"><span>${t('未计价')}</span><button class="text-button" data-monitor-unpriced>${fmt.format(s.unpriced)} →</button></div></section></div>${monitorNotice()}`;
};
function compatibilityPanel(){const list=state.data.monitor.compatibility||[];if(!list.length)return '';const statusLabel={supported:'已支持',partial:'部分支持',candidate:'候选'};return `<section class="panel padded compatibility-panel"><div class="row between"><div><h2>${t('平台兼容性')}</h2><p class="caption">${t('仅在有明确本地数据来源时标记为已支持')}</p></div><span class="pill">${t('证据分级')}</span></div><div class="compatibility-grid">${list.map(c=>`<div class="compatibility-item"><div class="row between"><strong>${esc(c.name)}</strong><span class="pill ${c.level==='supported'?'green':c.level==='partial'?'amber':''}">${t(statusLabel[c.level])}</span></div><p>${t(c.detailKey)}</p>${c.connected?`<small class="green">${t('已连接')}</small>`:''}</div>`).join('')}</div></section>`;}
function monitorRows(){const m=state.data.monitor;return `<div class="table-wrap"><table><thead><tr><th>${t('时间')}</th><th>${t('供应商')} / ${t('模型')}</th><th>${help('Tokens')}</th><th>${help('费用','多供应商费用')}</th><th>${t('状态')}</th><th>${help('延迟')}</th><th></th></tr></thead><tbody>${m.rows.length?m.rows.map(e=>{const sourceNames=(e.overlap?.sources||[]).map(id=>{const source=m.sources.find(item=>item.id===id);return source?sourceName(source):id;});return `<tr><td>${datetime(e.at)}</td><td>${esc(e.provider)}<div class="sub">${esc(e.model)}</div>${e.overlap?`<div class="sub warning" title="${esc(sourceNames.join(', '))}">${t(e.overlap.kind==='exact'?'已匹配其他来源':'可能与其他来源重复')}</div>`:''}</td><td>${compact(e.total)}</td><td>${e.usd===null?`<span class="pill amber">${help('未计价')}</span>`:money(e.usd)}<div class="sub">${help(e.basis==='reported'?'来源报告':'估算',e.basis==='reported'?'来源报告费用':'记录中的估算费用')}</div></td><td>${e.status??'—'}</td><td>${e.latencyMs===null?'—':decimal(e.latencyMs/1000,2)+' s'}</td><td><button class="text-button" data-monitor-detail="${e.id}">${t('详情')}</button></td></tr>`;}).join(''):`<tr><td colspan="7"><div class="empty">${t('暂无记录')}</div></td></tr>`}</tbody></table></div>`;}
activity=function(){if(!state.multi)return beforeMonitorActivity();const m=state.data.monitor;return head(t('用量'),periodSelect()+`<button class="button" data-monitor-export>${t('导出')}</button>`)+monitorFilters()+`<div class="filters"><input id="search" class="input" aria-label="${t('搜索供应商或模型')}" placeholder="${t('搜索供应商或模型')}" value="${esc(state.query)}"><select id="sort" aria-label="${t('排序')}"><option value="cost" ${state.sort==='cost'?'selected':''}>${t('成本最高')}</option><option value="recent" ${state.sort==='recent'?'selected':''}>${t('最近活动')}</option></select><select id="monitor-overlap" aria-label="${t('重叠筛选')}"><option value="" ${!state.overlap?'selected':''}>${t('全部记录')}</option><option value="exact" ${state.overlap==='exact'?'selected':''}>${t('精确重叠')}</option><option value="possible" ${state.overlap==='possible'?'selected':''}>${t('可能重叠')}</option></select><button class="button" data-monitor-failed aria-pressed="${state.failed}">${t('仅失败请求')}</button><button class="button" data-monitor-unpriced aria-pressed="${state.unpriced}">${t('仅未计价')}</button><button class="text-button" data-monitor-clear>${t('清除筛选')}</button></div>${state.day?`<p class="caption">${esc(state.day)}</p>`:''}<section class="panel">${monitorRows()}<div class="pagination"><span>${m.summary.requests?m.offset+1:0}–${Math.min(m.offset+m.limit,m.summary.requests)} / ${fmt.format(m.summary.requests)}</span><div class="row"><button class="button small" data-action="prev" ${!m.offset?'disabled':''}>${t('上一页')}</button><button class="button small" data-action="next" ${m.offset+m.limit>=m.summary.requests?'disabled':''}>${t('下一页')}</button></div></div></section>${monitorNotice()}`;};
sources=function(){const html=beforeMonitorSources(),m=state.data.monitor,detected=state.data.desktop.detectedMonitors||[],available=detected.filter(s=>!s.connected);const discovery=detected.length?`<div class="detected-sources"><div class="row between"><div><h3>${t('已发现的工具')}</h3><p class="caption">${t('从常用本机目录自动发现')}</p></div>${available.length?`<button class="button primary small" data-monitor-detect="all">${t('连接全部')} · ${available.length}</button>`:`<span class="pill green">${t('已全部连接')}</span>`}</div>${detected.map(s=>`<div class="detected-source"><div><strong>${esc(sourceName(s))}</strong><span class="caption">${esc(s.path)}</span></div>${s.connected?`<span class="pill green">${t('已连接')}</span>`:`<button class="button small" data-monitor-detect="${esc(s.kind)}">${t('连接')}</button>`}</div>`).join('')}</div>`:`<div class="notice compact-notice">${t('未在常用目录发现工具，可手动选择。')}</div>`;return html+compatibilityPanel()+`<section class="panel padded section-gap"><div class="row between"><h2>${t('多供应商使用记录')}</h2><span class="pill">${t('本机只读')}</span></div><p class="caption">${t('只采集用量与性能字段，不读取密钥配置，不保存聊天正文。')}</p>${discovery}<div class="row monitor-add"><select id="monitor-kind" aria-label="${t('来源类型')}"><option value="qoder">Qoder · stream-json</option><option value="qwen">Qwen Code · usage</option><option value="kimi">Kimi Code · sessions</option><option value="codebuddy">CodeBuddy Code · projects</option><option value="cc-switch">CC Switch · SQLite</option><option value="claude">Claude Code · projects</option><option value="gemini">Gemini CLI · tmp</option><option value="usage-jsonl">API · JSONL</option></select><button class="button" data-monitor-add>${t('手动添加')}</button></div>${m.sources.map(s=>`<div class="monitor-source"><div><strong>${esc(sourceName(s))}</strong> <span class="pill">${t(!s.enabled?'已暂停':s.state==='error'?'读取来源失败':s.state==='reading'?'正在读取':'已添加')}</span><div class="sub path-item">${esc(s.path)}</div><div class="caption">${fmt.format(s.records)} ${t('用量记录')} · ${s.at?datetime(s.at):'—'}</div></div><button class="button small" data-monitor-toggle="${s.id}" data-enabled="${!s.enabled}">${t(s.enabled?'暂停采集':'继续采集')}</button></div>`).join('')}</section>`;};
models=function(){if(!state.multi)return beforeMonitorModels();const m=state.data.monitor;return head(t('价格'),`<button class="button" data-monitor-rate>${t('添加计价规则')}</button>`)+`<p class="notice">${t('自定义规则仅为未计价记录估算费用，不覆盖来源报告的金额。')} · USD / ${t('百万 Tokens')}</p><section class="panel"><div class="table-wrap"><table><thead><tr><th>${t('供应商')}</th><th>${t('模型')}</th><th>${t('普通输入')}</th><th>${t('缓存读取')}</th><th>${t('缓存写入')}</th><th>${t('输出')}</th></tr></thead><tbody>${m.rates.length?m.rates.map(r=>`<tr><td>${esc(r.provider)}</td><td>${esc(r.model)}</td>${['input','cached','write','output'].map(k=>`<td>${esc(r.rates[k])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="6"><div class="empty">${t('暂无记录')}</div></td></tr>`}</tbody></table></div></section>`;};
function monitorRate(provider='',model=''){modal(t('添加计价规则'),`<form id="monitor-rate-form"><div class="field"><label>${t('供应商')}</label><input class="input" name="provider" required value="${esc(provider)}"></div><div class="field"><label>${t('模型')}</label><input class="input" name="model" required value="${esc(model)}"></div><p class="caption">USD / ${t('百万 Tokens')}</p>${[['input','普通输入'],['cached','缓存读取'],['write','缓存写入'],['output','输出']].map(([k,l])=>`<div class="field"><label>${t(l)}</label><input class="input" name="${k}" type="number" min="0" max="1000000" step="any" required></div>`).join('')}<button class="button primary" type="submit">${t('保存')}</button></form>`);}
function monitorDetail(id){const e=state.data.monitor.rows.find(e=>e.id===id);if(!e)return;modal(t('用量详情'),`<p>${esc(e.provider)} · ${esc(e.model)}<br>${datetime(e.at)}</p>${[['普通输入',e.input-e.cached-e.write],['缓存读取',e.cached],['缓存写入',e.write],['输出',e.output],['其中推理（已含在输出）',e.reasoning],['状态',e.status],['延迟',e.latencyMs===null?null:e.latencyMs+' ms'],['首 Token 延迟',e.ttftMs===null?null:e.ttftMs+' ms']].map(([l,v])=>`<div class="info-row"><span>${t(l)}</span><span>${esc(v??'—')}</span></div>`).join('')}${e.sourceAmount!==null?`<div class="info-row"><span>Qoder Credits</span><strong>${esc(e.sourceAmount/1e15)}</strong></div>`:''}<div class="detail-price">${money(e.usd)}</div><p>${t(e.basis==='reported'?'来源报告费用':'记录中的估算费用')} · ${esc(e.origin)}<br>${t('计价模型')} ${esc(e.pricingModel)}</p>${e.amount===null?`<button class="button" id="detail-add-rate">${t('添加计价规则')}</button>`:''}`);if(e.amount===null)$('#detail-add-rate').onclick=()=>monitorRate(e.provider,e.model);}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;const d=b.dataset;if(!Object.keys(d).some(k=>k.startsWith('monitor')))return;event.preventDefault();event.stopImmediatePropagation();
 if(d.monitorView){state.multi=d.monitorView==='multi';distributionState.provider=null;state.provider='';state.model='';state.query='';state.day='';state.unpriced=false;state.failed=false;state.overlap='';state.offset=0;load();}
 if(d.monitorAdd!==undefined)action(()=>api('chooseMonitor',$('#monitor-kind').value));
 if(d.monitorDetect)action(()=>api('addDetectedMonitors',d.monitorDetect==='all'?null:d.monitorDetect),result=>t('已连接 {n} 个来源',{n:result.added}));
 if(d.monitorToggle)action(()=>api('configureMonitor',d.monitorToggle,{enabled:d.enabled==='true'}));
 if(d.monitorExport!==undefined)action(()=>api('exportMonitor',filters()),n=>t('已导出 {n} 条记录',{n}));
 if(d.monitorProvider!==undefined){state.provider=d.monitorProvider;state.page='activity';state.offset=0;load();}
 if(d.monitorDay){state.day=d.monitorDay;state.page='activity';state.offset=0;load();}
 if(d.monitorFailed!==undefined){state.failed=!state.failed;state.offset=0;load();}
 if(d.monitorUnpriced!==undefined){state.unpriced=!state.unpriced;state.page='activity';state.offset=0;load();}
 if(d.monitorClear!==undefined){state.provider='';state.model='';state.query='';state.day='';state.unpriced=false;state.failed=false;state.overlap='';state.offset=0;load();}
 if(d.monitorDetail)monitorDetail(d.monitorDetail);
 if(d.monitorRate!==undefined)monitorRate();
},true);
document.addEventListener('change',event=>{if(event.target.id==='monitor-source'){state.connection=event.target.value;state.provider='';state.model='';state.overlap='';state.offset=0;load();}if(event.target.id==='monitor-provider'){state.provider=event.target.value;state.offset=0;load();}if(event.target.id==='monitor-overlap'){state.overlap=event.target.value;state.offset=0;load();}});
document.addEventListener('submit',event=>{if(event.target.id!=='monitor-rate-form')return;event.preventDefault();const f=new FormData(event.target);action(async()=>{await api('monitorRate',f.get('provider'),f.get('model'),Object.fromEntries(['input','cached','write','output'].map(k=>[k,f.get(k)])));$('#dialog').close();},()=>t('已保存'));});
