'use strict';
// Product-level views reuse the same ledger, account connection and window.
Object.assign(state,{view:'sessions',sort:'cost',project:'',session:'',day:'',unpriced:false,quotaKey:'',quotaForecast:'quota_window',trendRange:'period',trendView:'daily'});
const baseFilters=filters,baseRender=render,baseSettings=settings,baseSources=sources,baseNavigate=navigate;
const baseChart=chart;
chart=function(){let index=0;return baseChart().replace(/<rect class="bar"[\s\S]*?<\/rect>/g,bar=>{const d=state.data.days[index++];return `<g class="chart-hit" data-chart-day="${d.date}" role="button" tabindex="0" aria-label="${d.date}">${bar}</g>`;});};
filters=()=>({...baseFilters(),project:state.project,session:state.session,day:state.day,unpriced:state.unpriced,sort:state.sort});
const pricedValue=s=>s.unpriced>0&&s.unpriced===s.events?null:s.usd;
const dateOnly=value=>new Date(value+'T12:00:00').toLocaleDateString(locale(),{year:'numeric',month:'short',day:'numeric'});
function duration(seconds){if(seconds===null||!Number.isFinite(seconds))return '—';const minutes=Math.max(1,Math.ceil(seconds/60));const f=(n,unit)=>new Intl.NumberFormat(locale(),{style:'unit',unit,unitDisplay:'short',maximumFractionDigits:0}).format(n);if(minutes<60)return f(minutes,'minute');if(minutes<1440)return f(Math.floor(minutes/60),'hour')+' '+f(minutes%60,'minute');return f(Math.floor(minutes/1440),'day')+' '+f(Math.floor(minutes%1440/60),'hour');}
function selectedQuota(){const rows=state.data.outlooks||[];const codex=rows.filter(w=>w.limit==='codex');return rows.find(w=>w.limit+':'+w.window===state.quotaKey)||[...(codex.length?codex:rows)].sort((a,b)=>b.used-a.used)[0];}
function quotaStatus(w){return t(({stale:'额度需要刷新',expired:'等待重置确认',exhausted:'额度已用尽',learning:'正在积累额度观测',risk:'按近期速度可能提前用尽',on_track:'按近期速度可用至重置',uncertain:'暂不能确定是否够用'})[w?.state]||'未连接');}
function quotaForecast(w){const key=state.quotaForecast||'quota_window';return {key,forecast:key==='quota_window'?w?.forecast:w?.forecasts?.[key]||null,label:t(({quota_window:'本额度窗口累计',recent_24h:'最近24小时',recent_2h:'最近2小时'})[key]||'本额度窗口累计')};}
function quotaCard(compact=false){const d=state.data,w=selectedQuota();if(!w)return `<section class="panel quota-card"><div class="panel-head"><h2>${help('套餐额度')}</h2></div><div class="empty"><p>${t('连接套餐账户，查看额度。')}</p><button class="button primary" data-action="connect">${t('连接账户')}</button><button class="text-button" data-page="sources">${t('管理')}</button></div></section>`;
  const live=!['stale','expired'].includes(w.state),tone=['risk','exhausted'].includes(w.state)?'warning':'';
  const choice=`<select id="quota-window" aria-label="${t('选择额度窗口')}">${d.outlooks.map(q=>`<option value="${esc(q.limit+':'+q.window)}" ${q===w?'selected':''}>${esc(q.label||q.limit)} · ${windowLabel(q)}</option>`).join('')}</select>`;
  const advice=w.advice,selectedForecast=quotaForecast(w),forecast=selectedForecast.forecast;
  const forecastModes=[['quota_window','本额度窗口累计'],['recent_24h','最近24小时'],['recent_2h','最近2小时']];
  const forecastSwitch=!compact?`<div class="quota-forecast-head"><span>${t('预估剩余时间')}</span><div class="segments">${forecastModes.map(([key,label])=>`<button type="button" data-quota-forecast="${key}" class="${selectedForecast.key===key?'active':''}">${t(label)}</button>`).join('')}</div></div>`:'';
  const forecastBody=forecast?`<div class="quota-forecast-value"><strong>${duration(forecast.fastSeconds)} – ${duration(forecast.slowSeconds)}</strong></div><div class="quota-forecast-note">${t('按 {n} 分钟有效观测推算',{n:Math.round(forecast.minutes)})}<span title="${t('持续当前使用速度的估算，实际可用时间会变化。')}"> ⓘ</span></div>`:`<div class="quota-forecast-empty">${live?t('当前模式暂无足够观测。'):t('最近观测')+' '+datetime(w.observedAt)}</div>`;
  return `<section class="panel quota-card"><div class="panel-head"><h2>${help('套餐额度')}</h2>${choice}</div><div class="quota-main"><div><span class="quota-number">${live?decimal(w.remaining,0):'—'}<small>${live?'%':''}</small></span><span class="muted">${t('剩余额度')}</span></div><div class="reset-time"><strong>${duration(w.secondsToReset)}</strong><span>${t('距重置')}</span></div></div><div class="quota-meter"><span style="width:${live?w.remaining:0}%"></span></div><div class="pace-line ${tone}"><span class="status-dot"></span><strong>${quotaStatus(w)}</strong>${!live?`<button class="text-button" data-action="connect">${t('刷新连接')}</button>`:''}</div><div class="quota-forecast">${forecastSwitch}${forecastBody}</div>${!compact?`<div class="quota-footer"><span class="pill ${live?'green':''}">${live?t('已连接'):t('历史快照')}</span><span class="quota-footer-actions">${advice?`<button class="text-button quota-advice-action" data-action="model-advice">${t('查看模型建议')}</button>`:''}<button class="text-button" data-page="sources">${t('管理')}</button></span></div>`:''}</section>`;
}
function billingCard(){const c=state.data.cycle;if(c.paid===null)return `<section class="panel billing-card"><h2>${t('本账期')}</h2><p>${dateOnly(c.start)} — ${dateOnly(c.end)}</p><div class="bill-value">${money(pricedValue(c))}</div><span class="caption">${t('已计价的 API 等价成本')}</span><div class="section-gap"><button class="button" data-page="settings">${t('填写套餐实付')}</button></div></section>`;
  const passed=c.diff!==null&&c.diff>=0;const unknown=pricedValue(c)===null;return `<section class="panel billing-card"><div class="row between"><h2>${t('本账期')}</h2><button class="text-button" data-page="settings">${t('设置')}</button></div><p>${dateOnly(c.start)} — ${dateOnly(c.end)}</p><div class="bill-value">${money(pricedValue(c))} <small>/ ${money(c.paid)}</small></div><div class="caption">${t('API 等价成本 / 账期实付')}</div><div class="bill-progress"><span style="width:${Math.min(100,Math.max(0,(c.progress||0)*100))}%"></span></div><div class="bill-result"><strong>${t(unknown?'尚无可计价记录':passed?'已超过实付':'距覆盖实付还差')}</strong><span>${money(unknown?null:passed?c.diff:c.remaining)}</span></div><div class="caption">${c.unpriced?t('部分记录未计价，当前金额为已计价部分。'):t('仅基于已采集记录，不代表实际退款或现金节省。')}</div></section>`;}
function healthSummary(){const d=state.data,h=d.health,n=h.readErrors+h.parseErrors+h.partial+d.summary.unpriced;return `<button class="health-link ${n?'warning':''}" data-action="health"><span class="status-dot"></span>${n?t('数据需要核对'):t('数据状态')} · ${t('计价覆盖率')} ${percentage(d.summary.pricedTokens,d.summary.tokens)} <span>↗</span></button>`;}
function projectCard(){const d=state.data;return `<section class="panel project-card"><div class="panel-head"><h2>${t('用在哪些项目')}</h2><button class="text-button" data-page="activity">${t('查看全部')}</button></div><div class="project-list">${d.projects.length?d.projects.slice(0,5).map(p=>`<button class="project-item" data-project="${esc(p.key)}"><div class="row between"><span>${esc(p.key)}</span><strong>${money(pricedValue(p))}</strong></div><div class="model-track"><span style="width:${d.summary.usd?p.usd/d.summary.usd*100:0}%"></span></div><div class="row between caption"><span>${t('{n} 个会话',{n:p.sessions})}</span><span>${compact(p.tokens)} tokens</span></div></button>`).join(''):`<div class="empty">${t('暂无记录')}</div>`}</div></section>`;}
function modelAdviceCard(){const a=state.data.mixAdvice;if(!a||a.state!=='ready')return `<section class="panel model-advice-card"><div class="panel-head"><div><h2>${help('模型组合')}</h2><p>${t('正在学习你的模型习惯和额度速度')}</p></div><span class="pill">${t('学习中')}</span></div><div class="advice-empty">${t('至少使用两个可计价模型，并积累15分钟额度变化后生成建议。')}</div></section>`;
 const current=new Map(a.current.map(m=>[m.model,m.share])),title=a.basis==='local_history'?t('基于本地历史用量'):a.direction==='reduce'?t('降低高强度模型占比'):a.direction==='increase'?t('可提高高强度模型占比'):t('维持当前模型组合'),pace=a.paceChange===null?t('等待实时额度速度'):a.paceChange===0?t('当前速度接近目标'):t(a.paceChange>0?'目标速度提高 {n}%':'目标速度降低 {n}%',{n:Math.abs(a.paceChange)});
 const rows=[...a.recommended].sort((x,y)=>y.share-x.share).slice(0,4).map(m=>{const before=Math.max(0,Math.min(1,Number(current.get(m.model)||0))),target=Math.max(0,Math.min(1,Number(m.share)||0)),delta=Math.round((target-before)*100),currentPct=Math.round(before*100),targetPct=Math.round(target*100),low=Math.min(before,target),changeClass=delta>0?'up':delta<0?'down':'steady',changeLabel=delta>0?t('增加'):delta<0?t('降低'):t('保持');return `<div class="advice-row"><span class="advice-model" title="${esc(m.model)}">${esc(m.model)}</span><div class="advice-track" role="img" aria-label="${esc(m.model)} · ${t('当前占比')} ${currentPct}% · ${t('建议占比')} ${targetPct}%"><span class="advice-current" style="width:${currentPct}%"></span>${delta?`<span class="advice-change ${changeClass}" style="left:${low*100}%;width:${Math.abs(delta)}%"></span>`:''}<span class="advice-target" style="left:${target*100}%"></span></div><div class="advice-share"><strong>${targetPct}%</strong><small>${t('当前占比')} ${currentPct}%</small></div><small class="advice-delta ${changeClass}" title="${changeLabel}">${delta?(delta>0?'+':'')+delta+'%':'—'}</small></div>`;}).join('');
 return `<section class="panel model-advice-card"><div class="panel-head"><div><h2>${help('模型组合')}</h2><p>${title}</p></div><span class="pill ${a.confidence==='medium'?'green':''}">${help(a.confidence==='medium'?'中等可信度':'低可信度','建议可信度')}</span></div><div class="advice-pace"><strong>${pace}</strong><span>${t('以当前额度窗口重置时间为目标')}</span></div><div class="advice-legend"><span><i class="advice-key-current"></i>${t('当前占比')}</span><span><i class="advice-key-up"></i>${t('增加')}</span><span><i class="advice-key-down"></i>${t('降低')}</span><span><i class="advice-key-target"></i>${t('建议占比')}</span></div><div class="advice-models">${rows}</div><div class="advice-note">${a.basis==='local_history'?t('建议基于已有本地历史；连接并观测额度后会校准。'):a.historyScope==='quota_window'?`${t('依据本额度窗口的模型用量、')}${help('API 等价强度')}${t('和本窗口平均额度速度；下个窗口会继续校准。')}`:`${t('依据近14天模型用量、')}${help('API 等价强度')}${t('和近期额度速度；下个窗口会继续校准。')}`}</div></section>`;}
function trendDaysForRange(all,range,period){const source=range==='period'?(period||[]):(all||[]);if(!source.length||range==='all'||range==='period')return source;const end=new Date(source.at(-1).date+'T12:00:00');const days=range==='7d'?7:range==='30d'?30:90;const from=new Date(end);from.setDate(from.getDate()-days+1);return source.filter(x=>new Date(x.date+'T12:00:00')>=from);}
function trendSvg(days,mode,cost){if(!days.length)return `<div class="empty">${t('暂无记录')}</div>`;const value=x=>cost?Number(x.usd||0):Number(x.tokens||0),width=760,height=190,pad={l:42,r:10,t:14,b:28},innerW=width-pad.l-pad.r,innerH=height-pad.t-pad.b;let values=days.map(value);if(mode==='cumulative'){let sum=0;values=values.map(v=>(sum+=v));}const max=Math.max(...values,1),step=innerW/Math.max(values.length,1),fmtValue=v=>cost?money(v):compact(v);const guides=[0,.5,1].map(p=>{const y=pad.t+innerH*(1-p);return `<line class="grid" x1="${pad.l}" y1="${y}" x2="${width-pad.r}" y2="${y}"/><text class="axis-label" x="2" y="${y+4}">${esc(fmtValue(max*p))}</text>`;}).join('');if(mode==='cumulative'){const points=values.map((v,i)=>`${pad.l+i*step+step/2},${pad.t+innerH-(v/max)*innerH}`).join(' ');return `<svg class="chart trend-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${t('累计趋势')}">${guides}<polyline class="trend-line" points="${points}"/>${values.map((v,i)=>{const x=pad.l+i*step,y=pad.t+innerH-(v/max)*innerH;return `<g class="chart-hit" data-chart-day="${days[i].date}" role="button" tabindex="0" aria-label="${days[i].date} ${esc(fmtValue(value(days[i])))}"><circle class="trend-point" cx="${x+step/2}" cy="${y}" r="3"/><rect class="chart-hit-area" x="${x}" y="${pad.t}" width="${step}" height="${innerH}"/></g>`;}).join('')}<text class="axis-label" x="${pad.l}" y="${height-5}">${esc(days[0].date)}</text><text class="axis-label" text-anchor="end" x="${width-pad.r}" y="${height-5}">${esc(days.at(-1).date)}</text></svg>`;}return `<svg class="chart trend-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${t('每日趋势')}">${guides}${values.map((v,i)=>{const barH=v/max*innerH,x=pad.l+i*step+step*.18,y=pad.t+innerH-barH;return `<g class="chart-hit" data-chart-day="${days[i].date}" role="button" tabindex="0" aria-label="${days[i].date} ${esc(fmtValue(v))}"><rect class="bar" x="${x}" y="${y}" width="${Math.max(2,step*.64)}" height="${Math.max(1,barH)}" rx="3"/><rect class="chart-hit-area" x="${pad.l+i*step}" y="${pad.t}" width="${step}" height="${innerH}"/></g>`;}).join('')}<text class="axis-label" x="${pad.l}" y="${height-5}">${esc(days[0].date)}</text><text class="axis-label" text-anchor="end" x="${width-pad.r}" y="${height-5}">${esc(days.at(-1).date)}</text></svg>`;}
// Calendar cells make sparse or bursty usage legible across a long time span.
function trendActivity(days,cost){if(!days.length)return `<div class="empty">${t('暂无记录')}</div>`;const value=row=>cost?Number(row.usd||0):Number(row.tokens||0),byDate=new Map(days.map(row=>[row.date,row])),latest=new Date(days.at(-1).date+'T12:00:00'),first=new Date(latest);first.setDate(first.getDate()-364);first.setHours(12,0,0,0);const start=new Date(first);start.setDate(start.getDate()-start.getDay());const calendar=[];for(let at=new Date(start);at<=latest;at.setDate(at.getDate()+1)){const date=at.toISOString().slice(0,10),row=byDate.get(date),amount=row?value(row):0;calendar.push({date,amount,events:row?.events||0});}const max=Math.max(...calendar.map(row=>row.amount),1),weeks=Math.ceil(calendar.length/7),level=amount=>amount<=0?0:Math.min(4,Math.max(1,Math.ceil(Math.log1p(amount)/Math.log1p(max)*4))),monthNames=calendar.filter((_,index)=>index%7===0).map((row,index)=>{const at=new Date(row.date+'T12:00:00'),prior=index?new Date(calendar[(index-1)*7].date+'T12:00:00'):null;return !prior||at.getMonth()!==prior.getMonth()?`<span>${at.toLocaleDateString(locale(),{month:'short'})}</span>`:'<span></span>';}).join(''),format=amount=>cost?money(amount):compact(amount)+' Tokens';return `<div class="trend-activity" style="--activity-weeks:${weeks}" role="group" aria-label="${t('活动热力图')}"><div class="trend-activity-months">${monthNames}</div><div class="trend-activity-grid">${calendar.map(row=>`<button class="trend-activity-cell level-${level(row.amount)}" ${row.events?`data-chart-day="${row.date}"`:'disabled'} title="${esc(row.date+' · '+format(row.amount))}" aria-label="${esc(row.date+' · '+format(row.amount))}"></button>`).join('')}</div><div class="trend-activity-scale"><span>${t('低')}</span><i class="level-0"></i><i class="level-1"></i><i class="level-2"></i><i class="level-3"></i><i class="level-4"></i><span>${t('高')}</span></div></div>`;}
function trendModelRows(d,days,cost){const selected=new Set(days.map(x=>x.date)),groups=new Map();for(const bucket of d.trend?.modelsByDay||[]){if(!selected.has(bucket.date))continue;for(const model of bucket.models||[]){const key=model.model||model.key;const row=groups.get(key)||{model:key,tokens:0,usd:0,events:0};row.tokens+=Number(model.tokens||0);row.usd+=Number(model.usd||0);row.events+=Number(model.events||0);groups.set(key,row);}}const rows=[...groups.values()].sort((a,b)=>(cost?b.usd-a.usd:b.tokens-a.tokens));if(!rows.length)return `<div class="empty">${t('暂无记录')}</div>`;const total=rows.reduce((n,x)=>n+(cost?x.usd:x.tokens),0)||1;return `<div class="trend-models">${rows.slice(0,8).map(row=>{const val=cost?row.usd:row.tokens,pct=val/total*100;return `<div class="trend-model-row"><div class="trend-model-meta"><strong title="${esc(row.model)}">${esc(row.model)}</strong><span>${cost?money(val):compact(val)} · ${decimal(pct,1)}%</span></div><div class="trend-model-track"><span style="width:${Math.max(1,pct)}%"></span></div></div>`;}).join('')}</div>`;}
function trendCard(){const d=state.data,trend=d.trend||{},all=trend.days||[],days=trendDaysForRange(all,state.trendRange,d.days||[]),cost=state.metric==='cost',value=x=>cost?Number(x?.usd||0):Number(x?.tokens||0),active=days.filter(x=>x.events>0),total=days.reduce((n,x)=>n+value(x),0),avg=active.length?total/active.length:0,peak=active.reduce((a,b)=>value(b)>value(a)?b:a,null),recent=days.slice(-7).reduce((n,x)=>n+value(x),0),prior=days.slice(-14,-7).reduce((n,x)=>n+value(x),0),change=prior?((recent-prior)/prior*100):null,metricLabel=cost?t('成本'):'Tokens';const rangeOptions=[['period','当前周期'],['7d','最近 7 天'],['30d','最近 30 天'],['90d','最近 90 天'],['all','全部历史']];const viewOptions=[['activity','活动热力图'],['daily','每日趋势'],['cumulative','累计趋势'],['models','模型分布']];const dateLabel=days.length?dateOnly(days[0].date)+' — '+dateOnly(days.at(-1).date):t('暂无记录'),content=state.trendView==='models'?trendModelRows(d,days,cost):state.trendView==='activity'?trendActivity(days,cost):trendSvg(days,state.trendView,cost),guidance=state.trendView==='models'?t('按模型查看所选时间范围'):state.trendView==='activity'?t('点击有颜色的日期查看当天明细'):t('点击图表查看当天明细');return `<section class="panel trend-card"><div class="panel-head"><div><h2>${t('用量趋势')}</h2><p>${dateLabel}</p></div><div class="trend-controls"><div class="segments"><button data-metric="cost" class="${cost?'active':''}">${t('成本')}</button><button data-metric="tokens" class="${!cost?'active':''}">Tokens</button></div><select id="trend-range" aria-label="${t('时间范围')}">${rangeOptions.map(([key,label])=>`<option value="${key}" ${state.trendRange===key?'selected':''}>${t(label)}</option>`).join('')}</select></div></div><div class="segments trend-view-tabs">${viewOptions.map(([key,label])=>`<button data-trend-view="${key}" class="${state.trendView===key?'active':''}">${t(label)}</button>`).join('')}</div><div class="trend-stats"><div><span>${t('日均 {metric}',{metric:metricLabel})}</span><strong>${cost?money(avg):compact(avg)}</strong><small>${t('仅含活跃日')}</small></div><div><span>${t('峰值日')}</span><strong>${peak?dateOnly(peak.date):'—'}</strong><small>${peak?(cost?money(value(peak)):compact(value(peak))):'—'}</small></div><div><span>${t('活跃天数')}</span><strong>${fmt.format(active.length)}</strong><small>${t('共 {n} 天',{n:days.length})}</small></div><div><span>${t('较前 7 天')}</span><strong class="${change!==null&&change>0?'warning':change!==null?'green':''}">${change===null?'—':(change>=0?'+':'')+decimal(change,1)+'%'}</strong><small>${t('最近 7 天')}</small></div></div><div class="chart-area">${content}</div><div class="trend-footer"><span>${guidance}</span><span>${cost?t('已计价记录'):t('已采集记录')} · ${esc(d.timezone)}</span></div></section>`;}
overview=function(){const d=state.data;if(!d.settings.roots.length&&!d.stats.records)return empty();const s=d.summary;const change=d.comparison?.change;
 return head(t('总览'),periodSelect()+`<button class="button" data-action="report">${t('分享摘要')}</button><button class="button" data-action="compact" title="Ctrl+Shift+M">${t('专注窗口')}</button>`)+`<div class="decision-grid">${quotaCard()}${billingCard()}</div><div class="metrics"><div class="metric"><div class="metric-label">${help('Tokens')}</div><div class="metric-value">${compact(s.tokens)}</div><div class="metric-note">${t('{n} 个会话',{n:s.sessions})}</div></div><div class="metric"><div class="metric-label">${help('API 等价成本')}</div><div class="metric-value">${money(pricedValue(s))}</div><div class="metric-note">${change===null||change===undefined?t('已计价记录'):(change>=0?'+':'−')+decimal(Math.abs(change*100),1)+'% · '+t('较前一等长时段')}</div></div><div class="metric"><div class="metric-label">${help('缓存读取占比')}</div><div class="metric-value">${percentage(s.cached,s.tokens-s.output)}</div><div class="metric-note">${compact(s.cached)} tokens</div></div><div class="metric"><div class="metric-label">${help('计价覆盖率')}</div><div class="metric-value">${percentage(s.pricedTokens,s.tokens)}</div><button class="text-button" data-action="health">${t('{n} 条未计价',{n:s.unpriced})} ↗</button></div></div><div class="two-col">${trendCard()}${projectCard()}</div>${modelAdviceCard()}<div class="overview-footer">${healthSummary()}<span class="caption">${t('价格')} ${esc(d.catalog.asOf)} · Standard · USD</span></div>`;
};
function filterChips(){const chips=[['project',state.project],['session',state.session?state.session.slice(0,12):''],['day',state.day],['unpriced',state.unpriced?t('未计价'):'']].filter(([,v])=>v);return chips.length?`<div class="filter-chips">${chips.map(([key,value])=>`<button class="chip" data-clear="${key}">${esc(value)} ×</button>`).join('')}<button class="text-button" data-action="clearFilters">${t('清除筛选')}</button></div>`:'';}
function projectsTable(){const d=state.data,projects=d.projects||[];return `<div class="table-wrap"><table class="usage-project-table"><thead><tr><th>${t('项目')}</th><th>${t('最近活动')}</th><th>Tokens</th><th>${t('API 等价成本')}</th><th></th></tr></thead><tbody>${projects.length?projects.map(p=>`<tr><td><button class="table-link" data-project="${esc(p.key)}"><strong title="${esc(p.key)}">${esc(p.key)}</strong></button><div class="sub usage-project-meta" title="${esc(p.models.join(', '))}">${t('{n} 个会话',{n:p.sessions})} · ${p.models.map(esc).join(', ')}</div></td><td>${datetime(p.last)}</td><td>${compact(p.tokens)}</td><td>${money(pricedValue(p))}${p.unpriced?`<div class="sub warning">${t('{n} 条未计价',{n:p.unpriced})}</div>`:''}</td><td><button class="text-button" data-project="${esc(p.key)}">${t('查看会话')} →</button></td></tr>`).join(''):`<tr><td colspan="5"><div class="empty">${t('暂无记录')}</div></td></tr>`}</tbody></table></div>`;}
function sessionsTable(){const d=state.data;return `<div class="table-wrap"><table><thead><tr><th>${t('会话 / 项目')}</th><th>${t('最近活动')}</th><th>Tokens</th><th>${t('API 等价成本')}</th><th></th></tr></thead><tbody>${d.sessions.length?d.sessions.map(s=>{const title=s.title||s.project;const meta=[s.title?s.project:null,`ID ${s.key.slice(0,12)}`,s.models.join(', ')].filter(Boolean).join(' · ');return `<tr><td><strong title="${esc(s.title||s.project)}">${esc(title)}</strong><div class="sub" title="${esc(s.key)}">${esc(meta)}</div>${s.parent?`<span class="pill">${t('子任务')}</span>`:''}</td><td>${datetime(s.last)}</td><td>${compact(s.tokens)}</td><td>${money(pricedValue(s))}${s.unpriced?`<div class="sub warning">${t('{n} 条未计价',{n:s.unpriced})}</div>`:''}</td><td><button class="text-button" data-session="${esc(s.key)}">${t('查看记录')} →</button></td></tr>`;}).join(''):`<tr><td colspan="5"><div class="empty">${t('暂无记录')}</div></td></tr>`}</tbody></table></div>`;}
activity=function(){const d=state.data,total=state.view==='projects'?d.projects.length:state.view==='sessions'?d.sessionTotal:d.summary.events;const deviceFilter=`<select id="device" aria-label="${t('筛选设备')}"><option value="">${t('全部设备')}</option>${d.devices.map(device=>`<option value="${esc(device.id)}" ${state.device===device.id?'selected':''}>${esc(device.label)}</option>`).join('')}</select>`;const crumb=state.project?`<div class="usage-breadcrumb"><button class="text-button" data-view="projects">${t('项目')}</button><span>›</span><strong>${esc(state.project)}</strong>${state.session?`<span>›</span><strong>${esc(state.session.slice(0,12))}</strong>`:''}</div>`:'';return head(t('用量'),periodSelect()+exportButton())+`<div class="usage-toolbar"><div class="segments usage-tabs"><button data-view="projects" class="${state.view==='projects'?'active':''}">${t('项目')}</button><button data-view="sessions" class="${state.view==='sessions'?'active':''}">${t('会话')}</button><button data-view="records" class="${state.view==='records'?'active':''}">${t('记录')}</button></div><select id="sort" aria-label="${t('排序')}"><option value="cost" ${state.sort==='cost'?'selected':''}>${t('成本最高')}</option><option value="recent" ${state.sort==='recent'?'selected':''}>${t('最近活动')}</option></select><span class="caption">${money(d.summary.usd)} · ${compact(d.summary.tokens)} tokens</span></div>${crumb}<div class="filters"><input class="input" id="search" aria-label="${t('搜索项目或会话')}" placeholder="${t('搜索项目、模型或会话')}" value="${esc(state.query)}">${deviceFilter}<select id="model" aria-label="${t('筛选模型')}"><option value="">${t('全部模型')}</option>${d.allModels.map(m=>`<option value="${esc(m)}" ${state.model===m?'selected':''}>${esc(m)}</option>`).join('')}</select><button class="button" data-action="onlyUnpriced" aria-pressed="${state.unpriced}">${t('仅未计价')}</button></div>${filterChips()}<section class="panel">${state.view==='projects'?projectsTable():state.view==='sessions'?sessionsTable():rowsTable(d.rows)}<div class="pagination"><span>${state.view==='projects'?`${projectsTable&&d.projects.length?1:0}–${d.projects.length} / ${fmt.format(total)}`:`${total?d.offset+1:0}–${Math.min(d.offset+d.limit,total)} / ${fmt.format(total)}`}</span><div class="row"><button class="button small" data-action="prev" ${state.view==='projects'||!d.offset?'disabled':''}>${t('上一页')}</button><button class="button small" data-action="next" ${state.view==='projects'||d.offset+d.limit>=total?'disabled':''}>${t('下一页')}</button></div></div></section>`;};
settings=function(){let html=baseSettings();const s=state.data.settings;
 const cycle=`<div class="field-pair"><div class="field"><label for="cycleMode">${t('账期模式')}</label><select name="cycleMode" id="cycleMode"><option value="manual" ${s.cycleMode==='manual'?'selected':''}>${t('手动日期')}</option><option value="monthly" ${s.cycleMode==='monthly'?'selected':''}>${t('每月自动续期')}</option></select></div><div class="field"><label for="billingDay">${t('每月续费日')}</label><input class="input" type="number" id="billingDay" name="billingDay" min="1" max="31" value="${s.billingDay}"><small>${t('短月份按最后一天续期。')}</small></div></div>`;
 html=html.replace(`<h2>${t('账期')}</h2>`,`<h2>${t('账期')}</h2>`+cycle).replace(t('额外额度 · USD'),t('本账期额外实付 · USD'));
 if(s.cycleMode==='monthly')html=html.replace('name="cycleStart"','name="cycleStart" readonly').replace('name="cycleEnd"','name="cycleEnd" readonly');
 const notifications=`<div class="notification-settings"><h3>${t('额度提醒')}</h3><label class="check-line"><input type="checkbox" name="notifications" ${s.notifications?'checked':''}>${t('剩余20%、5%及额度恢复时提醒')}</label><small class="caption">${t('仅使用新鲜账户数据，每个窗口不重复提醒。')}</small><div class="field-pair section-gap"><div class="field"><label for="quietStart">${t('免打扰开始（小时）')}</label><input class="input" name="quietStart" id="quietStart" type="number" min="0" max="23" value="${s.quietStart}"></div><div class="field"><label for="quietEnd">${t('免打扰结束（小时）')}</label><input class="input" name="quietEnd" id="quietEnd" type="number" min="0" max="23" value="${s.quietEnd}"></div></div><small class="caption">${t('起止相同为全天允许。后台提醒需保持应用运行。')}</small></div>`;
 return html.replace(`<div class="section-gap"><button type="button"`,notifications+`<div class="section-gap"><button type="button"`);
};
sources=function(){let html=baseSources(),remote=state.data.devices.filter(device=>!device.local).length;if(remote)html=html.replace(`<span>${t('未接入')}</span>`,`<span>${t('{n} 台已导入设备',{n:remote})}</span>`);for(const root of state.data.settings.roots){const status=state.data.scanner.roots?.find(r=>r.path===root)?.state;html=html.replace(`<div class="path-item">${esc(root)}</div>`,`<div class="path-item"><span>${esc(root)}</span><div class="row between"><small class="${status==='unavailable'?'warning':'muted'}">${t(status==='unavailable'?'目录不可用':status==='empty'?'未发现记录':'已添加')}</small><button class="text-button" data-remove-root="${esc(root)}">${t('停止监测')}</button></div></div>`);}return html;};
function focusView(){const d=state.data;return `<div class="focus-top"><strong>Subscription Lens</strong><div class="row"><button class="button small" data-action="pin" aria-pressed="${d.desktop.pinned}">${t(d.desktop.pinned?'取消置顶':'置顶')}</button><button class="button small" data-action="expand">${t('展开')}</button></div></div>${quotaCard(true)}<div class="focus-summary"><span>${t('本账期')}</span><strong>${money(pricedValue(d.cycle))}</strong><small>${t('API 等价成本')}</small></div><div class="focus-footer"><span>${t('最近观测')} ${clock(d.account.quota?.observedAt||d.quota?.observedAt)}</span><button class="text-button" data-action="refreshFocus">${t('刷新')}</button></div>`;}
render=function(){if(!state.data)return;document.body.classList.toggle('compact-mode',!!state.data.desktop?.compact);if(state.data.desktop?.compact){localizeShell();applyTheme();$('#main').innerHTML=focusView();return;}baseRender();};
navigate=function(page){state.project='';state.session='';state.day='';state.unpriced=false;baseNavigate(page);};
function openHealth(){const d=state.data,h=d.health;const names={model:'没有匹配的模型价格',tokens:'缺少 Token 分类',counter:'累计计数不一致',invalid:'Token 分类不一致',context:'缺少上下文档位价格',category:'缺少分类价格'};modal(t('数据状态'),`<div class="info-row"><span>${t('计价覆盖率')}</span><strong>${percentage(d.summary.pricedTokens,d.summary.tokens)}</strong></div>${h.reasons.map(r=>`<div class="info-row"><span>${t(names[r.reason]||'未计价')}</span><span>${fmt.format(r.count)}</span></div>`).join('')}<div class="info-row"><span>${t('读取或解析异常')}</span><span>${h.readErrors+h.parseErrors}</span></div><div class="info-row"><span>${t('历史记录不完整')}</span><span>${h.partial}</span></div><div class="info-row"><span>${t('价格快照日期')}</span><span>${esc(d.catalog.asOf)}</span></div><p>${t('覆盖率仅衡量已采集记录能否计价，不代表账户历史完整。')}</p><div class="row"><button class="button" data-action="healthRecords">${t('查看未计价')}</button><button class="button" data-action="healthPrices">${t('维护价格')}</button><button class="button" data-action="healthSources">${t('检查来源')}</button></div>`);}
async function openReport(){const d=await api('previewReport',filters());modal(t('分享摘要'),`<div class="report-preview"><div class="caption">Subscription Lens · ${t('本机 · Codex')}</div><h3>${datetime(d.from)} — ${datetime(new Date(d.to).getTime()-1)}</h3><div class="report-numbers"><div><span>Tokens</span><strong>${compact(d.tokens)}</strong></div><div><span>${t('API 等价成本')}</span><strong>${money(d.usd)}</strong></div></div><p>${t('计价覆盖率')} ${d.coverage===null?'—':percentage(d.coverage,1)} · ${t('价格')} ${esc(d.priceDate)}</p></div><p>${t('仅含汇总，不含账户、项目名、路径或会话标识。')}</p><button class="button primary" data-action="saveReport">${t('导出摘要')}</button>`);}
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const a=button.dataset.action;
 const handled=button.dataset.project!==undefined||button.dataset.session||button.dataset.day||button.dataset.view||button.dataset.trendView||button.dataset.clear||button.dataset.removeRoot||['compact','expand','pin','health','report','saveReport','healthRecords','healthPrices','healthSources','clearFilters','onlyUnpriced','refreshFocus','model-advice'].includes(a);if(!handled)return;event.stopImmediatePropagation();
 if(button.dataset.project!==undefined){state.project=button.dataset.project;state.session='';state.day='';state.page='activity';state.view='sessions';state.offset=0;load();return;}
 if(button.dataset.session){state.session=button.dataset.session;state.view='records';state.offset=0;load();return;}
 if(button.dataset.day){state.day=button.dataset.day;state.page='activity';state.view='sessions';state.offset=0;load();return;}
 if(button.dataset.view){const next=button.dataset.view;if(next==='projects'||next==='sessions'||next==='records'){state.project='';state.session='';state.day='';}state.view=next;state.offset=0;load();return;}
 if(button.dataset.trendView){state.trendView=button.dataset.trendView;render();return;}
 if(button.dataset.clear){state[button.dataset.clear]=button.dataset.clear==='unpriced'?false:'';state.offset=0;load();return;}
 if(button.dataset.removeRoot){const root=button.dataset.removeRoot;modal(t('停止监测'),`<p>${t('停止读取此目录，已采集历史和原始文件均保留。')}</p><button class="button primary" id="confirm-remove">${t('停止监测')}</button>`);$('#confirm-remove').onclick=()=>action(async()=>{await api('removeRoot',root);$('#dialog').close();});return;}
 if(a==='compact'||a==='expand'){action(()=>api('setCompact',a==='compact'));return;}
 if(a==='pin'){action(()=>api('setPinned',!state.data.desktop.pinned));return;}
 if(a==='model-advice'){const tab=document.querySelector('[data-layout-tab="advice"]');if(tab)tab.click();requestAnimationFrame(()=>document.querySelector('.model-advice-card')?.scrollIntoView({behavior:'smooth',block:'start'}));return;}
 if(a==='health'){openHealth();return;}
 if(a==='report'){openReport().catch(e=>toast(e.message));return;}
 if(a==='saveReport'){action(()=>api('exportReport',filters()),()=>t('已保存'),button);return;}
 if(a==='healthPrices'||a==='healthSources'){ $('#dialog').close();navigate(a==='healthPrices'?'models':'sources');return;}
 if(a==='healthRecords'){$('#dialog').close();state.page='activity';state.view='records';state.unpriced=true;state.offset=0;load();return;}
 if(a==='onlyUnpriced'){state.unpriced=!state.unpriced;state.offset=0;load();return;}
 if(a==='clearFilters'){state.project='';state.session='';state.day='';state.unpriced=false;state.query='';state.model='';state.offset=0;load();return;}
 if(a==='refreshFocus'){action(()=>api('refresh'));}
},true);
document.addEventListener('change',event=>{if(event.target.id==='quota-window'){state.quotaKey=event.target.value;render();}if(event.target.id==='trend-range'){state.trendRange=event.target.value;render();}if(event.target.id==='sort'){state.sort=event.target.value;state.offset=0;load();}if(event.target.id==='cycleMode'){for(const id of ['cycleStart','cycleEnd'])$('#'+id).readOnly=event.target.value==='monthly';}if(event.target.id==='period'){state.day='';state.session='';}},true);
document.addEventListener('click',event=>{const button=event.target.closest('[data-quota-forecast]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();state.quotaForecast=button.dataset.quotaForecast||'quota_window';render();},true);
document.addEventListener('submit',event=>{if(event.target.id!=='settings-form')return;event.preventDefault();event.stopImmediatePropagation();const f=new FormData(event.target);const settings={};for(const key of ['cycleStart','cycleEnd','cycleMode','language','theme'])settings[key]=f.get(key);for(const key of ['extra','billingDay','quietStart','quietEnd'])settings[key]=Number(f.get(key));settings.paid=f.get('paid')===''?null:Number(f.get('paid'));for(const key of ['tray','startup','notifications'])settings[key]=f.has(key);action(async()=>{const result=await api('saveSettings',settings);state.dirty=false;state.data.settings=result;return result;},()=>t('已保存'));},true);
document.addEventListener('keydown',event=>{if(event.ctrlKey&&event.shiftKey&&event.key.toLowerCase()==='m'){event.preventDefault();action(()=>api('setCompact',!state.data.desktop?.compact));}else if(event.ctrlKey&&event.key.toLowerCase()==='k'){event.preventDefault();if(state.data.desktop?.compact)return;state.page='activity';load().then(()=>$('#search')?.focus());}else if(event.key==='Escape'&&!$('#dialog').open&&state.data.desktop?.compact){action(()=>api('setCompact',false));}});
for(const type of ['click','keydown'])document.addEventListener(type,event=>{const target=event.target.closest('[data-chart-day]');if(!target||type==='keydown'&&!['Enter',' '].includes(event.key))return;event.preventDefault();state.day=target.dataset.chartDay;state.page='activity';state.view='sessions';state.offset=0;load();});
// Keep relative reset times current without taking focus from forms or searches.
setInterval(()=>{if(state.data&&!state.dirty&&!$('#dialog').open&&['overview'].includes(state.page)&&!['INPUT','SELECT'].includes(document.activeElement?.tagName))load();},30000);
