'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const catalog = JSON.parse(fs.readFileSync(path.join(root, 'src/locales.json'), 'utf8'));
for (const [key, values] of Object.entries(catalog)) {
  if (!Array.isArray(values) || values.length !== 2 || values.some(v => typeof v !== 'string' || !v)) throw new Error('Invalid translation: ' + key);
}
fs.writeFileSync(path.join(root, 'src/ui/locales.js'), '// Generated by scripts/build-locales.cjs. Edit src/locales.json.\nwindow.LensLocales = ' + JSON.stringify(catalog, null, 2) + ';\n');
