'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {_electron:electron}=require('playwright'),{Store}=require('../src/core/store.cjs'),{Monitor}=require('../src/core/monitor.cjs');
async function main(){const base=path.resolve(__dirname,'../test-results');await fs.mkdir(base,{recursive:true});const dir=await fs.mkdtemp(path.join(base,'monitor-ui-')),data=path.join(dir,'data');const store=new Store(data);store.set('settings',{language:'en-US',theme:'light'});const monitor=new Monitor(store),at=new Date().toISOString();
 const records=Array.from({length:37},(_,i)=>({schema:'subscription-lens.usage.v1',id:'r'+i,at,provider:i<24?'OpenAI':'Other',model:i%2?'gpt-5.6-luna':'gpt-6-astra',usage:{input:1000+i,output:100},cost:i===36?undefined:{usd:String((i+1)/100),basis:i%2?'reported':'estimate'},status:i%5?200:500,latencyMs:250+i,ttftMs:100}));const file=path.join(dir,'usage.jsonl');await fs.writeFile(file,records.map(JSON.stringify).join('\n')+'\n');await monitor.add('usage-jsonl',file);store.commit('fixture',{offset:0,size:0,mtime:0,state:{}},records.slice(0,24).map((r,i)=>({id:'c'+i,session:'s'+i,project:'Test',model:r.model,at,input:r.usage.input,cached:0,write:0,output:100,reasoning:0,total:r.usage.input+100,quality:'complete'})));store.close();
 const app=await electron.launch({executablePath:process.env.LENS_TEST_EXE||require('electron'),args:process.env.LENS_TEST_EXE?[]:[path.resolve(__dirname,'..')],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,LENS_DATA_DIR:data,LENS_TEST_HIDDEN:'1'}});const errors=[],checks=[];
 try{const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000);await page.waitForSelector('[data-layout-tab]');await page.click('[data-monitor-view="multi"]');await page.waitForSelector('.distribution-row');assert.equal(await page.locator('.distribution-row').count(),2);await page.locator('path[data-distribution-item]').first().click();assert.equal(await page.locator('.distribution-name').count(),2);assert.match(await page.locator('.distribution-breadcrumb').innerText(),/OpenAI/);await page.click('[data-distribution-metric="cost"]');assert.match(await page.locator('.distribution-panel').innerText(),/Estimated and source-reported/);await page.locator('.distribution-row').first().click();await page.waitForSelector('[data-monitor-detail]');assert.equal(await page.locator('#monitor-provider').inputValue(),'OpenAI');checks.push('Provider → model → filtered records, tokens/cost toggle');
 const fit=async label=>{await page.waitForTimeout(350);const sizes=await page.evaluate(()=>({scroll:document.documentElement.scrollHeight,height:innerHeight,width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));if(sizes.scroll>sizes.height+2){await page.screenshot({path:path.join(base,'monitor-overflow.png'),fullPage:true});console.log(await page.locator('main').evaluate(n=>[...n.children].map(c=>({class:c.className,top:c.getBoundingClientRect().top,height:c.getBoundingClientRect().height}))));}assert.ok(sizes.scroll<=sizes.height+2,label+' vertical '+JSON.stringify(sizes));assert.ok(sizes.scrollWidth<=sizes.width+2,label+' horizontal '+JSON.stringify(sizes));};
 for(const [width,height]of [[760,560],[820,600],[1024,768],[1320,900]]){await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setContentSize(...size),[width,height]);for(const lang of ['en-US','nl-NL','zh-CN']){await page.evaluate(async language=>window.lens.saveSettings({language}),lang);await page.waitForFunction(l=>document.documentElement.lang===l,lang);for(const mode of ['multi','codex']){await page.click(`[data-monitor-view="${mode}"]`);await page.click('aside [data-page="overview"]');await page.waitForSelector('.distribution-panel',{state:'attached'});await fit(`${width}/${lang}/${mode}/overview`);if(width<=820){for(const tab of await page.locator('[data-layout-tab]').evaluateAll(nodes=>nodes.map(n=>n.dataset.layoutTab))){await page.click('[data-layout-tab='+tab+']');await fit(`${width}/${lang}/${mode}/${tab}`);}await page.click(`[data-layout-tab=${mode==='multi'?'distribution':'summary'}]`);}await page.click('aside [data-page="activity"]');await page.waitForSelector('table');await fit(`${width}/${lang}/${mode}/activity`);await page.click('aside [data-page="models"]');await page.waitForSelector('table');await fit(`${width}/${lang}/${mode}/prices`);await page.click('aside [data-page="sources"]');await page.waitForSelector('.monitor-add',{state:'attached'});await fit(`${width}/${lang}/${mode}/sources`);if(lang!=='zh-CN')assert.doesNotMatch(await page.locator('main').innerText(),/[\u3400-\u9fff]/);}}console.log('Layout passed',width);checks.push(`No page scrolling at ${width}×${height}, 3 languages, 2 modes, 4 pages`);}
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1320,900));await page.click('aside [data-page="overview"]');await page.click('[data-monitor-view="multi"]');await page.waitForTimeout(500);await page.screenshot({path:path.join(base,'monitor-overview.png'),fullPage:true,timeout:60000,animations:'disabled'});assert.deepEqual(errors,[]);await fs.writeFile(path.join(base,'monitor-smoke.json'),JSON.stringify({checks},null,2));console.log(checks);
 }finally{await app.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
