'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {_electron:electron}=require('playwright');const {Store}=require('../src/core/store.cjs');
process.env.ELECTRON_CACHE=path.resolve(__dirname,'../.cache/electron');
async function main(){
 const base=path.resolve(__dirname,'../test-results');await fs.mkdir(base,{recursive:true});const dir=await fs.mkdtemp(path.join(base,'product-'));const data=path.join(dir,'data'),home=path.join(dir,'codex');await fs.mkdir(path.join(home,'sessions'),{recursive:true});
 const store=new Store(data);store.set('settings',{roots:[home],language:'en-US',paid:20,theme:'light',cycleMode:'monthly',billingDay:1});
 const now=Date.now(),at=new Date(now).toISOString();const event=(id,session,project,model,input,days)=>({id,session,project,model,at:new Date(now-days*86400000).toISOString(),input,cached:Math.floor(input*.75),write:0,output:1000,reasoning:500,total:input+1000,quality:'complete'});
 const events=[];for(let i=0;i<10;i++)events.push(event('record-'+i,'task-'+Math.floor(i/2),i<6?'Website':'Research',i===9?'future-model':'gpt-6-astra',60000+i*1000,i%5));
 store.commit('fixture',{offset:0,size:0,mtime:0,state:{}},events,{source:'record',observedAt:at,windows:[{limit:'codex',window:'primary',used:82,minutes:300,resetsAt:Math.floor(now/1000)+3600,observedAt:at}]});store.close();
 const executablePath=process.env.LENS_TEST_EXE||require('electron');const app=await electron.launch({executablePath,args:process.env.LENS_TEST_EXE?[]:[path.resolve(__dirname,'..')],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,LENS_DATA_DIR:data,LENS_TEST_HIDDEN:'1'}});
 const checks=[],errors=[];const push=checks.push.bind(checks);checks.push=(...items)=>{console.log(items.join("; "));return push(...items);};try{
  const page=await app.firstWindow();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.decision-grid');assert.match(await page.locator('.quota-card').innerText(),/Quota needs refreshing/);checks.push('Stale snapshots do not masquerade as live quota');
  await page.click('[data-project=Website]');await page.waitForSelector('[data-session]');assert.equal(await page.locator('tbody tr').count(),3);await page.locator('[data-session]').first().click();await page.waitForSelector('[data-detail]');assert.equal(await page.locator('tbody tr').count(),2);await page.locator('[data-detail]').first().click();await page.waitForSelector('dialog[open]');await page.click('#close-dialog');await page.click('[data-action=clearFilters]');checks.push('Project → session → exact records, with clearable filters');
  await page.click('aside [data-page=overview]');await page.click('[data-action=health]');await page.waitForSelector('dialog[open]');assert.match(await page.locator('#dialog-body').innerText(),/No matching model price/);await page.click('[data-action=healthRecords]');await page.waitForSelector('[data-detail]');assert.equal(await page.locator('tbody tr').count(),1);checks.push('Data-health problem opens only unpriced records');
  await page.click('aside [data-page=overview]');await page.locator('[data-chart-day]').last().focus();await page.keyboard.press('Enter');await page.waitForSelector('.filter-chips');assert.ok(await page.locator('[data-clear=day]').count());checks.push('Chart supports keyboard date drill-down');
  await page.click('aside [data-page=settings]');await page.waitForSelector('#cycleMode');await page.selectOption('#cycleMode','monthly');await page.fill('#billingDay','31');await page.check('[name=notifications]');await page.fill('#quietStart','22');await page.fill('#quietEnd','8');await page.click('button[type=submit]');await page.waitForTimeout(300);const settings=await page.evaluate(async()=>{const r=await window.lens.query({});return r.value.settings;});assert.equal(settings.billingDay,31);assert.equal(settings.notifications,true);checks.push('Recurring billing and quiet hours persist');
  await page.click('aside [data-page=overview]');await page.keyboard.press('Control+Shift+M');await page.waitForSelector('.compact-mode');await page.click('[data-action=pin]');await page.waitForTimeout(200);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isAlwaysOnTop()),true);await page.screenshot({path:path.join(base,'product-compact.png'),fullPage:true});await page.keyboard.press('Escape');await page.waitForSelector('body:not(.compact-mode)');assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isAlwaysOnTop()),false);checks.push('Compact window, pin and Escape restore the desktop');
  const reportFile=path.join(dir,'summary.html');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},reportFile);await page.click('[data-action=report]');await page.waitForSelector('.report-preview');assert.doesNotMatch(await page.locator('#dialog-body').innerText(),/Website|Research|task-/);await page.click('[data-action=saveReport]');for(let i=0;i<50;i++){try{await fs.access(reportFile);break;}catch{await page.waitForTimeout(100);}}const html=await fs.readFile(reportFile,'utf8');assert.doesNotMatch(html,/Website|Research|task-|product-|<script/);await page.click('#close-dialog');checks.push('Preview and native save export aggregate-only HTML');
  await page.click('aside [data-page=settings]');await page.selectOption('#language','nl-NL');await page.click('button[type=submit]');await page.waitForFunction(()=>document.documentElement.lang==='nl-NL');await page.click('aside [data-page=overview]');await page.screenshot({path:path.join(base,'product-overview-nl.png'),fullPage:true});assert.doesNotMatch(await page.locator('main').innerText(),/[\u3400-\u9fff]/);await page.click('aside [data-page=settings]');await page.selectOption('#language','zh-CN');await page.click('button[type=submit]');await page.waitForFunction(()=>document.documentElement.lang==='zh-CN');await page.click('aside [data-page=overview]');await page.screenshot({path:path.join(base,'product-overview-zh.png'),fullPage:true});checks.push('New overview works in Dutch and Chinese');
  await page.click('aside [data-page=sources]');await page.click('[data-remove-root]');await page.click('#confirm-remove');await page.waitForTimeout(300);const remaining=await page.evaluate(async()=>{const r=await window.lens.query({period:'all'});return {roots:r.value.settings.roots,records:r.value.stats.records};});assert.equal(remaining.roots.length,0);assert.equal(remaining.records,10);await page.click('aside [data-page=overview]');await page.waitForSelector('.metrics');checks.push('Stopping a source retains the ledger and overview');
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(base,'product-smoke'+(process.env.LENS_TEST_EXE?'-packaged':'')+'.json'),JSON.stringify({at:new Date().toISOString(),packaged:!!process.env.LENS_TEST_EXE,checks},null,2));console.log(JSON.stringify(checks,null,2));
 }finally{await app.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
