'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');
process.env.ELECTRON_CACHE=path.resolve(__dirname,'../.cache/electron');
const {_electron:electron}=require(process.env.LENS_PLAYWRIGHT_PATH||'playwright');
async function main(){const base=path.resolve(__dirname,'../test-results');await fs.mkdir(base,{recursive:true});const userData=await fs.mkdtemp(path.join(base,'desktop-'));const executable=process.env.LENS_TEST_EXE||require('electron');const packaged=!!process.env.LENS_TEST_EXE;
  const app=await electron.launch({executablePath:executable,args:packaged?[]:[path.resolve(__dirname,'..')],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,LENS_DATA_DIR:userData,LENS_TEST_HIDDEN:'1'}});
  const results=[];try{const page=await app.firstWindow();const pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));await page.waitForSelector('h1');await page.evaluate(()=>window.lens.saveSettings({language:'zh-CN'}));await page.waitForFunction(()=>document.documentElement.lang==='zh-CN');assert.equal(await page.locator('h1').innerText(),'总览');results.push('Fresh install opens without seeded data');
    await page.click('[data-action=defaultRoot]');await page.waitForSelector('.metrics',{timeout:30000});const data=await page.evaluate(async()=>{const r=await window.lens.query({period:'all'});return {records:r.value.stats.records,tokens:r.value.summary.tokens,unpriced:r.value.summary.unpriced,models:r.value.models.map(m=>m.model),errors:r.value.scanner.errors};});assert.ok(data.records>0);assert.ok(data.tokens>0);assert.equal(data.errors,0);results.push('Real Codex usage collected');
    await page.selectOption('#period','all');await page.waitForTimeout(400);await page.screenshot({path:path.join(base,packaged?'release-overview.png':'overview.png'),fullPage:true});
    await page.click('nav [data-page=activity]');await page.waitForSelector('#search');await page.fill('#search','__no_such_project__');await page.waitForTimeout(500);assert.match(await page.locator('tbody').innerText(),/暂无记录/);await page.fill('#search','');await page.waitForTimeout(500);await page.click('[data-view=records]');await page.locator('[data-detail]').first().click();await page.waitForSelector('dialog[open]');assert.match(await page.locator('#dialog-body').innerText(),/缓存读取/);await page.click('#close-dialog');results.push('Search and real record detail work');
    await page.click('nav [data-page=sources]');await page.waitForSelector('[data-action=connect]');await page.click('[data-action=connect]');let account;for(let i=0;i<100;i++){account=await page.evaluate(async()=>{const r=await window.lens.query({});return {state:r.value.account.state,windows:r.value.account.quota?.windows.length,plan:r.value.account.plan,error:r.value.account.lastError};});if(account.windows&&account.state==='connected')break;if(['error','degraded','signed_out'].includes(account.state))break;await page.waitForTimeout(500);}console.log(JSON.stringify({account}));assert.equal(account.state,'connected');assert.ok(account.windows>0);results.push('Official account quota query works');
    await page.click('[data-page=settings]');await page.waitForSelector('#settings-form');await page.fill('#paid','200');await page.selectOption('#theme','dark');await page.click('button[type=submit]');await page.waitForFunction(()=>document.body.classList.contains('dark'));await page.screenshot({path:path.join(base,'settings-dark.png'),fullPage:true});results.push('Settings persist and theme applies');
    await page.selectOption('#theme','light');await page.click('button[type=submit]');await page.waitForFunction(()=>!document.body.classList.contains('dark'));await page.click('nav [data-page=models]');await page.waitForSelector('table');assert.ok(await page.locator('tbody tr').count()>=5);results.push('Price catalog shown');
    await page.click('nav [data-page=overview]');await page.waitForSelector('.metrics');await page.screenshot({path:path.join(base,packaged?'release-overview-connected.png':'overview-connected.png'),fullPage:true});
    assert.deepEqual(pageErrors,[]);results.push('No renderer errors');
    await fs.writeFile(path.join(base,packaged?'release-smoke.json':'smoke.json'),JSON.stringify({testedAt:new Date().toISOString(),packaged,results,data,account},null,2));console.log(JSON.stringify({results,data,account},null,2));
  }finally{await app.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
